/*
 * Copyright 2010-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
package com.amazonaws.services.apigateway.model;

import java.io.Serializable;


/**
 * <p>Represents the data structure of a method's request or response payload.</p> <div class="remarks"> <p>A request model defines the data structure of the client-supplied request payload. A response model defines the data structure of the response payload returned by the back end. Although not required, models are useful for mapping payloads between the front end and back end.</p> <p>A model is used for generating an API's SDK, validating the input request body, and creating a skeletal mapping template.</p> </div> <div class="seeAlso"> <a>Method</a>, <a>MethodResponse</a>, <a href="https://docs.aws.amazon.com/apigateway/latest/developerguide/models-mappings.html">Models and Mappings</a> </div>
 */
public class UpdateModelResult implements Serializable {
    /**
     * <p>The identifier for the model resource.</p>
     */
    private String id;

    /**
     * <p>The name of the model. Must be an alphanumeric string.</p>
     */
    private String name;

    /**
     * <p>The description of the model.</p>
     */
    private String description;

    /**
     * <p>The schema for the model. For <code>application/json</code> models, this should be <a href="https://tools.ietf.org/html/draft-zyp-json-schema-04" target="_blank">JSON schema draft 4</a> model. Do not include "\*/" characters in the description of any properties because such "\*/" characters may be interpreted as the closing marker for comments in some languages, such as Java or JavaScript, causing the installation of your API's SDK generated by API Gateway to fail.</p>
     */
    private String schema;

    /**
     * <p>The content-type for the model.</p>
     */
    private String contentType;

    /**
     * <p>The identifier for the model resource.</p>
     *
     * @return <p>The identifier for the model resource.</p>
     */
    public String getId() {
        return id;
    }

    /**
     * <p>The identifier for the model resource.</p>
     *
     * @param id <p>The identifier for the model resource.</p>
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * <p>The identifier for the model resource.</p>
     * <p>
     * Returns a reference to this object so that method calls can be chained together.
     *
     * @param id <p>The identifier for the model resource.</p>
     *
     * @return A reference to this updated object so that method calls can be chained together.
     */
    public UpdateModelResult withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * <p>The name of the model. Must be an alphanumeric string.</p>
     *
     * @return <p>The name of the model. Must be an alphanumeric string.</p>
     */
    public String getName() {
        return name;
    }

    /**
     * <p>The name of the model. Must be an alphanumeric string.</p>
     *
     * @param name <p>The name of the model. Must be an alphanumeric string.</p>
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * <p>The name of the model. Must be an alphanumeric string.</p>
     * <p>
     * Returns a reference to this object so that method calls can be chained together.
     *
     * @param name <p>The name of the model. Must be an alphanumeric string.</p>
     *
     * @return A reference to this updated object so that method calls can be chained together.
     */
    public UpdateModelResult withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * <p>The description of the model.</p>
     *
     * @return <p>The description of the model.</p>
     */
    public String getDescription() {
        return description;
    }

    /**
     * <p>The description of the model.</p>
     *
     * @param description <p>The description of the model.</p>
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * <p>The description of the model.</p>
     * <p>
     * Returns a reference to this object so that method calls can be chained together.
     *
     * @param description <p>The description of the model.</p>
     *
     * @return A reference to this updated object so that method calls can be chained together.
     */
    public UpdateModelResult withDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * <p>The schema for the model. For <code>application/json</code> models, this should be <a href="https://tools.ietf.org/html/draft-zyp-json-schema-04" target="_blank">JSON schema draft 4</a> model. Do not include "\*/" characters in the description of any properties because such "\*/" characters may be interpreted as the closing marker for comments in some languages, such as Java or JavaScript, causing the installation of your API's SDK generated by API Gateway to fail.</p>
     *
     * @return <p>The schema for the model. For <code>application/json</code> models, this should be <a href="https://tools.ietf.org/html/draft-zyp-json-schema-04" target="_blank">JSON schema draft 4</a> model. Do not include "\*/" characters in the description of any properties because such "\*/" characters may be interpreted as the closing marker for comments in some languages, such as Java or JavaScript, causing the installation of your API's SDK generated by API Gateway to fail.</p>
     */
    public String getSchema() {
        return schema;
    }

    /**
     * <p>The schema for the model. For <code>application/json</code> models, this should be <a href="https://tools.ietf.org/html/draft-zyp-json-schema-04" target="_blank">JSON schema draft 4</a> model. Do not include "\*/" characters in the description of any properties because such "\*/" characters may be interpreted as the closing marker for comments in some languages, such as Java or JavaScript, causing the installation of your API's SDK generated by API Gateway to fail.</p>
     *
     * @param schema <p>The schema for the model. For <code>application/json</code> models, this should be <a href="https://tools.ietf.org/html/draft-zyp-json-schema-04" target="_blank">JSON schema draft 4</a> model. Do not include "\*/" characters in the description of any properties because such "\*/" characters may be interpreted as the closing marker for comments in some languages, such as Java or JavaScript, causing the installation of your API's SDK generated by API Gateway to fail.</p>
     */
    public void setSchema(String schema) {
        this.schema = schema;
    }

    /**
     * <p>The schema for the model. For <code>application/json</code> models, this should be <a href="https://tools.ietf.org/html/draft-zyp-json-schema-04" target="_blank">JSON schema draft 4</a> model. Do not include "\*/" characters in the description of any properties because such "\*/" characters may be interpreted as the closing marker for comments in some languages, such as Java or JavaScript, causing the installation of your API's SDK generated by API Gateway to fail.</p>
     * <p>
     * Returns a reference to this object so that method calls can be chained together.
     *
     * @param schema <p>The schema for the model. For <code>application/json</code> models, this should be <a href="https://tools.ietf.org/html/draft-zyp-json-schema-04" target="_blank">JSON schema draft 4</a> model. Do not include "\*/" characters in the description of any properties because such "\*/" characters may be interpreted as the closing marker for comments in some languages, such as Java or JavaScript, causing the installation of your API's SDK generated by API Gateway to fail.</p>
     *
     * @return A reference to this updated object so that method calls can be chained together.
     */
    public UpdateModelResult withSchema(String schema) {
        this.schema = schema;
        return this;
    }

    /**
     * <p>The content-type for the model.</p>
     *
     * @return <p>The content-type for the model.</p>
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * <p>The content-type for the model.</p>
     *
     * @param contentType <p>The content-type for the model.</p>
     */
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    /**
     * <p>The content-type for the model.</p>
     * <p>
     * Returns a reference to this object so that method calls can be chained together.
     *
     * @param contentType <p>The content-type for the model.</p>
     *
     * @return A reference to this updated object so that method calls can be chained together.
     */
    public UpdateModelResult withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }

    /**
     * Returns a string representation of this object; useful for testing and
     * debugging.
     *
     * @return A string representation of this object.
     *
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("{");
        if (getId() != null) sb.append("id: " + getId() + ",");
        if (getName() != null) sb.append("name: " + getName() + ",");
        if (getDescription() != null) sb.append("description: " + getDescription() + ",");
        if (getSchema() != null) sb.append("schema: " + getSchema() + ",");
        if (getContentType() != null) sb.append("contentType: " + getContentType());
        sb.append("}");
        return sb.toString();
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int hashCode = 1;

        hashCode = prime * hashCode + ((getId() == null) ? 0 : getId().hashCode());
        hashCode = prime * hashCode + ((getName() == null) ? 0 : getName().hashCode());
        hashCode = prime * hashCode + ((getDescription() == null) ? 0 : getDescription().hashCode());
        hashCode = prime * hashCode + ((getSchema() == null) ? 0 : getSchema().hashCode());
        hashCode = prime * hashCode + ((getContentType() == null) ? 0 : getContentType().hashCode());
        return hashCode;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;

        if (obj instanceof UpdateModelResult == false) return false;
        UpdateModelResult other = (UpdateModelResult)obj;

        if (other.getId() == null ^ this.getId() == null) return false;
        if (other.getId() != null && other.getId().equals(this.getId()) == false) return false;
        if (other.getName() == null ^ this.getName() == null) return false;
        if (other.getName() != null && other.getName().equals(this.getName()) == false) return false;
        if (other.getDescription() == null ^ this.getDescription() == null) return false;
        if (other.getDescription() != null && other.getDescription().equals(this.getDescription()) == false) return false;
        if (other.getSchema() == null ^ this.getSchema() == null) return false;
        if (other.getSchema() != null && other.getSchema().equals(this.getSchema()) == false) return false;
        if (other.getContentType() == null ^ this.getContentType() == null) return false;
        if (other.getContentType() != null && other.getContentType().equals(this.getContentType()) == false) return false;
        return true;
    }
}
