source "https://rubygems.org"

gem "fastlane"
gem "addressable", ">= 2.8.0"
gem "json", ">= 2.19.2"
gem "rexml", ">= 3.4.2"

eval_gemfile("fastlane/Pluginfile") if File.exist?(File.join(__dir__, "fastlane", "Pluginfile"))
