/*
 * Copyright 2010-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package com.amazonaws.services.awstransferfamily.model;

import java.io.Serializable;

import com.amazonaws.AmazonWebServiceRequest;

/**
 * <p>
 * Updates the file transfer protocol-enabled server's properties after that
 * server has been created.
 * </p>
 * <p>
 * The <code>UpdateServer</code> call returns the <code>ServerId</code> of the
 * server you updated.
 * </p>
 */
public class UpdateServerRequest extends AmazonWebServiceRequest implements Serializable {
    /**
     * <p>
     * The Amazon Resource Name (ARN) of the AWS Certificate Manager (ACM)
     * certificate. Required when <code>Protocols</code> is set to
     * <code>FTPS</code>.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b> - 1600<br/>
     */
    private String certificate;

    /**
     * <p>
     * The virtual private cloud (VPC) endpoint settings that are configured for
     * your file transfer protocol-enabled server. With a VPC endpoint, you can
     * restrict access to your server to resources only within your VPC. To
     * control incoming internet traffic, you will need to associate one or more
     * Elastic IP addresses with your server's endpoint.
     * </p>
     */
    private EndpointDetails endpointDetails;

    /**
     * <p>
     * The type of endpoint that you want your file transfer protocol-enabled
     * server to connect to. You can choose to connect to the public internet or
     * a VPC endpoint. With a VPC endpoint, your server isn't accessible over
     * the public internet.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>PUBLIC, VPC, VPC_ENDPOINT
     */
    private String endpointType;

    /**
     * <p>
     * The RSA private key as generated by
     * <code>ssh-keygen -N "" -f my-new-server-key</code>.
     * </p>
     * <important>
     * <p>
     * If you aren't planning to migrate existing users from an existing file
     * transfer protocol-enabled server to a new server, don't update the host
     * key. Accidentally changing a server's host key can be disruptive.
     * </p>
     * </important>
     * <p>
     * For more information, see <a href=
     * "https://docs.aws.amazon.com/transfer/latest/userguide/configuring-servers.html#change-host-key"
     * >Changing the Host Key for Your AWS Transfer Family Server</a> in the
     * <i>AWS Transfer Family User Guide</i>.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b> - 4096<br/>
     */
    private String hostKey;

    /**
     * <p>
     * An array containing all of the information required to call a customer's
     * authentication API method.
     * </p>
     */
    private IdentityProviderDetails identityProviderDetails;

    /**
     * <p>
     * Changes the AWS Identity and Access Management (IAM) role that allows
     * Amazon S3 events to be logged in Amazon CloudWatch, turning logging on or
     * off.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b> - 2048<br/>
     * <b>Pattern: </b>^$|arn:.*role/.*<br/>
     */
    private String loggingRole;

    /**
     * <p>
     * Specifies the file transfer protocol or protocols over which your file
     * transfer protocol client can connect to your server's endpoint. The
     * available protocols are:
     * </p>
     * <ul>
     * <li>
     * <p>
     * Secure Shell (SSH) File Transfer Protocol (SFTP): File transfer over SSH
     * </p>
     * </li>
     * <li>
     * <p>
     * File Transfer Protocol Secure (FTPS): File transfer with TLS encryption
     * </p>
     * </li>
     * <li>
     * <p>
     * File Transfer Protocol (FTP): Unencrypted file transfer
     * </p>
     * </li>
     * </ul>
     */
    private java.util.List<String> protocols;

    /**
     * <p>
     * A system-assigned unique identifier for a file transfer protocol-enabled
     * server instance that the user account is assigned to.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>19 - 19<br/>
     * <b>Pattern: </b>^s-([0-9a-f]{17})$<br/>
     */
    private String serverId;

    /**
     * <p>
     * The Amazon Resource Name (ARN) of the AWS Certificate Manager (ACM)
     * certificate. Required when <code>Protocols</code> is set to
     * <code>FTPS</code>.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b> - 1600<br/>
     *
     * @return <p>
     *         The Amazon Resource Name (ARN) of the AWS Certificate Manager
     *         (ACM) certificate. Required when <code>Protocols</code> is set to
     *         <code>FTPS</code>.
     *         </p>
     */
    public String getCertificate() {
        return certificate;
    }

    /**
     * <p>
     * The Amazon Resource Name (ARN) of the AWS Certificate Manager (ACM)
     * certificate. Required when <code>Protocols</code> is set to
     * <code>FTPS</code>.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b> - 1600<br/>
     *
     * @param certificate <p>
     *            The Amazon Resource Name (ARN) of the AWS Certificate Manager
     *            (ACM) certificate. Required when <code>Protocols</code> is set
     *            to <code>FTPS</code>.
     *            </p>
     */
    public void setCertificate(String certificate) {
        this.certificate = certificate;
    }

    /**
     * <p>
     * The Amazon Resource Name (ARN) of the AWS Certificate Manager (ACM)
     * certificate. Required when <code>Protocols</code> is set to
     * <code>FTPS</code>.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b> - 1600<br/>
     *
     * @param certificate <p>
     *            The Amazon Resource Name (ARN) of the AWS Certificate Manager
     *            (ACM) certificate. Required when <code>Protocols</code> is set
     *            to <code>FTPS</code>.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public UpdateServerRequest withCertificate(String certificate) {
        this.certificate = certificate;
        return this;
    }

    /**
     * <p>
     * The virtual private cloud (VPC) endpoint settings that are configured for
     * your file transfer protocol-enabled server. With a VPC endpoint, you can
     * restrict access to your server to resources only within your VPC. To
     * control incoming internet traffic, you will need to associate one or more
     * Elastic IP addresses with your server's endpoint.
     * </p>
     *
     * @return <p>
     *         The virtual private cloud (VPC) endpoint settings that are
     *         configured for your file transfer protocol-enabled server. With a
     *         VPC endpoint, you can restrict access to your server to resources
     *         only within your VPC. To control incoming internet traffic, you
     *         will need to associate one or more Elastic IP addresses with your
     *         server's endpoint.
     *         </p>
     */
    public EndpointDetails getEndpointDetails() {
        return endpointDetails;
    }

    /**
     * <p>
     * The virtual private cloud (VPC) endpoint settings that are configured for
     * your file transfer protocol-enabled server. With a VPC endpoint, you can
     * restrict access to your server to resources only within your VPC. To
     * control incoming internet traffic, you will need to associate one or more
     * Elastic IP addresses with your server's endpoint.
     * </p>
     *
     * @param endpointDetails <p>
     *            The virtual private cloud (VPC) endpoint settings that are
     *            configured for your file transfer protocol-enabled server.
     *            With a VPC endpoint, you can restrict access to your server to
     *            resources only within your VPC. To control incoming internet
     *            traffic, you will need to associate one or more Elastic IP
     *            addresses with your server's endpoint.
     *            </p>
     */
    public void setEndpointDetails(EndpointDetails endpointDetails) {
        this.endpointDetails = endpointDetails;
    }

    /**
     * <p>
     * The virtual private cloud (VPC) endpoint settings that are configured for
     * your file transfer protocol-enabled server. With a VPC endpoint, you can
     * restrict access to your server to resources only within your VPC. To
     * control incoming internet traffic, you will need to associate one or more
     * Elastic IP addresses with your server's endpoint.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param endpointDetails <p>
     *            The virtual private cloud (VPC) endpoint settings that are
     *            configured for your file transfer protocol-enabled server.
     *            With a VPC endpoint, you can restrict access to your server to
     *            resources only within your VPC. To control incoming internet
     *            traffic, you will need to associate one or more Elastic IP
     *            addresses with your server's endpoint.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public UpdateServerRequest withEndpointDetails(EndpointDetails endpointDetails) {
        this.endpointDetails = endpointDetails;
        return this;
    }

    /**
     * <p>
     * The type of endpoint that you want your file transfer protocol-enabled
     * server to connect to. You can choose to connect to the public internet or
     * a VPC endpoint. With a VPC endpoint, your server isn't accessible over
     * the public internet.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>PUBLIC, VPC, VPC_ENDPOINT
     *
     * @return <p>
     *         The type of endpoint that you want your file transfer
     *         protocol-enabled server to connect to. You can choose to connect
     *         to the public internet or a VPC endpoint. With a VPC endpoint,
     *         your server isn't accessible over the public internet.
     *         </p>
     * @see EndpointType
     */
    public String getEndpointType() {
        return endpointType;
    }

    /**
     * <p>
     * The type of endpoint that you want your file transfer protocol-enabled
     * server to connect to. You can choose to connect to the public internet or
     * a VPC endpoint. With a VPC endpoint, your server isn't accessible over
     * the public internet.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>PUBLIC, VPC, VPC_ENDPOINT
     *
     * @param endpointType <p>
     *            The type of endpoint that you want your file transfer
     *            protocol-enabled server to connect to. You can choose to
     *            connect to the public internet or a VPC endpoint. With a VPC
     *            endpoint, your server isn't accessible over the public
     *            internet.
     *            </p>
     * @see EndpointType
     */
    public void setEndpointType(String endpointType) {
        this.endpointType = endpointType;
    }

    /**
     * <p>
     * The type of endpoint that you want your file transfer protocol-enabled
     * server to connect to. You can choose to connect to the public internet or
     * a VPC endpoint. With a VPC endpoint, your server isn't accessible over
     * the public internet.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>PUBLIC, VPC, VPC_ENDPOINT
     *
     * @param endpointType <p>
     *            The type of endpoint that you want your file transfer
     *            protocol-enabled server to connect to. You can choose to
     *            connect to the public internet or a VPC endpoint. With a VPC
     *            endpoint, your server isn't accessible over the public
     *            internet.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     * @see EndpointType
     */
    public UpdateServerRequest withEndpointType(String endpointType) {
        this.endpointType = endpointType;
        return this;
    }

    /**
     * <p>
     * The type of endpoint that you want your file transfer protocol-enabled
     * server to connect to. You can choose to connect to the public internet or
     * a VPC endpoint. With a VPC endpoint, your server isn't accessible over
     * the public internet.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>PUBLIC, VPC, VPC_ENDPOINT
     *
     * @param endpointType <p>
     *            The type of endpoint that you want your file transfer
     *            protocol-enabled server to connect to. You can choose to
     *            connect to the public internet or a VPC endpoint. With a VPC
     *            endpoint, your server isn't accessible over the public
     *            internet.
     *            </p>
     * @see EndpointType
     */
    public void setEndpointType(EndpointType endpointType) {
        this.endpointType = endpointType.toString();
    }

    /**
     * <p>
     * The type of endpoint that you want your file transfer protocol-enabled
     * server to connect to. You can choose to connect to the public internet or
     * a VPC endpoint. With a VPC endpoint, your server isn't accessible over
     * the public internet.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>PUBLIC, VPC, VPC_ENDPOINT
     *
     * @param endpointType <p>
     *            The type of endpoint that you want your file transfer
     *            protocol-enabled server to connect to. You can choose to
     *            connect to the public internet or a VPC endpoint. With a VPC
     *            endpoint, your server isn't accessible over the public
     *            internet.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     * @see EndpointType
     */
    public UpdateServerRequest withEndpointType(EndpointType endpointType) {
        this.endpointType = endpointType.toString();
        return this;
    }

    /**
     * <p>
     * The RSA private key as generated by
     * <code>ssh-keygen -N "" -f my-new-server-key</code>.
     * </p>
     * <important>
     * <p>
     * If you aren't planning to migrate existing users from an existing file
     * transfer protocol-enabled server to a new server, don't update the host
     * key. Accidentally changing a server's host key can be disruptive.
     * </p>
     * </important>
     * <p>
     * For more information, see <a href=
     * "https://docs.aws.amazon.com/transfer/latest/userguide/configuring-servers.html#change-host-key"
     * >Changing the Host Key for Your AWS Transfer Family Server</a> in the
     * <i>AWS Transfer Family User Guide</i>.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b> - 4096<br/>
     *
     * @return <p>
     *         The RSA private key as generated by
     *         <code>ssh-keygen -N "" -f my-new-server-key</code>.
     *         </p>
     *         <important>
     *         <p>
     *         If you aren't planning to migrate existing users from an existing
     *         file transfer protocol-enabled server to a new server, don't
     *         update the host key. Accidentally changing a server's host key
     *         can be disruptive.
     *         </p>
     *         </important>
     *         <p>
     *         For more information, see <a href=
     *         "https://docs.aws.amazon.com/transfer/latest/userguide/configuring-servers.html#change-host-key"
     *         >Changing the Host Key for Your AWS Transfer Family Server</a> in
     *         the <i>AWS Transfer Family User Guide</i>.
     *         </p>
     */
    public String getHostKey() {
        return hostKey;
    }

    /**
     * <p>
     * The RSA private key as generated by
     * <code>ssh-keygen -N "" -f my-new-server-key</code>.
     * </p>
     * <important>
     * <p>
     * If you aren't planning to migrate existing users from an existing file
     * transfer protocol-enabled server to a new server, don't update the host
     * key. Accidentally changing a server's host key can be disruptive.
     * </p>
     * </important>
     * <p>
     * For more information, see <a href=
     * "https://docs.aws.amazon.com/transfer/latest/userguide/configuring-servers.html#change-host-key"
     * >Changing the Host Key for Your AWS Transfer Family Server</a> in the
     * <i>AWS Transfer Family User Guide</i>.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b> - 4096<br/>
     *
     * @param hostKey <p>
     *            The RSA private key as generated by
     *            <code>ssh-keygen -N "" -f my-new-server-key</code>.
     *            </p>
     *            <important>
     *            <p>
     *            If you aren't planning to migrate existing users from an
     *            existing file transfer protocol-enabled server to a new
     *            server, don't update the host key. Accidentally changing a
     *            server's host key can be disruptive.
     *            </p>
     *            </important>
     *            <p>
     *            For more information, see <a href=
     *            "https://docs.aws.amazon.com/transfer/latest/userguide/configuring-servers.html#change-host-key"
     *            >Changing the Host Key for Your AWS Transfer Family Server</a>
     *            in the <i>AWS Transfer Family User Guide</i>.
     *            </p>
     */
    public void setHostKey(String hostKey) {
        this.hostKey = hostKey;
    }

    /**
     * <p>
     * The RSA private key as generated by
     * <code>ssh-keygen -N "" -f my-new-server-key</code>.
     * </p>
     * <important>
     * <p>
     * If you aren't planning to migrate existing users from an existing file
     * transfer protocol-enabled server to a new server, don't update the host
     * key. Accidentally changing a server's host key can be disruptive.
     * </p>
     * </important>
     * <p>
     * For more information, see <a href=
     * "https://docs.aws.amazon.com/transfer/latest/userguide/configuring-servers.html#change-host-key"
     * >Changing the Host Key for Your AWS Transfer Family Server</a> in the
     * <i>AWS Transfer Family User Guide</i>.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b> - 4096<br/>
     *
     * @param hostKey <p>
     *            The RSA private key as generated by
     *            <code>ssh-keygen -N "" -f my-new-server-key</code>.
     *            </p>
     *            <important>
     *            <p>
     *            If you aren't planning to migrate existing users from an
     *            existing file transfer protocol-enabled server to a new
     *            server, don't update the host key. Accidentally changing a
     *            server's host key can be disruptive.
     *            </p>
     *            </important>
     *            <p>
     *            For more information, see <a href=
     *            "https://docs.aws.amazon.com/transfer/latest/userguide/configuring-servers.html#change-host-key"
     *            >Changing the Host Key for Your AWS Transfer Family Server</a>
     *            in the <i>AWS Transfer Family User Guide</i>.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public UpdateServerRequest withHostKey(String hostKey) {
        this.hostKey = hostKey;
        return this;
    }

    /**
     * <p>
     * An array containing all of the information required to call a customer's
     * authentication API method.
     * </p>
     *
     * @return <p>
     *         An array containing all of the information required to call a
     *         customer's authentication API method.
     *         </p>
     */
    public IdentityProviderDetails getIdentityProviderDetails() {
        return identityProviderDetails;
    }

    /**
     * <p>
     * An array containing all of the information required to call a customer's
     * authentication API method.
     * </p>
     *
     * @param identityProviderDetails <p>
     *            An array containing all of the information required to call a
     *            customer's authentication API method.
     *            </p>
     */
    public void setIdentityProviderDetails(IdentityProviderDetails identityProviderDetails) {
        this.identityProviderDetails = identityProviderDetails;
    }

    /**
     * <p>
     * An array containing all of the information required to call a customer's
     * authentication API method.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param identityProviderDetails <p>
     *            An array containing all of the information required to call a
     *            customer's authentication API method.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public UpdateServerRequest withIdentityProviderDetails(
            IdentityProviderDetails identityProviderDetails) {
        this.identityProviderDetails = identityProviderDetails;
        return this;
    }

    /**
     * <p>
     * Changes the AWS Identity and Access Management (IAM) role that allows
     * Amazon S3 events to be logged in Amazon CloudWatch, turning logging on or
     * off.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b> - 2048<br/>
     * <b>Pattern: </b>^$|arn:.*role/.*<br/>
     *
     * @return <p>
     *         Changes the AWS Identity and Access Management (IAM) role that
     *         allows Amazon S3 events to be logged in Amazon CloudWatch,
     *         turning logging on or off.
     *         </p>
     */
    public String getLoggingRole() {
        return loggingRole;
    }

    /**
     * <p>
     * Changes the AWS Identity and Access Management (IAM) role that allows
     * Amazon S3 events to be logged in Amazon CloudWatch, turning logging on or
     * off.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b> - 2048<br/>
     * <b>Pattern: </b>^$|arn:.*role/.*<br/>
     *
     * @param loggingRole <p>
     *            Changes the AWS Identity and Access Management (IAM) role that
     *            allows Amazon S3 events to be logged in Amazon CloudWatch,
     *            turning logging on or off.
     *            </p>
     */
    public void setLoggingRole(String loggingRole) {
        this.loggingRole = loggingRole;
    }

    /**
     * <p>
     * Changes the AWS Identity and Access Management (IAM) role that allows
     * Amazon S3 events to be logged in Amazon CloudWatch, turning logging on or
     * off.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b> - 2048<br/>
     * <b>Pattern: </b>^$|arn:.*role/.*<br/>
     *
     * @param loggingRole <p>
     *            Changes the AWS Identity and Access Management (IAM) role that
     *            allows Amazon S3 events to be logged in Amazon CloudWatch,
     *            turning logging on or off.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public UpdateServerRequest withLoggingRole(String loggingRole) {
        this.loggingRole = loggingRole;
        return this;
    }

    /**
     * <p>
     * Specifies the file transfer protocol or protocols over which your file
     * transfer protocol client can connect to your server's endpoint. The
     * available protocols are:
     * </p>
     * <ul>
     * <li>
     * <p>
     * Secure Shell (SSH) File Transfer Protocol (SFTP): File transfer over SSH
     * </p>
     * </li>
     * <li>
     * <p>
     * File Transfer Protocol Secure (FTPS): File transfer with TLS encryption
     * </p>
     * </li>
     * <li>
     * <p>
     * File Transfer Protocol (FTP): Unencrypted file transfer
     * </p>
     * </li>
     * </ul>
     *
     * @return <p>
     *         Specifies the file transfer protocol or protocols over which your
     *         file transfer protocol client can connect to your server's
     *         endpoint. The available protocols are:
     *         </p>
     *         <ul>
     *         <li>
     *         <p>
     *         Secure Shell (SSH) File Transfer Protocol (SFTP): File transfer
     *         over SSH
     *         </p>
     *         </li>
     *         <li>
     *         <p>
     *         File Transfer Protocol Secure (FTPS): File transfer with TLS
     *         encryption
     *         </p>
     *         </li>
     *         <li>
     *         <p>
     *         File Transfer Protocol (FTP): Unencrypted file transfer
     *         </p>
     *         </li>
     *         </ul>
     */
    public java.util.List<String> getProtocols() {
        return protocols;
    }

    /**
     * <p>
     * Specifies the file transfer protocol or protocols over which your file
     * transfer protocol client can connect to your server's endpoint. The
     * available protocols are:
     * </p>
     * <ul>
     * <li>
     * <p>
     * Secure Shell (SSH) File Transfer Protocol (SFTP): File transfer over SSH
     * </p>
     * </li>
     * <li>
     * <p>
     * File Transfer Protocol Secure (FTPS): File transfer with TLS encryption
     * </p>
     * </li>
     * <li>
     * <p>
     * File Transfer Protocol (FTP): Unencrypted file transfer
     * </p>
     * </li>
     * </ul>
     *
     * @param protocols <p>
     *            Specifies the file transfer protocol or protocols over which
     *            your file transfer protocol client can connect to your
     *            server's endpoint. The available protocols are:
     *            </p>
     *            <ul>
     *            <li>
     *            <p>
     *            Secure Shell (SSH) File Transfer Protocol (SFTP): File
     *            transfer over SSH
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            File Transfer Protocol Secure (FTPS): File transfer with TLS
     *            encryption
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            File Transfer Protocol (FTP): Unencrypted file transfer
     *            </p>
     *            </li>
     *            </ul>
     */
    public void setProtocols(java.util.Collection<String> protocols) {
        if (protocols == null) {
            this.protocols = null;
            return;
        }

        this.protocols = new java.util.ArrayList<String>(protocols);
    }

    /**
     * <p>
     * Specifies the file transfer protocol or protocols over which your file
     * transfer protocol client can connect to your server's endpoint. The
     * available protocols are:
     * </p>
     * <ul>
     * <li>
     * <p>
     * Secure Shell (SSH) File Transfer Protocol (SFTP): File transfer over SSH
     * </p>
     * </li>
     * <li>
     * <p>
     * File Transfer Protocol Secure (FTPS): File transfer with TLS encryption
     * </p>
     * </li>
     * <li>
     * <p>
     * File Transfer Protocol (FTP): Unencrypted file transfer
     * </p>
     * </li>
     * </ul>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param protocols <p>
     *            Specifies the file transfer protocol or protocols over which
     *            your file transfer protocol client can connect to your
     *            server's endpoint. The available protocols are:
     *            </p>
     *            <ul>
     *            <li>
     *            <p>
     *            Secure Shell (SSH) File Transfer Protocol (SFTP): File
     *            transfer over SSH
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            File Transfer Protocol Secure (FTPS): File transfer with TLS
     *            encryption
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            File Transfer Protocol (FTP): Unencrypted file transfer
     *            </p>
     *            </li>
     *            </ul>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public UpdateServerRequest withProtocols(String... protocols) {
        if (getProtocols() == null) {
            this.protocols = new java.util.ArrayList<String>(protocols.length);
        }
        for (String value : protocols) {
            this.protocols.add(value);
        }
        return this;
    }

    /**
     * <p>
     * Specifies the file transfer protocol or protocols over which your file
     * transfer protocol client can connect to your server's endpoint. The
     * available protocols are:
     * </p>
     * <ul>
     * <li>
     * <p>
     * Secure Shell (SSH) File Transfer Protocol (SFTP): File transfer over SSH
     * </p>
     * </li>
     * <li>
     * <p>
     * File Transfer Protocol Secure (FTPS): File transfer with TLS encryption
     * </p>
     * </li>
     * <li>
     * <p>
     * File Transfer Protocol (FTP): Unencrypted file transfer
     * </p>
     * </li>
     * </ul>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param protocols <p>
     *            Specifies the file transfer protocol or protocols over which
     *            your file transfer protocol client can connect to your
     *            server's endpoint. The available protocols are:
     *            </p>
     *            <ul>
     *            <li>
     *            <p>
     *            Secure Shell (SSH) File Transfer Protocol (SFTP): File
     *            transfer over SSH
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            File Transfer Protocol Secure (FTPS): File transfer with TLS
     *            encryption
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            File Transfer Protocol (FTP): Unencrypted file transfer
     *            </p>
     *            </li>
     *            </ul>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public UpdateServerRequest withProtocols(java.util.Collection<String> protocols) {
        setProtocols(protocols);
        return this;
    }

    /**
     * <p>
     * A system-assigned unique identifier for a file transfer protocol-enabled
     * server instance that the user account is assigned to.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>19 - 19<br/>
     * <b>Pattern: </b>^s-([0-9a-f]{17})$<br/>
     *
     * @return <p>
     *         A system-assigned unique identifier for a file transfer
     *         protocol-enabled server instance that the user account is
     *         assigned to.
     *         </p>
     */
    public String getServerId() {
        return serverId;
    }

    /**
     * <p>
     * A system-assigned unique identifier for a file transfer protocol-enabled
     * server instance that the user account is assigned to.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>19 - 19<br/>
     * <b>Pattern: </b>^s-([0-9a-f]{17})$<br/>
     *
     * @param serverId <p>
     *            A system-assigned unique identifier for a file transfer
     *            protocol-enabled server instance that the user account is
     *            assigned to.
     *            </p>
     */
    public void setServerId(String serverId) {
        this.serverId = serverId;
    }

    /**
     * <p>
     * A system-assigned unique identifier for a file transfer protocol-enabled
     * server instance that the user account is assigned to.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>19 - 19<br/>
     * <b>Pattern: </b>^s-([0-9a-f]{17})$<br/>
     *
     * @param serverId <p>
     *            A system-assigned unique identifier for a file transfer
     *            protocol-enabled server instance that the user account is
     *            assigned to.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public UpdateServerRequest withServerId(String serverId) {
        this.serverId = serverId;
        return this;
    }

    /**
     * Returns a string representation of this object; useful for testing and
     * debugging.
     *
     * @return A string representation of this object.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("{");
        if (getCertificate() != null)
            sb.append("Certificate: " + getCertificate() + ",");
        if (getEndpointDetails() != null)
            sb.append("EndpointDetails: " + getEndpointDetails() + ",");
        if (getEndpointType() != null)
            sb.append("EndpointType: " + getEndpointType() + ",");
        if (getHostKey() != null)
            sb.append("HostKey: " + getHostKey() + ",");
        if (getIdentityProviderDetails() != null)
            sb.append("IdentityProviderDetails: " + getIdentityProviderDetails() + ",");
        if (getLoggingRole() != null)
            sb.append("LoggingRole: " + getLoggingRole() + ",");
        if (getProtocols() != null)
            sb.append("Protocols: " + getProtocols() + ",");
        if (getServerId() != null)
            sb.append("ServerId: " + getServerId());
        sb.append("}");
        return sb.toString();
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int hashCode = 1;

        hashCode = prime * hashCode
                + ((getCertificate() == null) ? 0 : getCertificate().hashCode());
        hashCode = prime * hashCode
                + ((getEndpointDetails() == null) ? 0 : getEndpointDetails().hashCode());
        hashCode = prime * hashCode
                + ((getEndpointType() == null) ? 0 : getEndpointType().hashCode());
        hashCode = prime * hashCode + ((getHostKey() == null) ? 0 : getHostKey().hashCode());
        hashCode = prime
                * hashCode
                + ((getIdentityProviderDetails() == null) ? 0 : getIdentityProviderDetails()
                        .hashCode());
        hashCode = prime * hashCode
                + ((getLoggingRole() == null) ? 0 : getLoggingRole().hashCode());
        hashCode = prime * hashCode + ((getProtocols() == null) ? 0 : getProtocols().hashCode());
        hashCode = prime * hashCode + ((getServerId() == null) ? 0 : getServerId().hashCode());
        return hashCode;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;

        if (obj instanceof UpdateServerRequest == false)
            return false;
        UpdateServerRequest other = (UpdateServerRequest) obj;

        if (other.getCertificate() == null ^ this.getCertificate() == null)
            return false;
        if (other.getCertificate() != null
                && other.getCertificate().equals(this.getCertificate()) == false)
            return false;
        if (other.getEndpointDetails() == null ^ this.getEndpointDetails() == null)
            return false;
        if (other.getEndpointDetails() != null
                && other.getEndpointDetails().equals(this.getEndpointDetails()) == false)
            return false;
        if (other.getEndpointType() == null ^ this.getEndpointType() == null)
            return false;
        if (other.getEndpointType() != null
                && other.getEndpointType().equals(this.getEndpointType()) == false)
            return false;
        if (other.getHostKey() == null ^ this.getHostKey() == null)
            return false;
        if (other.getHostKey() != null && other.getHostKey().equals(this.getHostKey()) == false)
            return false;
        if (other.getIdentityProviderDetails() == null ^ this.getIdentityProviderDetails() == null)
            return false;
        if (other.getIdentityProviderDetails() != null
                && other.getIdentityProviderDetails().equals(this.getIdentityProviderDetails()) == false)
            return false;
        if (other.getLoggingRole() == null ^ this.getLoggingRole() == null)
            return false;
        if (other.getLoggingRole() != null
                && other.getLoggingRole().equals(this.getLoggingRole()) == false)
            return false;
        if (other.getProtocols() == null ^ this.getProtocols() == null)
            return false;
        if (other.getProtocols() != null
                && other.getProtocols().equals(this.getProtocols()) == false)
            return false;
        if (other.getServerId() == null ^ this.getServerId() == null)
            return false;
        if (other.getServerId() != null && other.getServerId().equals(this.getServerId()) == false)
            return false;
        return true;
    }
}
