/*
 * Copyright 2010-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package com.amazonaws.services.awssecurityhub.model;

import java.io.Serializable;

/**
 * <p>
 * Provides consistent format for the contents of the Security Hub-aggregated
 * findings. <code>AwsSecurityFinding</code> format enables you to share
 * findings between AWS security services and third-party solutions, and
 * security standards checks.
 * </p>
 * <note>
 * <p>
 * A finding is a potential security issue generated either by AWS services
 * (Amazon GuardDuty, Amazon Inspector, and Amazon Macie) or by the integrated
 * third-party solutions and standards checks.
 * </p>
 * </note>
 */
public class AwsSecurityFinding implements Serializable {
    /**
     * <p>
     * The schema version that a finding is formatted for.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     */
    private String schemaVersion;

    /**
     * <p>
     * The security findings provider-specific identifier for a finding.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     */
    private String id;

    /**
     * <p>
     * The ARN generated by Security Hub that uniquely identifies a product that
     * generates findings. This can be the ARN for a third-party product that is
     * integrated with Security Hub, or the ARN for a custom integration.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     */
    private String productArn;

    /**
     * <p>
     * The identifier for the solution-specific component (a discrete unit of
     * logic) that generated a finding. In various security-findings providers'
     * solutions, this generator can be called a rule, a check, a detector, a
     * plug-in, etc.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     */
    private String generatorId;

    /**
     * <p>
     * The AWS account ID that a finding is generated in.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     */
    private String awsAccountId;

    /**
     * <p>
     * One or more finding types in the format of
     * <code>namespace/category/classifier</code> that classify a finding.
     * </p>
     * <p>
     * Valid namespace values are: Software and Configuration Checks | TTPs |
     * Effects | Unusual Behaviors | Sensitive Data Identifications
     * </p>
     */
    private java.util.List<String> types;

    /**
     * <p>
     * An ISO8601-formatted timestamp that indicates when the security-findings
     * provider first observed the potential security issue that a finding
     * captured.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     */
    private String firstObservedAt;

    /**
     * <p>
     * An ISO8601-formatted timestamp that indicates when the security-findings
     * provider most recently observed the potential security issue that a
     * finding captured.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     */
    private String lastObservedAt;

    /**
     * <p>
     * An ISO8601-formatted timestamp that indicates when the security-findings
     * provider created the potential security issue that a finding captured.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     */
    private String createdAt;

    /**
     * <p>
     * An ISO8601-formatted timestamp that indicates when the security-findings
     * provider last updated the finding record.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     */
    private String updatedAt;

    /**
     * <p>
     * A finding's severity.
     * </p>
     */
    private Severity severity;

    /**
     * <p>
     * A finding's confidence. Confidence is defined as the likelihood that a
     * finding accurately identifies the behavior or issue that it was intended
     * to identify.
     * </p>
     * <p>
     * Confidence is scored on a 0-100 basis using a ratio scale, where 0 means
     * zero percent confidence and 100 means 100 percent confidence.
     * </p>
     */
    private Integer confidence;

    /**
     * <p>
     * The level of importance assigned to the resources associated with the
     * finding.
     * </p>
     * <p>
     * A score of 0 means that the underlying resources have no criticality, and
     * a score of 100 is reserved for the most critical resources.
     * </p>
     */
    private Integer criticality;

    /**
     * <p>
     * A finding's title.
     * </p>
     * <note>
     * <p>
     * In this release, <code>Title</code> is a required property.
     * </p>
     * </note>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     */
    private String title;

    /**
     * <p>
     * A finding's description.
     * </p>
     * <note>
     * <p>
     * In this release, <code>Description</code> is a required property.
     * </p>
     * </note>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     */
    private String description;

    /**
     * <p>
     * A data type that describes the remediation options for a finding.
     * </p>
     */
    private Remediation remediation;

    /**
     * <p>
     * A URL that links to a page about the current finding in the
     * security-findings provider's solution.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     */
    private String sourceUrl;

    /**
     * <p>
     * A data type where security-findings providers can include additional
     * solution-specific details that aren't part of the defined
     * <code>AwsSecurityFinding</code> format.
     * </p>
     */
    private java.util.Map<String, String> productFields;

    /**
     * <p>
     * A list of name/value string pairs associated with the finding. These are
     * custom, user-defined fields added to a finding.
     * </p>
     */
    private java.util.Map<String, String> userDefinedFields;

    /**
     * <p>
     * A list of malware related to a finding.
     * </p>
     */
    private java.util.List<Malware> malware;

    /**
     * <p>
     * The details of network-related information about a finding.
     * </p>
     */
    private Network network;

    /**
     * <p>
     * The details of process-related information about a finding.
     * </p>
     */
    private ProcessDetails process;

    /**
     * <p>
     * Threat intelligence details related to a finding.
     * </p>
     */
    private java.util.List<ThreatIntelIndicator> threatIntelIndicators;

    /**
     * <p>
     * A set of resource data types that describe the resources that the finding
     * refers to.
     * </p>
     */
    private java.util.List<Resource> resources;

    /**
     * <p>
     * This data type is exclusive to findings that are generated as the result
     * of a check run against a specific rule in a supported security standard,
     * such as CIS AWS Foundations. Contains security standard-related finding
     * details.
     * </p>
     */
    private Compliance compliance;

    /**
     * <p>
     * Indicates the veracity of a finding.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>UNKNOWN, TRUE_POSITIVE, FALSE_POSITIVE,
     * BENIGN_POSITIVE
     */
    private String verificationState;

    /**
     * <p>
     * The workflow state of a finding.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>NEW, ASSIGNED, IN_PROGRESS, DEFERRED, RESOLVED
     */
    private String workflowState;

    /**
     * <p>
     * Provides information about the status of the investigation into a
     * finding.
     * </p>
     */
    private Workflow workflow;

    /**
     * <p>
     * The record state of a finding.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>ACTIVE, ARCHIVED
     */
    private String recordState;

    /**
     * <p>
     * A list of related findings.
     * </p>
     */
    private java.util.List<RelatedFinding> relatedFindings;

    /**
     * <p>
     * A user-defined note added to a finding.
     * </p>
     */
    private Note note;

    /**
     * <p>
     * The schema version that a finding is formatted for.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @return <p>
     *         The schema version that a finding is formatted for.
     *         </p>
     */
    public String getSchemaVersion() {
        return schemaVersion;
    }

    /**
     * <p>
     * The schema version that a finding is formatted for.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param schemaVersion <p>
     *            The schema version that a finding is formatted for.
     *            </p>
     */
    public void setSchemaVersion(String schemaVersion) {
        this.schemaVersion = schemaVersion;
    }

    /**
     * <p>
     * The schema version that a finding is formatted for.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param schemaVersion <p>
     *            The schema version that a finding is formatted for.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withSchemaVersion(String schemaVersion) {
        this.schemaVersion = schemaVersion;
        return this;
    }

    /**
     * <p>
     * The security findings provider-specific identifier for a finding.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @return <p>
     *         The security findings provider-specific identifier for a finding.
     *         </p>
     */
    public String getId() {
        return id;
    }

    /**
     * <p>
     * The security findings provider-specific identifier for a finding.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param id <p>
     *            The security findings provider-specific identifier for a
     *            finding.
     *            </p>
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * <p>
     * The security findings provider-specific identifier for a finding.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param id <p>
     *            The security findings provider-specific identifier for a
     *            finding.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * <p>
     * The ARN generated by Security Hub that uniquely identifies a product that
     * generates findings. This can be the ARN for a third-party product that is
     * integrated with Security Hub, or the ARN for a custom integration.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @return <p>
     *         The ARN generated by Security Hub that uniquely identifies a
     *         product that generates findings. This can be the ARN for a
     *         third-party product that is integrated with Security Hub, or the
     *         ARN for a custom integration.
     *         </p>
     */
    public String getProductArn() {
        return productArn;
    }

    /**
     * <p>
     * The ARN generated by Security Hub that uniquely identifies a product that
     * generates findings. This can be the ARN for a third-party product that is
     * integrated with Security Hub, or the ARN for a custom integration.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param productArn <p>
     *            The ARN generated by Security Hub that uniquely identifies a
     *            product that generates findings. This can be the ARN for a
     *            third-party product that is integrated with Security Hub, or
     *            the ARN for a custom integration.
     *            </p>
     */
    public void setProductArn(String productArn) {
        this.productArn = productArn;
    }

    /**
     * <p>
     * The ARN generated by Security Hub that uniquely identifies a product that
     * generates findings. This can be the ARN for a third-party product that is
     * integrated with Security Hub, or the ARN for a custom integration.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param productArn <p>
     *            The ARN generated by Security Hub that uniquely identifies a
     *            product that generates findings. This can be the ARN for a
     *            third-party product that is integrated with Security Hub, or
     *            the ARN for a custom integration.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withProductArn(String productArn) {
        this.productArn = productArn;
        return this;
    }

    /**
     * <p>
     * The identifier for the solution-specific component (a discrete unit of
     * logic) that generated a finding. In various security-findings providers'
     * solutions, this generator can be called a rule, a check, a detector, a
     * plug-in, etc.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @return <p>
     *         The identifier for the solution-specific component (a discrete
     *         unit of logic) that generated a finding. In various
     *         security-findings providers' solutions, this generator can be
     *         called a rule, a check, a detector, a plug-in, etc.
     *         </p>
     */
    public String getGeneratorId() {
        return generatorId;
    }

    /**
     * <p>
     * The identifier for the solution-specific component (a discrete unit of
     * logic) that generated a finding. In various security-findings providers'
     * solutions, this generator can be called a rule, a check, a detector, a
     * plug-in, etc.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param generatorId <p>
     *            The identifier for the solution-specific component (a discrete
     *            unit of logic) that generated a finding. In various
     *            security-findings providers' solutions, this generator can be
     *            called a rule, a check, a detector, a plug-in, etc.
     *            </p>
     */
    public void setGeneratorId(String generatorId) {
        this.generatorId = generatorId;
    }

    /**
     * <p>
     * The identifier for the solution-specific component (a discrete unit of
     * logic) that generated a finding. In various security-findings providers'
     * solutions, this generator can be called a rule, a check, a detector, a
     * plug-in, etc.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param generatorId <p>
     *            The identifier for the solution-specific component (a discrete
     *            unit of logic) that generated a finding. In various
     *            security-findings providers' solutions, this generator can be
     *            called a rule, a check, a detector, a plug-in, etc.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withGeneratorId(String generatorId) {
        this.generatorId = generatorId;
        return this;
    }

    /**
     * <p>
     * The AWS account ID that a finding is generated in.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @return <p>
     *         The AWS account ID that a finding is generated in.
     *         </p>
     */
    public String getAwsAccountId() {
        return awsAccountId;
    }

    /**
     * <p>
     * The AWS account ID that a finding is generated in.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param awsAccountId <p>
     *            The AWS account ID that a finding is generated in.
     *            </p>
     */
    public void setAwsAccountId(String awsAccountId) {
        this.awsAccountId = awsAccountId;
    }

    /**
     * <p>
     * The AWS account ID that a finding is generated in.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param awsAccountId <p>
     *            The AWS account ID that a finding is generated in.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withAwsAccountId(String awsAccountId) {
        this.awsAccountId = awsAccountId;
        return this;
    }

    /**
     * <p>
     * One or more finding types in the format of
     * <code>namespace/category/classifier</code> that classify a finding.
     * </p>
     * <p>
     * Valid namespace values are: Software and Configuration Checks | TTPs |
     * Effects | Unusual Behaviors | Sensitive Data Identifications
     * </p>
     *
     * @return <p>
     *         One or more finding types in the format of
     *         <code>namespace/category/classifier</code> that classify a
     *         finding.
     *         </p>
     *         <p>
     *         Valid namespace values are: Software and Configuration Checks |
     *         TTPs | Effects | Unusual Behaviors | Sensitive Data
     *         Identifications
     *         </p>
     */
    public java.util.List<String> getTypes() {
        return types;
    }

    /**
     * <p>
     * One or more finding types in the format of
     * <code>namespace/category/classifier</code> that classify a finding.
     * </p>
     * <p>
     * Valid namespace values are: Software and Configuration Checks | TTPs |
     * Effects | Unusual Behaviors | Sensitive Data Identifications
     * </p>
     *
     * @param types <p>
     *            One or more finding types in the format of
     *            <code>namespace/category/classifier</code> that classify a
     *            finding.
     *            </p>
     *            <p>
     *            Valid namespace values are: Software and Configuration Checks
     *            | TTPs | Effects | Unusual Behaviors | Sensitive Data
     *            Identifications
     *            </p>
     */
    public void setTypes(java.util.Collection<String> types) {
        if (types == null) {
            this.types = null;
            return;
        }

        this.types = new java.util.ArrayList<String>(types);
    }

    /**
     * <p>
     * One or more finding types in the format of
     * <code>namespace/category/classifier</code> that classify a finding.
     * </p>
     * <p>
     * Valid namespace values are: Software and Configuration Checks | TTPs |
     * Effects | Unusual Behaviors | Sensitive Data Identifications
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param types <p>
     *            One or more finding types in the format of
     *            <code>namespace/category/classifier</code> that classify a
     *            finding.
     *            </p>
     *            <p>
     *            Valid namespace values are: Software and Configuration Checks
     *            | TTPs | Effects | Unusual Behaviors | Sensitive Data
     *            Identifications
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withTypes(String... types) {
        if (getTypes() == null) {
            this.types = new java.util.ArrayList<String>(types.length);
        }
        for (String value : types) {
            this.types.add(value);
        }
        return this;
    }

    /**
     * <p>
     * One or more finding types in the format of
     * <code>namespace/category/classifier</code> that classify a finding.
     * </p>
     * <p>
     * Valid namespace values are: Software and Configuration Checks | TTPs |
     * Effects | Unusual Behaviors | Sensitive Data Identifications
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param types <p>
     *            One or more finding types in the format of
     *            <code>namespace/category/classifier</code> that classify a
     *            finding.
     *            </p>
     *            <p>
     *            Valid namespace values are: Software and Configuration Checks
     *            | TTPs | Effects | Unusual Behaviors | Sensitive Data
     *            Identifications
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withTypes(java.util.Collection<String> types) {
        setTypes(types);
        return this;
    }

    /**
     * <p>
     * An ISO8601-formatted timestamp that indicates when the security-findings
     * provider first observed the potential security issue that a finding
     * captured.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @return <p>
     *         An ISO8601-formatted timestamp that indicates when the
     *         security-findings provider first observed the potential security
     *         issue that a finding captured.
     *         </p>
     */
    public String getFirstObservedAt() {
        return firstObservedAt;
    }

    /**
     * <p>
     * An ISO8601-formatted timestamp that indicates when the security-findings
     * provider first observed the potential security issue that a finding
     * captured.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param firstObservedAt <p>
     *            An ISO8601-formatted timestamp that indicates when the
     *            security-findings provider first observed the potential
     *            security issue that a finding captured.
     *            </p>
     */
    public void setFirstObservedAt(String firstObservedAt) {
        this.firstObservedAt = firstObservedAt;
    }

    /**
     * <p>
     * An ISO8601-formatted timestamp that indicates when the security-findings
     * provider first observed the potential security issue that a finding
     * captured.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param firstObservedAt <p>
     *            An ISO8601-formatted timestamp that indicates when the
     *            security-findings provider first observed the potential
     *            security issue that a finding captured.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withFirstObservedAt(String firstObservedAt) {
        this.firstObservedAt = firstObservedAt;
        return this;
    }

    /**
     * <p>
     * An ISO8601-formatted timestamp that indicates when the security-findings
     * provider most recently observed the potential security issue that a
     * finding captured.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @return <p>
     *         An ISO8601-formatted timestamp that indicates when the
     *         security-findings provider most recently observed the potential
     *         security issue that a finding captured.
     *         </p>
     */
    public String getLastObservedAt() {
        return lastObservedAt;
    }

    /**
     * <p>
     * An ISO8601-formatted timestamp that indicates when the security-findings
     * provider most recently observed the potential security issue that a
     * finding captured.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param lastObservedAt <p>
     *            An ISO8601-formatted timestamp that indicates when the
     *            security-findings provider most recently observed the
     *            potential security issue that a finding captured.
     *            </p>
     */
    public void setLastObservedAt(String lastObservedAt) {
        this.lastObservedAt = lastObservedAt;
    }

    /**
     * <p>
     * An ISO8601-formatted timestamp that indicates when the security-findings
     * provider most recently observed the potential security issue that a
     * finding captured.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param lastObservedAt <p>
     *            An ISO8601-formatted timestamp that indicates when the
     *            security-findings provider most recently observed the
     *            potential security issue that a finding captured.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withLastObservedAt(String lastObservedAt) {
        this.lastObservedAt = lastObservedAt;
        return this;
    }

    /**
     * <p>
     * An ISO8601-formatted timestamp that indicates when the security-findings
     * provider created the potential security issue that a finding captured.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @return <p>
     *         An ISO8601-formatted timestamp that indicates when the
     *         security-findings provider created the potential security issue
     *         that a finding captured.
     *         </p>
     */
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * <p>
     * An ISO8601-formatted timestamp that indicates when the security-findings
     * provider created the potential security issue that a finding captured.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param createdAt <p>
     *            An ISO8601-formatted timestamp that indicates when the
     *            security-findings provider created the potential security
     *            issue that a finding captured.
     *            </p>
     */
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * <p>
     * An ISO8601-formatted timestamp that indicates when the security-findings
     * provider created the potential security issue that a finding captured.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param createdAt <p>
     *            An ISO8601-formatted timestamp that indicates when the
     *            security-findings provider created the potential security
     *            issue that a finding captured.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withCreatedAt(String createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * <p>
     * An ISO8601-formatted timestamp that indicates when the security-findings
     * provider last updated the finding record.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @return <p>
     *         An ISO8601-formatted timestamp that indicates when the
     *         security-findings provider last updated the finding record.
     *         </p>
     */
    public String getUpdatedAt() {
        return updatedAt;
    }

    /**
     * <p>
     * An ISO8601-formatted timestamp that indicates when the security-findings
     * provider last updated the finding record.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param updatedAt <p>
     *            An ISO8601-formatted timestamp that indicates when the
     *            security-findings provider last updated the finding record.
     *            </p>
     */
    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * <p>
     * An ISO8601-formatted timestamp that indicates when the security-findings
     * provider last updated the finding record.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param updatedAt <p>
     *            An ISO8601-formatted timestamp that indicates when the
     *            security-findings provider last updated the finding record.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    /**
     * <p>
     * A finding's severity.
     * </p>
     *
     * @return <p>
     *         A finding's severity.
     *         </p>
     */
    public Severity getSeverity() {
        return severity;
    }

    /**
     * <p>
     * A finding's severity.
     * </p>
     *
     * @param severity <p>
     *            A finding's severity.
     *            </p>
     */
    public void setSeverity(Severity severity) {
        this.severity = severity;
    }

    /**
     * <p>
     * A finding's severity.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param severity <p>
     *            A finding's severity.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withSeverity(Severity severity) {
        this.severity = severity;
        return this;
    }

    /**
     * <p>
     * A finding's confidence. Confidence is defined as the likelihood that a
     * finding accurately identifies the behavior or issue that it was intended
     * to identify.
     * </p>
     * <p>
     * Confidence is scored on a 0-100 basis using a ratio scale, where 0 means
     * zero percent confidence and 100 means 100 percent confidence.
     * </p>
     *
     * @return <p>
     *         A finding's confidence. Confidence is defined as the likelihood
     *         that a finding accurately identifies the behavior or issue that
     *         it was intended to identify.
     *         </p>
     *         <p>
     *         Confidence is scored on a 0-100 basis using a ratio scale, where
     *         0 means zero percent confidence and 100 means 100 percent
     *         confidence.
     *         </p>
     */
    public Integer getConfidence() {
        return confidence;
    }

    /**
     * <p>
     * A finding's confidence. Confidence is defined as the likelihood that a
     * finding accurately identifies the behavior or issue that it was intended
     * to identify.
     * </p>
     * <p>
     * Confidence is scored on a 0-100 basis using a ratio scale, where 0 means
     * zero percent confidence and 100 means 100 percent confidence.
     * </p>
     *
     * @param confidence <p>
     *            A finding's confidence. Confidence is defined as the
     *            likelihood that a finding accurately identifies the behavior
     *            or issue that it was intended to identify.
     *            </p>
     *            <p>
     *            Confidence is scored on a 0-100 basis using a ratio scale,
     *            where 0 means zero percent confidence and 100 means 100
     *            percent confidence.
     *            </p>
     */
    public void setConfidence(Integer confidence) {
        this.confidence = confidence;
    }

    /**
     * <p>
     * A finding's confidence. Confidence is defined as the likelihood that a
     * finding accurately identifies the behavior or issue that it was intended
     * to identify.
     * </p>
     * <p>
     * Confidence is scored on a 0-100 basis using a ratio scale, where 0 means
     * zero percent confidence and 100 means 100 percent confidence.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param confidence <p>
     *            A finding's confidence. Confidence is defined as the
     *            likelihood that a finding accurately identifies the behavior
     *            or issue that it was intended to identify.
     *            </p>
     *            <p>
     *            Confidence is scored on a 0-100 basis using a ratio scale,
     *            where 0 means zero percent confidence and 100 means 100
     *            percent confidence.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withConfidence(Integer confidence) {
        this.confidence = confidence;
        return this;
    }

    /**
     * <p>
     * The level of importance assigned to the resources associated with the
     * finding.
     * </p>
     * <p>
     * A score of 0 means that the underlying resources have no criticality, and
     * a score of 100 is reserved for the most critical resources.
     * </p>
     *
     * @return <p>
     *         The level of importance assigned to the resources associated with
     *         the finding.
     *         </p>
     *         <p>
     *         A score of 0 means that the underlying resources have no
     *         criticality, and a score of 100 is reserved for the most critical
     *         resources.
     *         </p>
     */
    public Integer getCriticality() {
        return criticality;
    }

    /**
     * <p>
     * The level of importance assigned to the resources associated with the
     * finding.
     * </p>
     * <p>
     * A score of 0 means that the underlying resources have no criticality, and
     * a score of 100 is reserved for the most critical resources.
     * </p>
     *
     * @param criticality <p>
     *            The level of importance assigned to the resources associated
     *            with the finding.
     *            </p>
     *            <p>
     *            A score of 0 means that the underlying resources have no
     *            criticality, and a score of 100 is reserved for the most
     *            critical resources.
     *            </p>
     */
    public void setCriticality(Integer criticality) {
        this.criticality = criticality;
    }

    /**
     * <p>
     * The level of importance assigned to the resources associated with the
     * finding.
     * </p>
     * <p>
     * A score of 0 means that the underlying resources have no criticality, and
     * a score of 100 is reserved for the most critical resources.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param criticality <p>
     *            The level of importance assigned to the resources associated
     *            with the finding.
     *            </p>
     *            <p>
     *            A score of 0 means that the underlying resources have no
     *            criticality, and a score of 100 is reserved for the most
     *            critical resources.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withCriticality(Integer criticality) {
        this.criticality = criticality;
        return this;
    }

    /**
     * <p>
     * A finding's title.
     * </p>
     * <note>
     * <p>
     * In this release, <code>Title</code> is a required property.
     * </p>
     * </note>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @return <p>
     *         A finding's title.
     *         </p>
     *         <note>
     *         <p>
     *         In this release, <code>Title</code> is a required property.
     *         </p>
     *         </note>
     */
    public String getTitle() {
        return title;
    }

    /**
     * <p>
     * A finding's title.
     * </p>
     * <note>
     * <p>
     * In this release, <code>Title</code> is a required property.
     * </p>
     * </note>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param title <p>
     *            A finding's title.
     *            </p>
     *            <note>
     *            <p>
     *            In this release, <code>Title</code> is a required property.
     *            </p>
     *            </note>
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * <p>
     * A finding's title.
     * </p>
     * <note>
     * <p>
     * In this release, <code>Title</code> is a required property.
     * </p>
     * </note>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param title <p>
     *            A finding's title.
     *            </p>
     *            <note>
     *            <p>
     *            In this release, <code>Title</code> is a required property.
     *            </p>
     *            </note>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * <p>
     * A finding's description.
     * </p>
     * <note>
     * <p>
     * In this release, <code>Description</code> is a required property.
     * </p>
     * </note>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @return <p>
     *         A finding's description.
     *         </p>
     *         <note>
     *         <p>
     *         In this release, <code>Description</code> is a required property.
     *         </p>
     *         </note>
     */
    public String getDescription() {
        return description;
    }

    /**
     * <p>
     * A finding's description.
     * </p>
     * <note>
     * <p>
     * In this release, <code>Description</code> is a required property.
     * </p>
     * </note>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param description <p>
     *            A finding's description.
     *            </p>
     *            <note>
     *            <p>
     *            In this release, <code>Description</code> is a required
     *            property.
     *            </p>
     *            </note>
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * <p>
     * A finding's description.
     * </p>
     * <note>
     * <p>
     * In this release, <code>Description</code> is a required property.
     * </p>
     * </note>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param description <p>
     *            A finding's description.
     *            </p>
     *            <note>
     *            <p>
     *            In this release, <code>Description</code> is a required
     *            property.
     *            </p>
     *            </note>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * <p>
     * A data type that describes the remediation options for a finding.
     * </p>
     *
     * @return <p>
     *         A data type that describes the remediation options for a finding.
     *         </p>
     */
    public Remediation getRemediation() {
        return remediation;
    }

    /**
     * <p>
     * A data type that describes the remediation options for a finding.
     * </p>
     *
     * @param remediation <p>
     *            A data type that describes the remediation options for a
     *            finding.
     *            </p>
     */
    public void setRemediation(Remediation remediation) {
        this.remediation = remediation;
    }

    /**
     * <p>
     * A data type that describes the remediation options for a finding.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param remediation <p>
     *            A data type that describes the remediation options for a
     *            finding.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withRemediation(Remediation remediation) {
        this.remediation = remediation;
        return this;
    }

    /**
     * <p>
     * A URL that links to a page about the current finding in the
     * security-findings provider's solution.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @return <p>
     *         A URL that links to a page about the current finding in the
     *         security-findings provider's solution.
     *         </p>
     */
    public String getSourceUrl() {
        return sourceUrl;
    }

    /**
     * <p>
     * A URL that links to a page about the current finding in the
     * security-findings provider's solution.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param sourceUrl <p>
     *            A URL that links to a page about the current finding in the
     *            security-findings provider's solution.
     *            </p>
     */
    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl;
    }

    /**
     * <p>
     * A URL that links to a page about the current finding in the
     * security-findings provider's solution.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>.*\S.*<br/>
     *
     * @param sourceUrl <p>
     *            A URL that links to a page about the current finding in the
     *            security-findings provider's solution.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl;
        return this;
    }

    /**
     * <p>
     * A data type where security-findings providers can include additional
     * solution-specific details that aren't part of the defined
     * <code>AwsSecurityFinding</code> format.
     * </p>
     *
     * @return <p>
     *         A data type where security-findings providers can include
     *         additional solution-specific details that aren't part of the
     *         defined <code>AwsSecurityFinding</code> format.
     *         </p>
     */
    public java.util.Map<String, String> getProductFields() {
        return productFields;
    }

    /**
     * <p>
     * A data type where security-findings providers can include additional
     * solution-specific details that aren't part of the defined
     * <code>AwsSecurityFinding</code> format.
     * </p>
     *
     * @param productFields <p>
     *            A data type where security-findings providers can include
     *            additional solution-specific details that aren't part of the
     *            defined <code>AwsSecurityFinding</code> format.
     *            </p>
     */
    public void setProductFields(java.util.Map<String, String> productFields) {
        this.productFields = productFields;
    }

    /**
     * <p>
     * A data type where security-findings providers can include additional
     * solution-specific details that aren't part of the defined
     * <code>AwsSecurityFinding</code> format.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param productFields <p>
     *            A data type where security-findings providers can include
     *            additional solution-specific details that aren't part of the
     *            defined <code>AwsSecurityFinding</code> format.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withProductFields(java.util.Map<String, String> productFields) {
        this.productFields = productFields;
        return this;
    }

    /**
     * <p>
     * A data type where security-findings providers can include additional
     * solution-specific details that aren't part of the defined
     * <code>AwsSecurityFinding</code> format.
     * </p>
     * <p>
     * The method adds a new key-value pair into ProductFields parameter, and
     * returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param key The key of the entry to be added into ProductFields.
     * @param value The corresponding value of the entry to be added into
     *            ProductFields.
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding addProductFieldsEntry(String key, String value) {
        if (null == this.productFields) {
            this.productFields = new java.util.HashMap<String, String>();
        }
        if (this.productFields.containsKey(key))
            throw new IllegalArgumentException("Duplicated keys (" + key.toString()
                    + ") are provided.");
        this.productFields.put(key, value);
        return this;
    }

    /**
     * Removes all the entries added into ProductFields.
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     */
    public AwsSecurityFinding clearProductFieldsEntries() {
        this.productFields = null;
        return this;
    }

    /**
     * <p>
     * A list of name/value string pairs associated with the finding. These are
     * custom, user-defined fields added to a finding.
     * </p>
     *
     * @return <p>
     *         A list of name/value string pairs associated with the finding.
     *         These are custom, user-defined fields added to a finding.
     *         </p>
     */
    public java.util.Map<String, String> getUserDefinedFields() {
        return userDefinedFields;
    }

    /**
     * <p>
     * A list of name/value string pairs associated with the finding. These are
     * custom, user-defined fields added to a finding.
     * </p>
     *
     * @param userDefinedFields <p>
     *            A list of name/value string pairs associated with the finding.
     *            These are custom, user-defined fields added to a finding.
     *            </p>
     */
    public void setUserDefinedFields(java.util.Map<String, String> userDefinedFields) {
        this.userDefinedFields = userDefinedFields;
    }

    /**
     * <p>
     * A list of name/value string pairs associated with the finding. These are
     * custom, user-defined fields added to a finding.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param userDefinedFields <p>
     *            A list of name/value string pairs associated with the finding.
     *            These are custom, user-defined fields added to a finding.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withUserDefinedFields(java.util.Map<String, String> userDefinedFields) {
        this.userDefinedFields = userDefinedFields;
        return this;
    }

    /**
     * <p>
     * A list of name/value string pairs associated with the finding. These are
     * custom, user-defined fields added to a finding.
     * </p>
     * <p>
     * The method adds a new key-value pair into UserDefinedFields parameter,
     * and returns a reference to this object so that method calls can be
     * chained together.
     *
     * @param key The key of the entry to be added into UserDefinedFields.
     * @param value The corresponding value of the entry to be added into
     *            UserDefinedFields.
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding addUserDefinedFieldsEntry(String key, String value) {
        if (null == this.userDefinedFields) {
            this.userDefinedFields = new java.util.HashMap<String, String>();
        }
        if (this.userDefinedFields.containsKey(key))
            throw new IllegalArgumentException("Duplicated keys (" + key.toString()
                    + ") are provided.");
        this.userDefinedFields.put(key, value);
        return this;
    }

    /**
     * Removes all the entries added into UserDefinedFields.
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     */
    public AwsSecurityFinding clearUserDefinedFieldsEntries() {
        this.userDefinedFields = null;
        return this;
    }

    /**
     * <p>
     * A list of malware related to a finding.
     * </p>
     *
     * @return <p>
     *         A list of malware related to a finding.
     *         </p>
     */
    public java.util.List<Malware> getMalware() {
        return malware;
    }

    /**
     * <p>
     * A list of malware related to a finding.
     * </p>
     *
     * @param malware <p>
     *            A list of malware related to a finding.
     *            </p>
     */
    public void setMalware(java.util.Collection<Malware> malware) {
        if (malware == null) {
            this.malware = null;
            return;
        }

        this.malware = new java.util.ArrayList<Malware>(malware);
    }

    /**
     * <p>
     * A list of malware related to a finding.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param malware <p>
     *            A list of malware related to a finding.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withMalware(Malware... malware) {
        if (getMalware() == null) {
            this.malware = new java.util.ArrayList<Malware>(malware.length);
        }
        for (Malware value : malware) {
            this.malware.add(value);
        }
        return this;
    }

    /**
     * <p>
     * A list of malware related to a finding.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param malware <p>
     *            A list of malware related to a finding.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withMalware(java.util.Collection<Malware> malware) {
        setMalware(malware);
        return this;
    }

    /**
     * <p>
     * The details of network-related information about a finding.
     * </p>
     *
     * @return <p>
     *         The details of network-related information about a finding.
     *         </p>
     */
    public Network getNetwork() {
        return network;
    }

    /**
     * <p>
     * The details of network-related information about a finding.
     * </p>
     *
     * @param network <p>
     *            The details of network-related information about a finding.
     *            </p>
     */
    public void setNetwork(Network network) {
        this.network = network;
    }

    /**
     * <p>
     * The details of network-related information about a finding.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param network <p>
     *            The details of network-related information about a finding.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withNetwork(Network network) {
        this.network = network;
        return this;
    }

    /**
     * <p>
     * The details of process-related information about a finding.
     * </p>
     *
     * @return <p>
     *         The details of process-related information about a finding.
     *         </p>
     */
    public ProcessDetails getProcess() {
        return process;
    }

    /**
     * <p>
     * The details of process-related information about a finding.
     * </p>
     *
     * @param process <p>
     *            The details of process-related information about a finding.
     *            </p>
     */
    public void setProcess(ProcessDetails process) {
        this.process = process;
    }

    /**
     * <p>
     * The details of process-related information about a finding.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param process <p>
     *            The details of process-related information about a finding.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withProcess(ProcessDetails process) {
        this.process = process;
        return this;
    }

    /**
     * <p>
     * Threat intelligence details related to a finding.
     * </p>
     *
     * @return <p>
     *         Threat intelligence details related to a finding.
     *         </p>
     */
    public java.util.List<ThreatIntelIndicator> getThreatIntelIndicators() {
        return threatIntelIndicators;
    }

    /**
     * <p>
     * Threat intelligence details related to a finding.
     * </p>
     *
     * @param threatIntelIndicators <p>
     *            Threat intelligence details related to a finding.
     *            </p>
     */
    public void setThreatIntelIndicators(
            java.util.Collection<ThreatIntelIndicator> threatIntelIndicators) {
        if (threatIntelIndicators == null) {
            this.threatIntelIndicators = null;
            return;
        }

        this.threatIntelIndicators = new java.util.ArrayList<ThreatIntelIndicator>(
                threatIntelIndicators);
    }

    /**
     * <p>
     * Threat intelligence details related to a finding.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param threatIntelIndicators <p>
     *            Threat intelligence details related to a finding.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withThreatIntelIndicators(
            ThreatIntelIndicator... threatIntelIndicators) {
        if (getThreatIntelIndicators() == null) {
            this.threatIntelIndicators = new java.util.ArrayList<ThreatIntelIndicator>(
                    threatIntelIndicators.length);
        }
        for (ThreatIntelIndicator value : threatIntelIndicators) {
            this.threatIntelIndicators.add(value);
        }
        return this;
    }

    /**
     * <p>
     * Threat intelligence details related to a finding.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param threatIntelIndicators <p>
     *            Threat intelligence details related to a finding.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withThreatIntelIndicators(
            java.util.Collection<ThreatIntelIndicator> threatIntelIndicators) {
        setThreatIntelIndicators(threatIntelIndicators);
        return this;
    }

    /**
     * <p>
     * A set of resource data types that describe the resources that the finding
     * refers to.
     * </p>
     *
     * @return <p>
     *         A set of resource data types that describe the resources that the
     *         finding refers to.
     *         </p>
     */
    public java.util.List<Resource> getResources() {
        return resources;
    }

    /**
     * <p>
     * A set of resource data types that describe the resources that the finding
     * refers to.
     * </p>
     *
     * @param resources <p>
     *            A set of resource data types that describe the resources that
     *            the finding refers to.
     *            </p>
     */
    public void setResources(java.util.Collection<Resource> resources) {
        if (resources == null) {
            this.resources = null;
            return;
        }

        this.resources = new java.util.ArrayList<Resource>(resources);
    }

    /**
     * <p>
     * A set of resource data types that describe the resources that the finding
     * refers to.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param resources <p>
     *            A set of resource data types that describe the resources that
     *            the finding refers to.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withResources(Resource... resources) {
        if (getResources() == null) {
            this.resources = new java.util.ArrayList<Resource>(resources.length);
        }
        for (Resource value : resources) {
            this.resources.add(value);
        }
        return this;
    }

    /**
     * <p>
     * A set of resource data types that describe the resources that the finding
     * refers to.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param resources <p>
     *            A set of resource data types that describe the resources that
     *            the finding refers to.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withResources(java.util.Collection<Resource> resources) {
        setResources(resources);
        return this;
    }

    /**
     * <p>
     * This data type is exclusive to findings that are generated as the result
     * of a check run against a specific rule in a supported security standard,
     * such as CIS AWS Foundations. Contains security standard-related finding
     * details.
     * </p>
     *
     * @return <p>
     *         This data type is exclusive to findings that are generated as the
     *         result of a check run against a specific rule in a supported
     *         security standard, such as CIS AWS Foundations. Contains security
     *         standard-related finding details.
     *         </p>
     */
    public Compliance getCompliance() {
        return compliance;
    }

    /**
     * <p>
     * This data type is exclusive to findings that are generated as the result
     * of a check run against a specific rule in a supported security standard,
     * such as CIS AWS Foundations. Contains security standard-related finding
     * details.
     * </p>
     *
     * @param compliance <p>
     *            This data type is exclusive to findings that are generated as
     *            the result of a check run against a specific rule in a
     *            supported security standard, such as CIS AWS Foundations.
     *            Contains security standard-related finding details.
     *            </p>
     */
    public void setCompliance(Compliance compliance) {
        this.compliance = compliance;
    }

    /**
     * <p>
     * This data type is exclusive to findings that are generated as the result
     * of a check run against a specific rule in a supported security standard,
     * such as CIS AWS Foundations. Contains security standard-related finding
     * details.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param compliance <p>
     *            This data type is exclusive to findings that are generated as
     *            the result of a check run against a specific rule in a
     *            supported security standard, such as CIS AWS Foundations.
     *            Contains security standard-related finding details.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withCompliance(Compliance compliance) {
        this.compliance = compliance;
        return this;
    }

    /**
     * <p>
     * Indicates the veracity of a finding.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>UNKNOWN, TRUE_POSITIVE, FALSE_POSITIVE,
     * BENIGN_POSITIVE
     *
     * @return <p>
     *         Indicates the veracity of a finding.
     *         </p>
     * @see VerificationState
     */
    public String getVerificationState() {
        return verificationState;
    }

    /**
     * <p>
     * Indicates the veracity of a finding.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>UNKNOWN, TRUE_POSITIVE, FALSE_POSITIVE,
     * BENIGN_POSITIVE
     *
     * @param verificationState <p>
     *            Indicates the veracity of a finding.
     *            </p>
     * @see VerificationState
     */
    public void setVerificationState(String verificationState) {
        this.verificationState = verificationState;
    }

    /**
     * <p>
     * Indicates the veracity of a finding.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>UNKNOWN, TRUE_POSITIVE, FALSE_POSITIVE,
     * BENIGN_POSITIVE
     *
     * @param verificationState <p>
     *            Indicates the veracity of a finding.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     * @see VerificationState
     */
    public AwsSecurityFinding withVerificationState(String verificationState) {
        this.verificationState = verificationState;
        return this;
    }

    /**
     * <p>
     * Indicates the veracity of a finding.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>UNKNOWN, TRUE_POSITIVE, FALSE_POSITIVE,
     * BENIGN_POSITIVE
     *
     * @param verificationState <p>
     *            Indicates the veracity of a finding.
     *            </p>
     * @see VerificationState
     */
    public void setVerificationState(VerificationState verificationState) {
        this.verificationState = verificationState.toString();
    }

    /**
     * <p>
     * Indicates the veracity of a finding.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>UNKNOWN, TRUE_POSITIVE, FALSE_POSITIVE,
     * BENIGN_POSITIVE
     *
     * @param verificationState <p>
     *            Indicates the veracity of a finding.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     * @see VerificationState
     */
    public AwsSecurityFinding withVerificationState(VerificationState verificationState) {
        this.verificationState = verificationState.toString();
        return this;
    }

    /**
     * <p>
     * The workflow state of a finding.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>NEW, ASSIGNED, IN_PROGRESS, DEFERRED, RESOLVED
     *
     * @return <p>
     *         The workflow state of a finding.
     *         </p>
     * @see WorkflowState
     */
    public String getWorkflowState() {
        return workflowState;
    }

    /**
     * <p>
     * The workflow state of a finding.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>NEW, ASSIGNED, IN_PROGRESS, DEFERRED, RESOLVED
     *
     * @param workflowState <p>
     *            The workflow state of a finding.
     *            </p>
     * @see WorkflowState
     */
    public void setWorkflowState(String workflowState) {
        this.workflowState = workflowState;
    }

    /**
     * <p>
     * The workflow state of a finding.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>NEW, ASSIGNED, IN_PROGRESS, DEFERRED, RESOLVED
     *
     * @param workflowState <p>
     *            The workflow state of a finding.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     * @see WorkflowState
     */
    public AwsSecurityFinding withWorkflowState(String workflowState) {
        this.workflowState = workflowState;
        return this;
    }

    /**
     * <p>
     * The workflow state of a finding.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>NEW, ASSIGNED, IN_PROGRESS, DEFERRED, RESOLVED
     *
     * @param workflowState <p>
     *            The workflow state of a finding.
     *            </p>
     * @see WorkflowState
     */
    public void setWorkflowState(WorkflowState workflowState) {
        this.workflowState = workflowState.toString();
    }

    /**
     * <p>
     * The workflow state of a finding.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>NEW, ASSIGNED, IN_PROGRESS, DEFERRED, RESOLVED
     *
     * @param workflowState <p>
     *            The workflow state of a finding.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     * @see WorkflowState
     */
    public AwsSecurityFinding withWorkflowState(WorkflowState workflowState) {
        this.workflowState = workflowState.toString();
        return this;
    }

    /**
     * <p>
     * Provides information about the status of the investigation into a
     * finding.
     * </p>
     *
     * @return <p>
     *         Provides information about the status of the investigation into a
     *         finding.
     *         </p>
     */
    public Workflow getWorkflow() {
        return workflow;
    }

    /**
     * <p>
     * Provides information about the status of the investigation into a
     * finding.
     * </p>
     *
     * @param workflow <p>
     *            Provides information about the status of the investigation
     *            into a finding.
     *            </p>
     */
    public void setWorkflow(Workflow workflow) {
        this.workflow = workflow;
    }

    /**
     * <p>
     * Provides information about the status of the investigation into a
     * finding.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param workflow <p>
     *            Provides information about the status of the investigation
     *            into a finding.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withWorkflow(Workflow workflow) {
        this.workflow = workflow;
        return this;
    }

    /**
     * <p>
     * The record state of a finding.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>ACTIVE, ARCHIVED
     *
     * @return <p>
     *         The record state of a finding.
     *         </p>
     * @see RecordState
     */
    public String getRecordState() {
        return recordState;
    }

    /**
     * <p>
     * The record state of a finding.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>ACTIVE, ARCHIVED
     *
     * @param recordState <p>
     *            The record state of a finding.
     *            </p>
     * @see RecordState
     */
    public void setRecordState(String recordState) {
        this.recordState = recordState;
    }

    /**
     * <p>
     * The record state of a finding.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>ACTIVE, ARCHIVED
     *
     * @param recordState <p>
     *            The record state of a finding.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     * @see RecordState
     */
    public AwsSecurityFinding withRecordState(String recordState) {
        this.recordState = recordState;
        return this;
    }

    /**
     * <p>
     * The record state of a finding.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>ACTIVE, ARCHIVED
     *
     * @param recordState <p>
     *            The record state of a finding.
     *            </p>
     * @see RecordState
     */
    public void setRecordState(RecordState recordState) {
        this.recordState = recordState.toString();
    }

    /**
     * <p>
     * The record state of a finding.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>ACTIVE, ARCHIVED
     *
     * @param recordState <p>
     *            The record state of a finding.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     * @see RecordState
     */
    public AwsSecurityFinding withRecordState(RecordState recordState) {
        this.recordState = recordState.toString();
        return this;
    }

    /**
     * <p>
     * A list of related findings.
     * </p>
     *
     * @return <p>
     *         A list of related findings.
     *         </p>
     */
    public java.util.List<RelatedFinding> getRelatedFindings() {
        return relatedFindings;
    }

    /**
     * <p>
     * A list of related findings.
     * </p>
     *
     * @param relatedFindings <p>
     *            A list of related findings.
     *            </p>
     */
    public void setRelatedFindings(java.util.Collection<RelatedFinding> relatedFindings) {
        if (relatedFindings == null) {
            this.relatedFindings = null;
            return;
        }

        this.relatedFindings = new java.util.ArrayList<RelatedFinding>(relatedFindings);
    }

    /**
     * <p>
     * A list of related findings.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param relatedFindings <p>
     *            A list of related findings.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withRelatedFindings(RelatedFinding... relatedFindings) {
        if (getRelatedFindings() == null) {
            this.relatedFindings = new java.util.ArrayList<RelatedFinding>(relatedFindings.length);
        }
        for (RelatedFinding value : relatedFindings) {
            this.relatedFindings.add(value);
        }
        return this;
    }

    /**
     * <p>
     * A list of related findings.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param relatedFindings <p>
     *            A list of related findings.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withRelatedFindings(
            java.util.Collection<RelatedFinding> relatedFindings) {
        setRelatedFindings(relatedFindings);
        return this;
    }

    /**
     * <p>
     * A user-defined note added to a finding.
     * </p>
     *
     * @return <p>
     *         A user-defined note added to a finding.
     *         </p>
     */
    public Note getNote() {
        return note;
    }

    /**
     * <p>
     * A user-defined note added to a finding.
     * </p>
     *
     * @param note <p>
     *            A user-defined note added to a finding.
     *            </p>
     */
    public void setNote(Note note) {
        this.note = note;
    }

    /**
     * <p>
     * A user-defined note added to a finding.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param note <p>
     *            A user-defined note added to a finding.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public AwsSecurityFinding withNote(Note note) {
        this.note = note;
        return this;
    }

    /**
     * Returns a string representation of this object; useful for testing and
     * debugging.
     *
     * @return A string representation of this object.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("{");
        if (getSchemaVersion() != null)
            sb.append("SchemaVersion: " + getSchemaVersion() + ",");
        if (getId() != null)
            sb.append("Id: " + getId() + ",");
        if (getProductArn() != null)
            sb.append("ProductArn: " + getProductArn() + ",");
        if (getGeneratorId() != null)
            sb.append("GeneratorId: " + getGeneratorId() + ",");
        if (getAwsAccountId() != null)
            sb.append("AwsAccountId: " + getAwsAccountId() + ",");
        if (getTypes() != null)
            sb.append("Types: " + getTypes() + ",");
        if (getFirstObservedAt() != null)
            sb.append("FirstObservedAt: " + getFirstObservedAt() + ",");
        if (getLastObservedAt() != null)
            sb.append("LastObservedAt: " + getLastObservedAt() + ",");
        if (getCreatedAt() != null)
            sb.append("CreatedAt: " + getCreatedAt() + ",");
        if (getUpdatedAt() != null)
            sb.append("UpdatedAt: " + getUpdatedAt() + ",");
        if (getSeverity() != null)
            sb.append("Severity: " + getSeverity() + ",");
        if (getConfidence() != null)
            sb.append("Confidence: " + getConfidence() + ",");
        if (getCriticality() != null)
            sb.append("Criticality: " + getCriticality() + ",");
        if (getTitle() != null)
            sb.append("Title: " + getTitle() + ",");
        if (getDescription() != null)
            sb.append("Description: " + getDescription() + ",");
        if (getRemediation() != null)
            sb.append("Remediation: " + getRemediation() + ",");
        if (getSourceUrl() != null)
            sb.append("SourceUrl: " + getSourceUrl() + ",");
        if (getProductFields() != null)
            sb.append("ProductFields: " + getProductFields() + ",");
        if (getUserDefinedFields() != null)
            sb.append("UserDefinedFields: " + getUserDefinedFields() + ",");
        if (getMalware() != null)
            sb.append("Malware: " + getMalware() + ",");
        if (getNetwork() != null)
            sb.append("Network: " + getNetwork() + ",");
        if (getProcess() != null)
            sb.append("Process: " + getProcess() + ",");
        if (getThreatIntelIndicators() != null)
            sb.append("ThreatIntelIndicators: " + getThreatIntelIndicators() + ",");
        if (getResources() != null)
            sb.append("Resources: " + getResources() + ",");
        if (getCompliance() != null)
            sb.append("Compliance: " + getCompliance() + ",");
        if (getVerificationState() != null)
            sb.append("VerificationState: " + getVerificationState() + ",");
        if (getWorkflowState() != null)
            sb.append("WorkflowState: " + getWorkflowState() + ",");
        if (getWorkflow() != null)
            sb.append("Workflow: " + getWorkflow() + ",");
        if (getRecordState() != null)
            sb.append("RecordState: " + getRecordState() + ",");
        if (getRelatedFindings() != null)
            sb.append("RelatedFindings: " + getRelatedFindings() + ",");
        if (getNote() != null)
            sb.append("Note: " + getNote());
        sb.append("}");
        return sb.toString();
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int hashCode = 1;

        hashCode = prime * hashCode
                + ((getSchemaVersion() == null) ? 0 : getSchemaVersion().hashCode());
        hashCode = prime * hashCode + ((getId() == null) ? 0 : getId().hashCode());
        hashCode = prime * hashCode + ((getProductArn() == null) ? 0 : getProductArn().hashCode());
        hashCode = prime * hashCode
                + ((getGeneratorId() == null) ? 0 : getGeneratorId().hashCode());
        hashCode = prime * hashCode
                + ((getAwsAccountId() == null) ? 0 : getAwsAccountId().hashCode());
        hashCode = prime * hashCode + ((getTypes() == null) ? 0 : getTypes().hashCode());
        hashCode = prime * hashCode
                + ((getFirstObservedAt() == null) ? 0 : getFirstObservedAt().hashCode());
        hashCode = prime * hashCode
                + ((getLastObservedAt() == null) ? 0 : getLastObservedAt().hashCode());
        hashCode = prime * hashCode + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        hashCode = prime * hashCode + ((getUpdatedAt() == null) ? 0 : getUpdatedAt().hashCode());
        hashCode = prime * hashCode + ((getSeverity() == null) ? 0 : getSeverity().hashCode());
        hashCode = prime * hashCode + ((getConfidence() == null) ? 0 : getConfidence().hashCode());
        hashCode = prime * hashCode
                + ((getCriticality() == null) ? 0 : getCriticality().hashCode());
        hashCode = prime * hashCode + ((getTitle() == null) ? 0 : getTitle().hashCode());
        hashCode = prime * hashCode
                + ((getDescription() == null) ? 0 : getDescription().hashCode());
        hashCode = prime * hashCode
                + ((getRemediation() == null) ? 0 : getRemediation().hashCode());
        hashCode = prime * hashCode + ((getSourceUrl() == null) ? 0 : getSourceUrl().hashCode());
        hashCode = prime * hashCode
                + ((getProductFields() == null) ? 0 : getProductFields().hashCode());
        hashCode = prime * hashCode
                + ((getUserDefinedFields() == null) ? 0 : getUserDefinedFields().hashCode());
        hashCode = prime * hashCode + ((getMalware() == null) ? 0 : getMalware().hashCode());
        hashCode = prime * hashCode + ((getNetwork() == null) ? 0 : getNetwork().hashCode());
        hashCode = prime * hashCode + ((getProcess() == null) ? 0 : getProcess().hashCode());
        hashCode = prime
                * hashCode
                + ((getThreatIntelIndicators() == null) ? 0 : getThreatIntelIndicators().hashCode());
        hashCode = prime * hashCode + ((getResources() == null) ? 0 : getResources().hashCode());
        hashCode = prime * hashCode + ((getCompliance() == null) ? 0 : getCompliance().hashCode());
        hashCode = prime * hashCode
                + ((getVerificationState() == null) ? 0 : getVerificationState().hashCode());
        hashCode = prime * hashCode
                + ((getWorkflowState() == null) ? 0 : getWorkflowState().hashCode());
        hashCode = prime * hashCode + ((getWorkflow() == null) ? 0 : getWorkflow().hashCode());
        hashCode = prime * hashCode
                + ((getRecordState() == null) ? 0 : getRecordState().hashCode());
        hashCode = prime * hashCode
                + ((getRelatedFindings() == null) ? 0 : getRelatedFindings().hashCode());
        hashCode = prime * hashCode + ((getNote() == null) ? 0 : getNote().hashCode());
        return hashCode;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;

        if (obj instanceof AwsSecurityFinding == false)
            return false;
        AwsSecurityFinding other = (AwsSecurityFinding) obj;

        if (other.getSchemaVersion() == null ^ this.getSchemaVersion() == null)
            return false;
        if (other.getSchemaVersion() != null
                && other.getSchemaVersion().equals(this.getSchemaVersion()) == false)
            return false;
        if (other.getId() == null ^ this.getId() == null)
            return false;
        if (other.getId() != null && other.getId().equals(this.getId()) == false)
            return false;
        if (other.getProductArn() == null ^ this.getProductArn() == null)
            return false;
        if (other.getProductArn() != null
                && other.getProductArn().equals(this.getProductArn()) == false)
            return false;
        if (other.getGeneratorId() == null ^ this.getGeneratorId() == null)
            return false;
        if (other.getGeneratorId() != null
                && other.getGeneratorId().equals(this.getGeneratorId()) == false)
            return false;
        if (other.getAwsAccountId() == null ^ this.getAwsAccountId() == null)
            return false;
        if (other.getAwsAccountId() != null
                && other.getAwsAccountId().equals(this.getAwsAccountId()) == false)
            return false;
        if (other.getTypes() == null ^ this.getTypes() == null)
            return false;
        if (other.getTypes() != null && other.getTypes().equals(this.getTypes()) == false)
            return false;
        if (other.getFirstObservedAt() == null ^ this.getFirstObservedAt() == null)
            return false;
        if (other.getFirstObservedAt() != null
                && other.getFirstObservedAt().equals(this.getFirstObservedAt()) == false)
            return false;
        if (other.getLastObservedAt() == null ^ this.getLastObservedAt() == null)
            return false;
        if (other.getLastObservedAt() != null
                && other.getLastObservedAt().equals(this.getLastObservedAt()) == false)
            return false;
        if (other.getCreatedAt() == null ^ this.getCreatedAt() == null)
            return false;
        if (other.getCreatedAt() != null
                && other.getCreatedAt().equals(this.getCreatedAt()) == false)
            return false;
        if (other.getUpdatedAt() == null ^ this.getUpdatedAt() == null)
            return false;
        if (other.getUpdatedAt() != null
                && other.getUpdatedAt().equals(this.getUpdatedAt()) == false)
            return false;
        if (other.getSeverity() == null ^ this.getSeverity() == null)
            return false;
        if (other.getSeverity() != null && other.getSeverity().equals(this.getSeverity()) == false)
            return false;
        if (other.getConfidence() == null ^ this.getConfidence() == null)
            return false;
        if (other.getConfidence() != null
                && other.getConfidence().equals(this.getConfidence()) == false)
            return false;
        if (other.getCriticality() == null ^ this.getCriticality() == null)
            return false;
        if (other.getCriticality() != null
                && other.getCriticality().equals(this.getCriticality()) == false)
            return false;
        if (other.getTitle() == null ^ this.getTitle() == null)
            return false;
        if (other.getTitle() != null && other.getTitle().equals(this.getTitle()) == false)
            return false;
        if (other.getDescription() == null ^ this.getDescription() == null)
            return false;
        if (other.getDescription() != null
                && other.getDescription().equals(this.getDescription()) == false)
            return false;
        if (other.getRemediation() == null ^ this.getRemediation() == null)
            return false;
        if (other.getRemediation() != null
                && other.getRemediation().equals(this.getRemediation()) == false)
            return false;
        if (other.getSourceUrl() == null ^ this.getSourceUrl() == null)
            return false;
        if (other.getSourceUrl() != null
                && other.getSourceUrl().equals(this.getSourceUrl()) == false)
            return false;
        if (other.getProductFields() == null ^ this.getProductFields() == null)
            return false;
        if (other.getProductFields() != null
                && other.getProductFields().equals(this.getProductFields()) == false)
            return false;
        if (other.getUserDefinedFields() == null ^ this.getUserDefinedFields() == null)
            return false;
        if (other.getUserDefinedFields() != null
                && other.getUserDefinedFields().equals(this.getUserDefinedFields()) == false)
            return false;
        if (other.getMalware() == null ^ this.getMalware() == null)
            return false;
        if (other.getMalware() != null && other.getMalware().equals(this.getMalware()) == false)
            return false;
        if (other.getNetwork() == null ^ this.getNetwork() == null)
            return false;
        if (other.getNetwork() != null && other.getNetwork().equals(this.getNetwork()) == false)
            return false;
        if (other.getProcess() == null ^ this.getProcess() == null)
            return false;
        if (other.getProcess() != null && other.getProcess().equals(this.getProcess()) == false)
            return false;
        if (other.getThreatIntelIndicators() == null ^ this.getThreatIntelIndicators() == null)
            return false;
        if (other.getThreatIntelIndicators() != null
                && other.getThreatIntelIndicators().equals(this.getThreatIntelIndicators()) == false)
            return false;
        if (other.getResources() == null ^ this.getResources() == null)
            return false;
        if (other.getResources() != null
                && other.getResources().equals(this.getResources()) == false)
            return false;
        if (other.getCompliance() == null ^ this.getCompliance() == null)
            return false;
        if (other.getCompliance() != null
                && other.getCompliance().equals(this.getCompliance()) == false)
            return false;
        if (other.getVerificationState() == null ^ this.getVerificationState() == null)
            return false;
        if (other.getVerificationState() != null
                && other.getVerificationState().equals(this.getVerificationState()) == false)
            return false;
        if (other.getWorkflowState() == null ^ this.getWorkflowState() == null)
            return false;
        if (other.getWorkflowState() != null
                && other.getWorkflowState().equals(this.getWorkflowState()) == false)
            return false;
        if (other.getWorkflow() == null ^ this.getWorkflow() == null)
            return false;
        if (other.getWorkflow() != null && other.getWorkflow().equals(this.getWorkflow()) == false)
            return false;
        if (other.getRecordState() == null ^ this.getRecordState() == null)
            return false;
        if (other.getRecordState() != null
                && other.getRecordState().equals(this.getRecordState()) == false)
            return false;
        if (other.getRelatedFindings() == null ^ this.getRelatedFindings() == null)
            return false;
        if (other.getRelatedFindings() != null
                && other.getRelatedFindings().equals(this.getRelatedFindings()) == false)
            return false;
        if (other.getNote() == null ^ this.getNote() == null)
            return false;
        if (other.getNote() != null && other.getNote().equals(this.getNote()) == false)
            return false;
        return true;
    }
}
