/*
 * Copyright 2010-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package com.amazonaws.services.glue.model;

import java.io.Serializable;

/**
 * <p>
 * A structure for a machine learning transform.
 * </p>
 */
public class MLTransform implements Serializable {
    /**
     * <p>
     * The unique transform ID that is generated for the machine learning
     * transform. The ID is guaranteed to be unique and does not change.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>1 - 255<br/>
     * <b>Pattern: </b>[ -\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*<br/>
     */
    private String transformId;

    /**
     * <p>
     * A user-defined name for the machine learning transform. Names are not
     * guaranteed unique and can be changed at any time.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>1 - 255<br/>
     * <b>Pattern: </b>[ -\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*<br/>
     */
    private String name;

    /**
     * <p>
     * A user-defined, long-form description text for the machine learning
     * transform. Descriptions are not guaranteed to be unique and can be
     * changed at any time.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>0 - 2048<br/>
     * <b>Pattern: </b>[ -\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*
     * <br/>
     */
    private String description;

    /**
     * <p>
     * The current status of the machine learning transform.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>NOT_READY, READY, DELETING
     */
    private String status;

    /**
     * <p>
     * A timestamp. The time and date that this machine learning transform was
     * created.
     * </p>
     */
    private java.util.Date createdOn;

    /**
     * <p>
     * A timestamp. The last point in time when this machine learning transform
     * was modified.
     * </p>
     */
    private java.util.Date lastModifiedOn;

    /**
     * <p>
     * A list of AWS Glue table definitions used by the transform.
     * </p>
     */
    private java.util.List<GlueTable> inputRecordTables;

    /**
     * <p>
     * A <code>TransformParameters</code> object. You can use parameters to tune
     * (customize) the behavior of the machine learning transform by specifying
     * what data it learns from and your preference on various tradeoffs (such
     * as precious vs. recall, or accuracy vs. cost).
     * </p>
     */
    private TransformParameters parameters;

    /**
     * <p>
     * An <code>EvaluationMetrics</code> object. Evaluation metrics provide an
     * estimate of the quality of your machine learning transform.
     * </p>
     */
    private EvaluationMetrics evaluationMetrics;

    /**
     * <p>
     * A count identifier for the labeling files generated by AWS Glue for this
     * transform. As you create a better transform, you can iteratively
     * download, label, and upload the labeling file.
     * </p>
     */
    private Integer labelCount;

    /**
     * <p>
     * A map of key-value pairs representing the columns and data types that
     * this transform can run against. Has an upper bound of 100 columns.
     * </p>
     */
    private java.util.List<SchemaColumn> schema;

    /**
     * <p>
     * The name or Amazon Resource Name (ARN) of the IAM role with the required
     * permissions. The required permissions include both AWS Glue service role
     * permissions to AWS Glue resources, and Amazon S3 permissions required by
     * the transform.
     * </p>
     * <ul>
     * <li>
     * <p>
     * This role needs AWS Glue service role permissions to allow access to
     * resources in AWS Glue. See <a href=
     * "https://docs.aws.amazon.com/glue/latest/dg/attach-policy-iam-user.html"
     * >Attach a Policy to IAM Users That Access AWS Glue</a>.
     * </p>
     * </li>
     * <li>
     * <p>
     * This role needs permission to your Amazon Simple Storage Service (Amazon
     * S3) sources, targets, temporary directory, scripts, and any libraries
     * used by the task run for this transform.
     * </p>
     * </li>
     * </ul>
     */
    private String role;

    /**
     * <p>
     * This value determines which version of AWS Glue this machine learning
     * transform is compatible with. Glue 1.0 is recommended for most customers.
     * If the value is not set, the Glue compatibility defaults to Glue 0.9. For
     * more information, see <a href=
     * "https://docs.aws.amazon.com/glue/latest/dg/release-notes.html#release-notes-versions"
     * >AWS Glue Versions</a> in the developer guide.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>1 - 255<br/>
     * <b>Pattern: </b>^\w+\.\w+$<br/>
     */
    private String glueVersion;

    /**
     * <p>
     * The number of AWS Glue data processing units (DPUs) that are allocated to
     * task runs for this transform. You can allocate from 2 to 100 DPUs; the
     * default is 10. A DPU is a relative measure of processing power that
     * consists of 4 vCPUs of compute capacity and 16 GB of memory. For more
     * information, see the <a href="http://aws.amazon.com/glue/pricing/">AWS
     * Glue pricing page</a>.
     * </p>
     * <p>
     * <code>MaxCapacity</code> is a mutually exclusive option with
     * <code>NumberOfWorkers</code> and <code>WorkerType</code>.
     * </p>
     * <ul>
     * <li>
     * <p>
     * If either <code>NumberOfWorkers</code> or <code>WorkerType</code> is set,
     * then <code>MaxCapacity</code> cannot be set.
     * </p>
     * </li>
     * <li>
     * <p>
     * If <code>MaxCapacity</code> is set then neither
     * <code>NumberOfWorkers</code> or <code>WorkerType</code> can be set.
     * </p>
     * </li>
     * <li>
     * <p>
     * If <code>WorkerType</code> is set, then <code>NumberOfWorkers</code> is
     * required (and vice versa).
     * </p>
     * </li>
     * <li>
     * <p>
     * <code>MaxCapacity</code> and <code>NumberOfWorkers</code> must both be at
     * least 1.
     * </p>
     * </li>
     * </ul>
     * <p>
     * When the <code>WorkerType</code> field is set to a value other than
     * <code>Standard</code>, the <code>MaxCapacity</code> field is set
     * automatically and becomes read-only.
     * </p>
     */
    private Double maxCapacity;

    /**
     * <p>
     * The type of predefined worker that is allocated when a task of this
     * transform runs. Accepts a value of Standard, G.1X, or G.2X.
     * </p>
     * <ul>
     * <li>
     * <p>
     * For the <code>Standard</code> worker type, each worker provides 4 vCPU,
     * 16 GB of memory and a 50GB disk, and 2 executors per worker.
     * </p>
     * </li>
     * <li>
     * <p>
     * For the <code>G.1X</code> worker type, each worker provides 4 vCPU, 16 GB
     * of memory and a 64GB disk, and 1 executor per worker.
     * </p>
     * </li>
     * <li>
     * <p>
     * For the <code>G.2X</code> worker type, each worker provides 8 vCPU, 32 GB
     * of memory and a 128GB disk, and 1 executor per worker.
     * </p>
     * </li>
     * </ul>
     * <p>
     * <code>MaxCapacity</code> is a mutually exclusive option with
     * <code>NumberOfWorkers</code> and <code>WorkerType</code>.
     * </p>
     * <ul>
     * <li>
     * <p>
     * If either <code>NumberOfWorkers</code> or <code>WorkerType</code> is set,
     * then <code>MaxCapacity</code> cannot be set.
     * </p>
     * </li>
     * <li>
     * <p>
     * If <code>MaxCapacity</code> is set then neither
     * <code>NumberOfWorkers</code> or <code>WorkerType</code> can be set.
     * </p>
     * </li>
     * <li>
     * <p>
     * If <code>WorkerType</code> is set, then <code>NumberOfWorkers</code> is
     * required (and vice versa).
     * </p>
     * </li>
     * <li>
     * <p>
     * <code>MaxCapacity</code> and <code>NumberOfWorkers</code> must both be at
     * least 1.
     * </p>
     * </li>
     * </ul>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>Standard, G.1X, G.2X
     */
    private String workerType;

    /**
     * <p>
     * The number of workers of a defined <code>workerType</code> that are
     * allocated when a task of the transform runs.
     * </p>
     * <p>
     * If <code>WorkerType</code> is set, then <code>NumberOfWorkers</code> is
     * required (and vice versa).
     * </p>
     */
    private Integer numberOfWorkers;

    /**
     * <p>
     * The timeout in minutes of the machine learning transform.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Range: </b>1 - <br/>
     */
    private Integer timeout;

    /**
     * <p>
     * The maximum number of times to retry after an <code>MLTaskRun</code> of
     * the machine learning transform fails.
     * </p>
     */
    private Integer maxRetries;

    /**
     * <p>
     * The unique transform ID that is generated for the machine learning
     * transform. The ID is guaranteed to be unique and does not change.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>1 - 255<br/>
     * <b>Pattern: </b>[ -\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*<br/>
     *
     * @return <p>
     *         The unique transform ID that is generated for the machine
     *         learning transform. The ID is guaranteed to be unique and does
     *         not change.
     *         </p>
     */
    public String getTransformId() {
        return transformId;
    }

    /**
     * <p>
     * The unique transform ID that is generated for the machine learning
     * transform. The ID is guaranteed to be unique and does not change.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>1 - 255<br/>
     * <b>Pattern: </b>[ -\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*<br/>
     *
     * @param transformId <p>
     *            The unique transform ID that is generated for the machine
     *            learning transform. The ID is guaranteed to be unique and does
     *            not change.
     *            </p>
     */
    public void setTransformId(String transformId) {
        this.transformId = transformId;
    }

    /**
     * <p>
     * The unique transform ID that is generated for the machine learning
     * transform. The ID is guaranteed to be unique and does not change.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>1 - 255<br/>
     * <b>Pattern: </b>[ -\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*<br/>
     *
     * @param transformId <p>
     *            The unique transform ID that is generated for the machine
     *            learning transform. The ID is guaranteed to be unique and does
     *            not change.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public MLTransform withTransformId(String transformId) {
        this.transformId = transformId;
        return this;
    }

    /**
     * <p>
     * A user-defined name for the machine learning transform. Names are not
     * guaranteed unique and can be changed at any time.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>1 - 255<br/>
     * <b>Pattern: </b>[ -\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*<br/>
     *
     * @return <p>
     *         A user-defined name for the machine learning transform. Names are
     *         not guaranteed unique and can be changed at any time.
     *         </p>
     */
    public String getName() {
        return name;
    }

    /**
     * <p>
     * A user-defined name for the machine learning transform. Names are not
     * guaranteed unique and can be changed at any time.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>1 - 255<br/>
     * <b>Pattern: </b>[ -\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*<br/>
     *
     * @param name <p>
     *            A user-defined name for the machine learning transform. Names
     *            are not guaranteed unique and can be changed at any time.
     *            </p>
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * <p>
     * A user-defined name for the machine learning transform. Names are not
     * guaranteed unique and can be changed at any time.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>1 - 255<br/>
     * <b>Pattern: </b>[ -\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*<br/>
     *
     * @param name <p>
     *            A user-defined name for the machine learning transform. Names
     *            are not guaranteed unique and can be changed at any time.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public MLTransform withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * <p>
     * A user-defined, long-form description text for the machine learning
     * transform. Descriptions are not guaranteed to be unique and can be
     * changed at any time.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>0 - 2048<br/>
     * <b>Pattern: </b>[ -\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*
     * <br/>
     *
     * @return <p>
     *         A user-defined, long-form description text for the machine
     *         learning transform. Descriptions are not guaranteed to be unique
     *         and can be changed at any time.
     *         </p>
     */
    public String getDescription() {
        return description;
    }

    /**
     * <p>
     * A user-defined, long-form description text for the machine learning
     * transform. Descriptions are not guaranteed to be unique and can be
     * changed at any time.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>0 - 2048<br/>
     * <b>Pattern: </b>[ -\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*
     * <br/>
     *
     * @param description <p>
     *            A user-defined, long-form description text for the machine
     *            learning transform. Descriptions are not guaranteed to be
     *            unique and can be changed at any time.
     *            </p>
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * <p>
     * A user-defined, long-form description text for the machine learning
     * transform. Descriptions are not guaranteed to be unique and can be
     * changed at any time.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>0 - 2048<br/>
     * <b>Pattern: </b>[ -\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*
     * <br/>
     *
     * @param description <p>
     *            A user-defined, long-form description text for the machine
     *            learning transform. Descriptions are not guaranteed to be
     *            unique and can be changed at any time.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public MLTransform withDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * <p>
     * The current status of the machine learning transform.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>NOT_READY, READY, DELETING
     *
     * @return <p>
     *         The current status of the machine learning transform.
     *         </p>
     * @see TransformStatusType
     */
    public String getStatus() {
        return status;
    }

    /**
     * <p>
     * The current status of the machine learning transform.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>NOT_READY, READY, DELETING
     *
     * @param status <p>
     *            The current status of the machine learning transform.
     *            </p>
     * @see TransformStatusType
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * <p>
     * The current status of the machine learning transform.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>NOT_READY, READY, DELETING
     *
     * @param status <p>
     *            The current status of the machine learning transform.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     * @see TransformStatusType
     */
    public MLTransform withStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * <p>
     * The current status of the machine learning transform.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>NOT_READY, READY, DELETING
     *
     * @param status <p>
     *            The current status of the machine learning transform.
     *            </p>
     * @see TransformStatusType
     */
    public void setStatus(TransformStatusType status) {
        this.status = status.toString();
    }

    /**
     * <p>
     * The current status of the machine learning transform.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>NOT_READY, READY, DELETING
     *
     * @param status <p>
     *            The current status of the machine learning transform.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     * @see TransformStatusType
     */
    public MLTransform withStatus(TransformStatusType status) {
        this.status = status.toString();
        return this;
    }

    /**
     * <p>
     * A timestamp. The time and date that this machine learning transform was
     * created.
     * </p>
     *
     * @return <p>
     *         A timestamp. The time and date that this machine learning
     *         transform was created.
     *         </p>
     */
    public java.util.Date getCreatedOn() {
        return createdOn;
    }

    /**
     * <p>
     * A timestamp. The time and date that this machine learning transform was
     * created.
     * </p>
     *
     * @param createdOn <p>
     *            A timestamp. The time and date that this machine learning
     *            transform was created.
     *            </p>
     */
    public void setCreatedOn(java.util.Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * <p>
     * A timestamp. The time and date that this machine learning transform was
     * created.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param createdOn <p>
     *            A timestamp. The time and date that this machine learning
     *            transform was created.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public MLTransform withCreatedOn(java.util.Date createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    /**
     * <p>
     * A timestamp. The last point in time when this machine learning transform
     * was modified.
     * </p>
     *
     * @return <p>
     *         A timestamp. The last point in time when this machine learning
     *         transform was modified.
     *         </p>
     */
    public java.util.Date getLastModifiedOn() {
        return lastModifiedOn;
    }

    /**
     * <p>
     * A timestamp. The last point in time when this machine learning transform
     * was modified.
     * </p>
     *
     * @param lastModifiedOn <p>
     *            A timestamp. The last point in time when this machine learning
     *            transform was modified.
     *            </p>
     */
    public void setLastModifiedOn(java.util.Date lastModifiedOn) {
        this.lastModifiedOn = lastModifiedOn;
    }

    /**
     * <p>
     * A timestamp. The last point in time when this machine learning transform
     * was modified.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param lastModifiedOn <p>
     *            A timestamp. The last point in time when this machine learning
     *            transform was modified.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public MLTransform withLastModifiedOn(java.util.Date lastModifiedOn) {
        this.lastModifiedOn = lastModifiedOn;
        return this;
    }

    /**
     * <p>
     * A list of AWS Glue table definitions used by the transform.
     * </p>
     *
     * @return <p>
     *         A list of AWS Glue table definitions used by the transform.
     *         </p>
     */
    public java.util.List<GlueTable> getInputRecordTables() {
        return inputRecordTables;
    }

    /**
     * <p>
     * A list of AWS Glue table definitions used by the transform.
     * </p>
     *
     * @param inputRecordTables <p>
     *            A list of AWS Glue table definitions used by the transform.
     *            </p>
     */
    public void setInputRecordTables(java.util.Collection<GlueTable> inputRecordTables) {
        if (inputRecordTables == null) {
            this.inputRecordTables = null;
            return;
        }

        this.inputRecordTables = new java.util.ArrayList<GlueTable>(inputRecordTables);
    }

    /**
     * <p>
     * A list of AWS Glue table definitions used by the transform.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param inputRecordTables <p>
     *            A list of AWS Glue table definitions used by the transform.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public MLTransform withInputRecordTables(GlueTable... inputRecordTables) {
        if (getInputRecordTables() == null) {
            this.inputRecordTables = new java.util.ArrayList<GlueTable>(inputRecordTables.length);
        }
        for (GlueTable value : inputRecordTables) {
            this.inputRecordTables.add(value);
        }
        return this;
    }

    /**
     * <p>
     * A list of AWS Glue table definitions used by the transform.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param inputRecordTables <p>
     *            A list of AWS Glue table definitions used by the transform.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public MLTransform withInputRecordTables(java.util.Collection<GlueTable> inputRecordTables) {
        setInputRecordTables(inputRecordTables);
        return this;
    }

    /**
     * <p>
     * A <code>TransformParameters</code> object. You can use parameters to tune
     * (customize) the behavior of the machine learning transform by specifying
     * what data it learns from and your preference on various tradeoffs (such
     * as precious vs. recall, or accuracy vs. cost).
     * </p>
     *
     * @return <p>
     *         A <code>TransformParameters</code> object. You can use parameters
     *         to tune (customize) the behavior of the machine learning
     *         transform by specifying what data it learns from and your
     *         preference on various tradeoffs (such as precious vs. recall, or
     *         accuracy vs. cost).
     *         </p>
     */
    public TransformParameters getParameters() {
        return parameters;
    }

    /**
     * <p>
     * A <code>TransformParameters</code> object. You can use parameters to tune
     * (customize) the behavior of the machine learning transform by specifying
     * what data it learns from and your preference on various tradeoffs (such
     * as precious vs. recall, or accuracy vs. cost).
     * </p>
     *
     * @param parameters <p>
     *            A <code>TransformParameters</code> object. You can use
     *            parameters to tune (customize) the behavior of the machine
     *            learning transform by specifying what data it learns from and
     *            your preference on various tradeoffs (such as precious vs.
     *            recall, or accuracy vs. cost).
     *            </p>
     */
    public void setParameters(TransformParameters parameters) {
        this.parameters = parameters;
    }

    /**
     * <p>
     * A <code>TransformParameters</code> object. You can use parameters to tune
     * (customize) the behavior of the machine learning transform by specifying
     * what data it learns from and your preference on various tradeoffs (such
     * as precious vs. recall, or accuracy vs. cost).
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param parameters <p>
     *            A <code>TransformParameters</code> object. You can use
     *            parameters to tune (customize) the behavior of the machine
     *            learning transform by specifying what data it learns from and
     *            your preference on various tradeoffs (such as precious vs.
     *            recall, or accuracy vs. cost).
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public MLTransform withParameters(TransformParameters parameters) {
        this.parameters = parameters;
        return this;
    }

    /**
     * <p>
     * An <code>EvaluationMetrics</code> object. Evaluation metrics provide an
     * estimate of the quality of your machine learning transform.
     * </p>
     *
     * @return <p>
     *         An <code>EvaluationMetrics</code> object. Evaluation metrics
     *         provide an estimate of the quality of your machine learning
     *         transform.
     *         </p>
     */
    public EvaluationMetrics getEvaluationMetrics() {
        return evaluationMetrics;
    }

    /**
     * <p>
     * An <code>EvaluationMetrics</code> object. Evaluation metrics provide an
     * estimate of the quality of your machine learning transform.
     * </p>
     *
     * @param evaluationMetrics <p>
     *            An <code>EvaluationMetrics</code> object. Evaluation metrics
     *            provide an estimate of the quality of your machine learning
     *            transform.
     *            </p>
     */
    public void setEvaluationMetrics(EvaluationMetrics evaluationMetrics) {
        this.evaluationMetrics = evaluationMetrics;
    }

    /**
     * <p>
     * An <code>EvaluationMetrics</code> object. Evaluation metrics provide an
     * estimate of the quality of your machine learning transform.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param evaluationMetrics <p>
     *            An <code>EvaluationMetrics</code> object. Evaluation metrics
     *            provide an estimate of the quality of your machine learning
     *            transform.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public MLTransform withEvaluationMetrics(EvaluationMetrics evaluationMetrics) {
        this.evaluationMetrics = evaluationMetrics;
        return this;
    }

    /**
     * <p>
     * A count identifier for the labeling files generated by AWS Glue for this
     * transform. As you create a better transform, you can iteratively
     * download, label, and upload the labeling file.
     * </p>
     *
     * @return <p>
     *         A count identifier for the labeling files generated by AWS Glue
     *         for this transform. As you create a better transform, you can
     *         iteratively download, label, and upload the labeling file.
     *         </p>
     */
    public Integer getLabelCount() {
        return labelCount;
    }

    /**
     * <p>
     * A count identifier for the labeling files generated by AWS Glue for this
     * transform. As you create a better transform, you can iteratively
     * download, label, and upload the labeling file.
     * </p>
     *
     * @param labelCount <p>
     *            A count identifier for the labeling files generated by AWS
     *            Glue for this transform. As you create a better transform, you
     *            can iteratively download, label, and upload the labeling file.
     *            </p>
     */
    public void setLabelCount(Integer labelCount) {
        this.labelCount = labelCount;
    }

    /**
     * <p>
     * A count identifier for the labeling files generated by AWS Glue for this
     * transform. As you create a better transform, you can iteratively
     * download, label, and upload the labeling file.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param labelCount <p>
     *            A count identifier for the labeling files generated by AWS
     *            Glue for this transform. As you create a better transform, you
     *            can iteratively download, label, and upload the labeling file.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public MLTransform withLabelCount(Integer labelCount) {
        this.labelCount = labelCount;
        return this;
    }

    /**
     * <p>
     * A map of key-value pairs representing the columns and data types that
     * this transform can run against. Has an upper bound of 100 columns.
     * </p>
     *
     * @return <p>
     *         A map of key-value pairs representing the columns and data types
     *         that this transform can run against. Has an upper bound of 100
     *         columns.
     *         </p>
     */
    public java.util.List<SchemaColumn> getSchema() {
        return schema;
    }

    /**
     * <p>
     * A map of key-value pairs representing the columns and data types that
     * this transform can run against. Has an upper bound of 100 columns.
     * </p>
     *
     * @param schema <p>
     *            A map of key-value pairs representing the columns and data
     *            types that this transform can run against. Has an upper bound
     *            of 100 columns.
     *            </p>
     */
    public void setSchema(java.util.Collection<SchemaColumn> schema) {
        if (schema == null) {
            this.schema = null;
            return;
        }

        this.schema = new java.util.ArrayList<SchemaColumn>(schema);
    }

    /**
     * <p>
     * A map of key-value pairs representing the columns and data types that
     * this transform can run against. Has an upper bound of 100 columns.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param schema <p>
     *            A map of key-value pairs representing the columns and data
     *            types that this transform can run against. Has an upper bound
     *            of 100 columns.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public MLTransform withSchema(SchemaColumn... schema) {
        if (getSchema() == null) {
            this.schema = new java.util.ArrayList<SchemaColumn>(schema.length);
        }
        for (SchemaColumn value : schema) {
            this.schema.add(value);
        }
        return this;
    }

    /**
     * <p>
     * A map of key-value pairs representing the columns and data types that
     * this transform can run against. Has an upper bound of 100 columns.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param schema <p>
     *            A map of key-value pairs representing the columns and data
     *            types that this transform can run against. Has an upper bound
     *            of 100 columns.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public MLTransform withSchema(java.util.Collection<SchemaColumn> schema) {
        setSchema(schema);
        return this;
    }

    /**
     * <p>
     * The name or Amazon Resource Name (ARN) of the IAM role with the required
     * permissions. The required permissions include both AWS Glue service role
     * permissions to AWS Glue resources, and Amazon S3 permissions required by
     * the transform.
     * </p>
     * <ul>
     * <li>
     * <p>
     * This role needs AWS Glue service role permissions to allow access to
     * resources in AWS Glue. See <a href=
     * "https://docs.aws.amazon.com/glue/latest/dg/attach-policy-iam-user.html"
     * >Attach a Policy to IAM Users That Access AWS Glue</a>.
     * </p>
     * </li>
     * <li>
     * <p>
     * This role needs permission to your Amazon Simple Storage Service (Amazon
     * S3) sources, targets, temporary directory, scripts, and any libraries
     * used by the task run for this transform.
     * </p>
     * </li>
     * </ul>
     *
     * @return <p>
     *         The name or Amazon Resource Name (ARN) of the IAM role with the
     *         required permissions. The required permissions include both AWS
     *         Glue service role permissions to AWS Glue resources, and Amazon
     *         S3 permissions required by the transform.
     *         </p>
     *         <ul>
     *         <li>
     *         <p>
     *         This role needs AWS Glue service role permissions to allow access
     *         to resources in AWS Glue. See <a href=
     *         "https://docs.aws.amazon.com/glue/latest/dg/attach-policy-iam-user.html"
     *         >Attach a Policy to IAM Users That Access AWS Glue</a>.
     *         </p>
     *         </li>
     *         <li>
     *         <p>
     *         This role needs permission to your Amazon Simple Storage Service
     *         (Amazon S3) sources, targets, temporary directory, scripts, and
     *         any libraries used by the task run for this transform.
     *         </p>
     *         </li>
     *         </ul>
     */
    public String getRole() {
        return role;
    }

    /**
     * <p>
     * The name or Amazon Resource Name (ARN) of the IAM role with the required
     * permissions. The required permissions include both AWS Glue service role
     * permissions to AWS Glue resources, and Amazon S3 permissions required by
     * the transform.
     * </p>
     * <ul>
     * <li>
     * <p>
     * This role needs AWS Glue service role permissions to allow access to
     * resources in AWS Glue. See <a href=
     * "https://docs.aws.amazon.com/glue/latest/dg/attach-policy-iam-user.html"
     * >Attach a Policy to IAM Users That Access AWS Glue</a>.
     * </p>
     * </li>
     * <li>
     * <p>
     * This role needs permission to your Amazon Simple Storage Service (Amazon
     * S3) sources, targets, temporary directory, scripts, and any libraries
     * used by the task run for this transform.
     * </p>
     * </li>
     * </ul>
     *
     * @param role <p>
     *            The name or Amazon Resource Name (ARN) of the IAM role with
     *            the required permissions. The required permissions include
     *            both AWS Glue service role permissions to AWS Glue resources,
     *            and Amazon S3 permissions required by the transform.
     *            </p>
     *            <ul>
     *            <li>
     *            <p>
     *            This role needs AWS Glue service role permissions to allow
     *            access to resources in AWS Glue. See <a href=
     *            "https://docs.aws.amazon.com/glue/latest/dg/attach-policy-iam-user.html"
     *            >Attach a Policy to IAM Users That Access AWS Glue</a>.
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            This role needs permission to your Amazon Simple Storage
     *            Service (Amazon S3) sources, targets, temporary directory,
     *            scripts, and any libraries used by the task run for this
     *            transform.
     *            </p>
     *            </li>
     *            </ul>
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * <p>
     * The name or Amazon Resource Name (ARN) of the IAM role with the required
     * permissions. The required permissions include both AWS Glue service role
     * permissions to AWS Glue resources, and Amazon S3 permissions required by
     * the transform.
     * </p>
     * <ul>
     * <li>
     * <p>
     * This role needs AWS Glue service role permissions to allow access to
     * resources in AWS Glue. See <a href=
     * "https://docs.aws.amazon.com/glue/latest/dg/attach-policy-iam-user.html"
     * >Attach a Policy to IAM Users That Access AWS Glue</a>.
     * </p>
     * </li>
     * <li>
     * <p>
     * This role needs permission to your Amazon Simple Storage Service (Amazon
     * S3) sources, targets, temporary directory, scripts, and any libraries
     * used by the task run for this transform.
     * </p>
     * </li>
     * </ul>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param role <p>
     *            The name or Amazon Resource Name (ARN) of the IAM role with
     *            the required permissions. The required permissions include
     *            both AWS Glue service role permissions to AWS Glue resources,
     *            and Amazon S3 permissions required by the transform.
     *            </p>
     *            <ul>
     *            <li>
     *            <p>
     *            This role needs AWS Glue service role permissions to allow
     *            access to resources in AWS Glue. See <a href=
     *            "https://docs.aws.amazon.com/glue/latest/dg/attach-policy-iam-user.html"
     *            >Attach a Policy to IAM Users That Access AWS Glue</a>.
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            This role needs permission to your Amazon Simple Storage
     *            Service (Amazon S3) sources, targets, temporary directory,
     *            scripts, and any libraries used by the task run for this
     *            transform.
     *            </p>
     *            </li>
     *            </ul>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public MLTransform withRole(String role) {
        this.role = role;
        return this;
    }

    /**
     * <p>
     * This value determines which version of AWS Glue this machine learning
     * transform is compatible with. Glue 1.0 is recommended for most customers.
     * If the value is not set, the Glue compatibility defaults to Glue 0.9. For
     * more information, see <a href=
     * "https://docs.aws.amazon.com/glue/latest/dg/release-notes.html#release-notes-versions"
     * >AWS Glue Versions</a> in the developer guide.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>1 - 255<br/>
     * <b>Pattern: </b>^\w+\.\w+$<br/>
     *
     * @return <p>
     *         This value determines which version of AWS Glue this machine
     *         learning transform is compatible with. Glue 1.0 is recommended
     *         for most customers. If the value is not set, the Glue
     *         compatibility defaults to Glue 0.9. For more information, see <a
     *         href=
     *         "https://docs.aws.amazon.com/glue/latest/dg/release-notes.html#release-notes-versions"
     *         >AWS Glue Versions</a> in the developer guide.
     *         </p>
     */
    public String getGlueVersion() {
        return glueVersion;
    }

    /**
     * <p>
     * This value determines which version of AWS Glue this machine learning
     * transform is compatible with. Glue 1.0 is recommended for most customers.
     * If the value is not set, the Glue compatibility defaults to Glue 0.9. For
     * more information, see <a href=
     * "https://docs.aws.amazon.com/glue/latest/dg/release-notes.html#release-notes-versions"
     * >AWS Glue Versions</a> in the developer guide.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>1 - 255<br/>
     * <b>Pattern: </b>^\w+\.\w+$<br/>
     *
     * @param glueVersion <p>
     *            This value determines which version of AWS Glue this machine
     *            learning transform is compatible with. Glue 1.0 is recommended
     *            for most customers. If the value is not set, the Glue
     *            compatibility defaults to Glue 0.9. For more information, see
     *            <a href=
     *            "https://docs.aws.amazon.com/glue/latest/dg/release-notes.html#release-notes-versions"
     *            >AWS Glue Versions</a> in the developer guide.
     *            </p>
     */
    public void setGlueVersion(String glueVersion) {
        this.glueVersion = glueVersion;
    }

    /**
     * <p>
     * This value determines which version of AWS Glue this machine learning
     * transform is compatible with. Glue 1.0 is recommended for most customers.
     * If the value is not set, the Glue compatibility defaults to Glue 0.9. For
     * more information, see <a href=
     * "https://docs.aws.amazon.com/glue/latest/dg/release-notes.html#release-notes-versions"
     * >AWS Glue Versions</a> in the developer guide.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>1 - 255<br/>
     * <b>Pattern: </b>^\w+\.\w+$<br/>
     *
     * @param glueVersion <p>
     *            This value determines which version of AWS Glue this machine
     *            learning transform is compatible with. Glue 1.0 is recommended
     *            for most customers. If the value is not set, the Glue
     *            compatibility defaults to Glue 0.9. For more information, see
     *            <a href=
     *            "https://docs.aws.amazon.com/glue/latest/dg/release-notes.html#release-notes-versions"
     *            >AWS Glue Versions</a> in the developer guide.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public MLTransform withGlueVersion(String glueVersion) {
        this.glueVersion = glueVersion;
        return this;
    }

    /**
     * <p>
     * The number of AWS Glue data processing units (DPUs) that are allocated to
     * task runs for this transform. You can allocate from 2 to 100 DPUs; the
     * default is 10. A DPU is a relative measure of processing power that
     * consists of 4 vCPUs of compute capacity and 16 GB of memory. For more
     * information, see the <a href="http://aws.amazon.com/glue/pricing/">AWS
     * Glue pricing page</a>.
     * </p>
     * <p>
     * <code>MaxCapacity</code> is a mutually exclusive option with
     * <code>NumberOfWorkers</code> and <code>WorkerType</code>.
     * </p>
     * <ul>
     * <li>
     * <p>
     * If either <code>NumberOfWorkers</code> or <code>WorkerType</code> is set,
     * then <code>MaxCapacity</code> cannot be set.
     * </p>
     * </li>
     * <li>
     * <p>
     * If <code>MaxCapacity</code> is set then neither
     * <code>NumberOfWorkers</code> or <code>WorkerType</code> can be set.
     * </p>
     * </li>
     * <li>
     * <p>
     * If <code>WorkerType</code> is set, then <code>NumberOfWorkers</code> is
     * required (and vice versa).
     * </p>
     * </li>
     * <li>
     * <p>
     * <code>MaxCapacity</code> and <code>NumberOfWorkers</code> must both be at
     * least 1.
     * </p>
     * </li>
     * </ul>
     * <p>
     * When the <code>WorkerType</code> field is set to a value other than
     * <code>Standard</code>, the <code>MaxCapacity</code> field is set
     * automatically and becomes read-only.
     * </p>
     *
     * @return <p>
     *         The number of AWS Glue data processing units (DPUs) that are
     *         allocated to task runs for this transform. You can allocate from
     *         2 to 100 DPUs; the default is 10. A DPU is a relative measure of
     *         processing power that consists of 4 vCPUs of compute capacity and
     *         16 GB of memory. For more information, see the <a
     *         href="http://aws.amazon.com/glue/pricing/">AWS Glue pricing
     *         page</a>.
     *         </p>
     *         <p>
     *         <code>MaxCapacity</code> is a mutually exclusive option with
     *         <code>NumberOfWorkers</code> and <code>WorkerType</code>.
     *         </p>
     *         <ul>
     *         <li>
     *         <p>
     *         If either <code>NumberOfWorkers</code> or <code>WorkerType</code>
     *         is set, then <code>MaxCapacity</code> cannot be set.
     *         </p>
     *         </li>
     *         <li>
     *         <p>
     *         If <code>MaxCapacity</code> is set then neither
     *         <code>NumberOfWorkers</code> or <code>WorkerType</code> can be
     *         set.
     *         </p>
     *         </li>
     *         <li>
     *         <p>
     *         If <code>WorkerType</code> is set, then
     *         <code>NumberOfWorkers</code> is required (and vice versa).
     *         </p>
     *         </li>
     *         <li>
     *         <p>
     *         <code>MaxCapacity</code> and <code>NumberOfWorkers</code> must
     *         both be at least 1.
     *         </p>
     *         </li>
     *         </ul>
     *         <p>
     *         When the <code>WorkerType</code> field is set to a value other
     *         than <code>Standard</code>, the <code>MaxCapacity</code> field is
     *         set automatically and becomes read-only.
     *         </p>
     */
    public Double getMaxCapacity() {
        return maxCapacity;
    }

    /**
     * <p>
     * The number of AWS Glue data processing units (DPUs) that are allocated to
     * task runs for this transform. You can allocate from 2 to 100 DPUs; the
     * default is 10. A DPU is a relative measure of processing power that
     * consists of 4 vCPUs of compute capacity and 16 GB of memory. For more
     * information, see the <a href="http://aws.amazon.com/glue/pricing/">AWS
     * Glue pricing page</a>.
     * </p>
     * <p>
     * <code>MaxCapacity</code> is a mutually exclusive option with
     * <code>NumberOfWorkers</code> and <code>WorkerType</code>.
     * </p>
     * <ul>
     * <li>
     * <p>
     * If either <code>NumberOfWorkers</code> or <code>WorkerType</code> is set,
     * then <code>MaxCapacity</code> cannot be set.
     * </p>
     * </li>
     * <li>
     * <p>
     * If <code>MaxCapacity</code> is set then neither
     * <code>NumberOfWorkers</code> or <code>WorkerType</code> can be set.
     * </p>
     * </li>
     * <li>
     * <p>
     * If <code>WorkerType</code> is set, then <code>NumberOfWorkers</code> is
     * required (and vice versa).
     * </p>
     * </li>
     * <li>
     * <p>
     * <code>MaxCapacity</code> and <code>NumberOfWorkers</code> must both be at
     * least 1.
     * </p>
     * </li>
     * </ul>
     * <p>
     * When the <code>WorkerType</code> field is set to a value other than
     * <code>Standard</code>, the <code>MaxCapacity</code> field is set
     * automatically and becomes read-only.
     * </p>
     *
     * @param maxCapacity <p>
     *            The number of AWS Glue data processing units (DPUs) that are
     *            allocated to task runs for this transform. You can allocate
     *            from 2 to 100 DPUs; the default is 10. A DPU is a relative
     *            measure of processing power that consists of 4 vCPUs of
     *            compute capacity and 16 GB of memory. For more information,
     *            see the <a href="http://aws.amazon.com/glue/pricing/">AWS Glue
     *            pricing page</a>.
     *            </p>
     *            <p>
     *            <code>MaxCapacity</code> is a mutually exclusive option with
     *            <code>NumberOfWorkers</code> and <code>WorkerType</code>.
     *            </p>
     *            <ul>
     *            <li>
     *            <p>
     *            If either <code>NumberOfWorkers</code> or
     *            <code>WorkerType</code> is set, then <code>MaxCapacity</code>
     *            cannot be set.
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            If <code>MaxCapacity</code> is set then neither
     *            <code>NumberOfWorkers</code> or <code>WorkerType</code> can be
     *            set.
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            If <code>WorkerType</code> is set, then
     *            <code>NumberOfWorkers</code> is required (and vice versa).
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            <code>MaxCapacity</code> and <code>NumberOfWorkers</code> must
     *            both be at least 1.
     *            </p>
     *            </li>
     *            </ul>
     *            <p>
     *            When the <code>WorkerType</code> field is set to a value other
     *            than <code>Standard</code>, the <code>MaxCapacity</code> field
     *            is set automatically and becomes read-only.
     *            </p>
     */
    public void setMaxCapacity(Double maxCapacity) {
        this.maxCapacity = maxCapacity;
    }

    /**
     * <p>
     * The number of AWS Glue data processing units (DPUs) that are allocated to
     * task runs for this transform. You can allocate from 2 to 100 DPUs; the
     * default is 10. A DPU is a relative measure of processing power that
     * consists of 4 vCPUs of compute capacity and 16 GB of memory. For more
     * information, see the <a href="http://aws.amazon.com/glue/pricing/">AWS
     * Glue pricing page</a>.
     * </p>
     * <p>
     * <code>MaxCapacity</code> is a mutually exclusive option with
     * <code>NumberOfWorkers</code> and <code>WorkerType</code>.
     * </p>
     * <ul>
     * <li>
     * <p>
     * If either <code>NumberOfWorkers</code> or <code>WorkerType</code> is set,
     * then <code>MaxCapacity</code> cannot be set.
     * </p>
     * </li>
     * <li>
     * <p>
     * If <code>MaxCapacity</code> is set then neither
     * <code>NumberOfWorkers</code> or <code>WorkerType</code> can be set.
     * </p>
     * </li>
     * <li>
     * <p>
     * If <code>WorkerType</code> is set, then <code>NumberOfWorkers</code> is
     * required (and vice versa).
     * </p>
     * </li>
     * <li>
     * <p>
     * <code>MaxCapacity</code> and <code>NumberOfWorkers</code> must both be at
     * least 1.
     * </p>
     * </li>
     * </ul>
     * <p>
     * When the <code>WorkerType</code> field is set to a value other than
     * <code>Standard</code>, the <code>MaxCapacity</code> field is set
     * automatically and becomes read-only.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param maxCapacity <p>
     *            The number of AWS Glue data processing units (DPUs) that are
     *            allocated to task runs for this transform. You can allocate
     *            from 2 to 100 DPUs; the default is 10. A DPU is a relative
     *            measure of processing power that consists of 4 vCPUs of
     *            compute capacity and 16 GB of memory. For more information,
     *            see the <a href="http://aws.amazon.com/glue/pricing/">AWS Glue
     *            pricing page</a>.
     *            </p>
     *            <p>
     *            <code>MaxCapacity</code> is a mutually exclusive option with
     *            <code>NumberOfWorkers</code> and <code>WorkerType</code>.
     *            </p>
     *            <ul>
     *            <li>
     *            <p>
     *            If either <code>NumberOfWorkers</code> or
     *            <code>WorkerType</code> is set, then <code>MaxCapacity</code>
     *            cannot be set.
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            If <code>MaxCapacity</code> is set then neither
     *            <code>NumberOfWorkers</code> or <code>WorkerType</code> can be
     *            set.
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            If <code>WorkerType</code> is set, then
     *            <code>NumberOfWorkers</code> is required (and vice versa).
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            <code>MaxCapacity</code> and <code>NumberOfWorkers</code> must
     *            both be at least 1.
     *            </p>
     *            </li>
     *            </ul>
     *            <p>
     *            When the <code>WorkerType</code> field is set to a value other
     *            than <code>Standard</code>, the <code>MaxCapacity</code> field
     *            is set automatically and becomes read-only.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public MLTransform withMaxCapacity(Double maxCapacity) {
        this.maxCapacity = maxCapacity;
        return this;
    }

    /**
     * <p>
     * The type of predefined worker that is allocated when a task of this
     * transform runs. Accepts a value of Standard, G.1X, or G.2X.
     * </p>
     * <ul>
     * <li>
     * <p>
     * For the <code>Standard</code> worker type, each worker provides 4 vCPU,
     * 16 GB of memory and a 50GB disk, and 2 executors per worker.
     * </p>
     * </li>
     * <li>
     * <p>
     * For the <code>G.1X</code> worker type, each worker provides 4 vCPU, 16 GB
     * of memory and a 64GB disk, and 1 executor per worker.
     * </p>
     * </li>
     * <li>
     * <p>
     * For the <code>G.2X</code> worker type, each worker provides 8 vCPU, 32 GB
     * of memory and a 128GB disk, and 1 executor per worker.
     * </p>
     * </li>
     * </ul>
     * <p>
     * <code>MaxCapacity</code> is a mutually exclusive option with
     * <code>NumberOfWorkers</code> and <code>WorkerType</code>.
     * </p>
     * <ul>
     * <li>
     * <p>
     * If either <code>NumberOfWorkers</code> or <code>WorkerType</code> is set,
     * then <code>MaxCapacity</code> cannot be set.
     * </p>
     * </li>
     * <li>
     * <p>
     * If <code>MaxCapacity</code> is set then neither
     * <code>NumberOfWorkers</code> or <code>WorkerType</code> can be set.
     * </p>
     * </li>
     * <li>
     * <p>
     * If <code>WorkerType</code> is set, then <code>NumberOfWorkers</code> is
     * required (and vice versa).
     * </p>
     * </li>
     * <li>
     * <p>
     * <code>MaxCapacity</code> and <code>NumberOfWorkers</code> must both be at
     * least 1.
     * </p>
     * </li>
     * </ul>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>Standard, G.1X, G.2X
     *
     * @return <p>
     *         The type of predefined worker that is allocated when a task of
     *         this transform runs. Accepts a value of Standard, G.1X, or G.2X.
     *         </p>
     *         <ul>
     *         <li>
     *         <p>
     *         For the <code>Standard</code> worker type, each worker provides 4
     *         vCPU, 16 GB of memory and a 50GB disk, and 2 executors per
     *         worker.
     *         </p>
     *         </li>
     *         <li>
     *         <p>
     *         For the <code>G.1X</code> worker type, each worker provides 4
     *         vCPU, 16 GB of memory and a 64GB disk, and 1 executor per worker.
     *         </p>
     *         </li>
     *         <li>
     *         <p>
     *         For the <code>G.2X</code> worker type, each worker provides 8
     *         vCPU, 32 GB of memory and a 128GB disk, and 1 executor per
     *         worker.
     *         </p>
     *         </li>
     *         </ul>
     *         <p>
     *         <code>MaxCapacity</code> is a mutually exclusive option with
     *         <code>NumberOfWorkers</code> and <code>WorkerType</code>.
     *         </p>
     *         <ul>
     *         <li>
     *         <p>
     *         If either <code>NumberOfWorkers</code> or <code>WorkerType</code>
     *         is set, then <code>MaxCapacity</code> cannot be set.
     *         </p>
     *         </li>
     *         <li>
     *         <p>
     *         If <code>MaxCapacity</code> is set then neither
     *         <code>NumberOfWorkers</code> or <code>WorkerType</code> can be
     *         set.
     *         </p>
     *         </li>
     *         <li>
     *         <p>
     *         If <code>WorkerType</code> is set, then
     *         <code>NumberOfWorkers</code> is required (and vice versa).
     *         </p>
     *         </li>
     *         <li>
     *         <p>
     *         <code>MaxCapacity</code> and <code>NumberOfWorkers</code> must
     *         both be at least 1.
     *         </p>
     *         </li>
     *         </ul>
     * @see WorkerType
     */
    public String getWorkerType() {
        return workerType;
    }

    /**
     * <p>
     * The type of predefined worker that is allocated when a task of this
     * transform runs. Accepts a value of Standard, G.1X, or G.2X.
     * </p>
     * <ul>
     * <li>
     * <p>
     * For the <code>Standard</code> worker type, each worker provides 4 vCPU,
     * 16 GB of memory and a 50GB disk, and 2 executors per worker.
     * </p>
     * </li>
     * <li>
     * <p>
     * For the <code>G.1X</code> worker type, each worker provides 4 vCPU, 16 GB
     * of memory and a 64GB disk, and 1 executor per worker.
     * </p>
     * </li>
     * <li>
     * <p>
     * For the <code>G.2X</code> worker type, each worker provides 8 vCPU, 32 GB
     * of memory and a 128GB disk, and 1 executor per worker.
     * </p>
     * </li>
     * </ul>
     * <p>
     * <code>MaxCapacity</code> is a mutually exclusive option with
     * <code>NumberOfWorkers</code> and <code>WorkerType</code>.
     * </p>
     * <ul>
     * <li>
     * <p>
     * If either <code>NumberOfWorkers</code> or <code>WorkerType</code> is set,
     * then <code>MaxCapacity</code> cannot be set.
     * </p>
     * </li>
     * <li>
     * <p>
     * If <code>MaxCapacity</code> is set then neither
     * <code>NumberOfWorkers</code> or <code>WorkerType</code> can be set.
     * </p>
     * </li>
     * <li>
     * <p>
     * If <code>WorkerType</code> is set, then <code>NumberOfWorkers</code> is
     * required (and vice versa).
     * </p>
     * </li>
     * <li>
     * <p>
     * <code>MaxCapacity</code> and <code>NumberOfWorkers</code> must both be at
     * least 1.
     * </p>
     * </li>
     * </ul>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>Standard, G.1X, G.2X
     *
     * @param workerType <p>
     *            The type of predefined worker that is allocated when a task of
     *            this transform runs. Accepts a value of Standard, G.1X, or
     *            G.2X.
     *            </p>
     *            <ul>
     *            <li>
     *            <p>
     *            For the <code>Standard</code> worker type, each worker
     *            provides 4 vCPU, 16 GB of memory and a 50GB disk, and 2
     *            executors per worker.
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            For the <code>G.1X</code> worker type, each worker provides 4
     *            vCPU, 16 GB of memory and a 64GB disk, and 1 executor per
     *            worker.
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            For the <code>G.2X</code> worker type, each worker provides 8
     *            vCPU, 32 GB of memory and a 128GB disk, and 1 executor per
     *            worker.
     *            </p>
     *            </li>
     *            </ul>
     *            <p>
     *            <code>MaxCapacity</code> is a mutually exclusive option with
     *            <code>NumberOfWorkers</code> and <code>WorkerType</code>.
     *            </p>
     *            <ul>
     *            <li>
     *            <p>
     *            If either <code>NumberOfWorkers</code> or
     *            <code>WorkerType</code> is set, then <code>MaxCapacity</code>
     *            cannot be set.
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            If <code>MaxCapacity</code> is set then neither
     *            <code>NumberOfWorkers</code> or <code>WorkerType</code> can be
     *            set.
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            If <code>WorkerType</code> is set, then
     *            <code>NumberOfWorkers</code> is required (and vice versa).
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            <code>MaxCapacity</code> and <code>NumberOfWorkers</code> must
     *            both be at least 1.
     *            </p>
     *            </li>
     *            </ul>
     * @see WorkerType
     */
    public void setWorkerType(String workerType) {
        this.workerType = workerType;
    }

    /**
     * <p>
     * The type of predefined worker that is allocated when a task of this
     * transform runs. Accepts a value of Standard, G.1X, or G.2X.
     * </p>
     * <ul>
     * <li>
     * <p>
     * For the <code>Standard</code> worker type, each worker provides 4 vCPU,
     * 16 GB of memory and a 50GB disk, and 2 executors per worker.
     * </p>
     * </li>
     * <li>
     * <p>
     * For the <code>G.1X</code> worker type, each worker provides 4 vCPU, 16 GB
     * of memory and a 64GB disk, and 1 executor per worker.
     * </p>
     * </li>
     * <li>
     * <p>
     * For the <code>G.2X</code> worker type, each worker provides 8 vCPU, 32 GB
     * of memory and a 128GB disk, and 1 executor per worker.
     * </p>
     * </li>
     * </ul>
     * <p>
     * <code>MaxCapacity</code> is a mutually exclusive option with
     * <code>NumberOfWorkers</code> and <code>WorkerType</code>.
     * </p>
     * <ul>
     * <li>
     * <p>
     * If either <code>NumberOfWorkers</code> or <code>WorkerType</code> is set,
     * then <code>MaxCapacity</code> cannot be set.
     * </p>
     * </li>
     * <li>
     * <p>
     * If <code>MaxCapacity</code> is set then neither
     * <code>NumberOfWorkers</code> or <code>WorkerType</code> can be set.
     * </p>
     * </li>
     * <li>
     * <p>
     * If <code>WorkerType</code> is set, then <code>NumberOfWorkers</code> is
     * required (and vice versa).
     * </p>
     * </li>
     * <li>
     * <p>
     * <code>MaxCapacity</code> and <code>NumberOfWorkers</code> must both be at
     * least 1.
     * </p>
     * </li>
     * </ul>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>Standard, G.1X, G.2X
     *
     * @param workerType <p>
     *            The type of predefined worker that is allocated when a task of
     *            this transform runs. Accepts a value of Standard, G.1X, or
     *            G.2X.
     *            </p>
     *            <ul>
     *            <li>
     *            <p>
     *            For the <code>Standard</code> worker type, each worker
     *            provides 4 vCPU, 16 GB of memory and a 50GB disk, and 2
     *            executors per worker.
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            For the <code>G.1X</code> worker type, each worker provides 4
     *            vCPU, 16 GB of memory and a 64GB disk, and 1 executor per
     *            worker.
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            For the <code>G.2X</code> worker type, each worker provides 8
     *            vCPU, 32 GB of memory and a 128GB disk, and 1 executor per
     *            worker.
     *            </p>
     *            </li>
     *            </ul>
     *            <p>
     *            <code>MaxCapacity</code> is a mutually exclusive option with
     *            <code>NumberOfWorkers</code> and <code>WorkerType</code>.
     *            </p>
     *            <ul>
     *            <li>
     *            <p>
     *            If either <code>NumberOfWorkers</code> or
     *            <code>WorkerType</code> is set, then <code>MaxCapacity</code>
     *            cannot be set.
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            If <code>MaxCapacity</code> is set then neither
     *            <code>NumberOfWorkers</code> or <code>WorkerType</code> can be
     *            set.
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            If <code>WorkerType</code> is set, then
     *            <code>NumberOfWorkers</code> is required (and vice versa).
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            <code>MaxCapacity</code> and <code>NumberOfWorkers</code> must
     *            both be at least 1.
     *            </p>
     *            </li>
     *            </ul>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     * @see WorkerType
     */
    public MLTransform withWorkerType(String workerType) {
        this.workerType = workerType;
        return this;
    }

    /**
     * <p>
     * The type of predefined worker that is allocated when a task of this
     * transform runs. Accepts a value of Standard, G.1X, or G.2X.
     * </p>
     * <ul>
     * <li>
     * <p>
     * For the <code>Standard</code> worker type, each worker provides 4 vCPU,
     * 16 GB of memory and a 50GB disk, and 2 executors per worker.
     * </p>
     * </li>
     * <li>
     * <p>
     * For the <code>G.1X</code> worker type, each worker provides 4 vCPU, 16 GB
     * of memory and a 64GB disk, and 1 executor per worker.
     * </p>
     * </li>
     * <li>
     * <p>
     * For the <code>G.2X</code> worker type, each worker provides 8 vCPU, 32 GB
     * of memory and a 128GB disk, and 1 executor per worker.
     * </p>
     * </li>
     * </ul>
     * <p>
     * <code>MaxCapacity</code> is a mutually exclusive option with
     * <code>NumberOfWorkers</code> and <code>WorkerType</code>.
     * </p>
     * <ul>
     * <li>
     * <p>
     * If either <code>NumberOfWorkers</code> or <code>WorkerType</code> is set,
     * then <code>MaxCapacity</code> cannot be set.
     * </p>
     * </li>
     * <li>
     * <p>
     * If <code>MaxCapacity</code> is set then neither
     * <code>NumberOfWorkers</code> or <code>WorkerType</code> can be set.
     * </p>
     * </li>
     * <li>
     * <p>
     * If <code>WorkerType</code> is set, then <code>NumberOfWorkers</code> is
     * required (and vice versa).
     * </p>
     * </li>
     * <li>
     * <p>
     * <code>MaxCapacity</code> and <code>NumberOfWorkers</code> must both be at
     * least 1.
     * </p>
     * </li>
     * </ul>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>Standard, G.1X, G.2X
     *
     * @param workerType <p>
     *            The type of predefined worker that is allocated when a task of
     *            this transform runs. Accepts a value of Standard, G.1X, or
     *            G.2X.
     *            </p>
     *            <ul>
     *            <li>
     *            <p>
     *            For the <code>Standard</code> worker type, each worker
     *            provides 4 vCPU, 16 GB of memory and a 50GB disk, and 2
     *            executors per worker.
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            For the <code>G.1X</code> worker type, each worker provides 4
     *            vCPU, 16 GB of memory and a 64GB disk, and 1 executor per
     *            worker.
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            For the <code>G.2X</code> worker type, each worker provides 8
     *            vCPU, 32 GB of memory and a 128GB disk, and 1 executor per
     *            worker.
     *            </p>
     *            </li>
     *            </ul>
     *            <p>
     *            <code>MaxCapacity</code> is a mutually exclusive option with
     *            <code>NumberOfWorkers</code> and <code>WorkerType</code>.
     *            </p>
     *            <ul>
     *            <li>
     *            <p>
     *            If either <code>NumberOfWorkers</code> or
     *            <code>WorkerType</code> is set, then <code>MaxCapacity</code>
     *            cannot be set.
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            If <code>MaxCapacity</code> is set then neither
     *            <code>NumberOfWorkers</code> or <code>WorkerType</code> can be
     *            set.
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            If <code>WorkerType</code> is set, then
     *            <code>NumberOfWorkers</code> is required (and vice versa).
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            <code>MaxCapacity</code> and <code>NumberOfWorkers</code> must
     *            both be at least 1.
     *            </p>
     *            </li>
     *            </ul>
     * @see WorkerType
     */
    public void setWorkerType(WorkerType workerType) {
        this.workerType = workerType.toString();
    }

    /**
     * <p>
     * The type of predefined worker that is allocated when a task of this
     * transform runs. Accepts a value of Standard, G.1X, or G.2X.
     * </p>
     * <ul>
     * <li>
     * <p>
     * For the <code>Standard</code> worker type, each worker provides 4 vCPU,
     * 16 GB of memory and a 50GB disk, and 2 executors per worker.
     * </p>
     * </li>
     * <li>
     * <p>
     * For the <code>G.1X</code> worker type, each worker provides 4 vCPU, 16 GB
     * of memory and a 64GB disk, and 1 executor per worker.
     * </p>
     * </li>
     * <li>
     * <p>
     * For the <code>G.2X</code> worker type, each worker provides 8 vCPU, 32 GB
     * of memory and a 128GB disk, and 1 executor per worker.
     * </p>
     * </li>
     * </ul>
     * <p>
     * <code>MaxCapacity</code> is a mutually exclusive option with
     * <code>NumberOfWorkers</code> and <code>WorkerType</code>.
     * </p>
     * <ul>
     * <li>
     * <p>
     * If either <code>NumberOfWorkers</code> or <code>WorkerType</code> is set,
     * then <code>MaxCapacity</code> cannot be set.
     * </p>
     * </li>
     * <li>
     * <p>
     * If <code>MaxCapacity</code> is set then neither
     * <code>NumberOfWorkers</code> or <code>WorkerType</code> can be set.
     * </p>
     * </li>
     * <li>
     * <p>
     * If <code>WorkerType</code> is set, then <code>NumberOfWorkers</code> is
     * required (and vice versa).
     * </p>
     * </li>
     * <li>
     * <p>
     * <code>MaxCapacity</code> and <code>NumberOfWorkers</code> must both be at
     * least 1.
     * </p>
     * </li>
     * </ul>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Allowed Values: </b>Standard, G.1X, G.2X
     *
     * @param workerType <p>
     *            The type of predefined worker that is allocated when a task of
     *            this transform runs. Accepts a value of Standard, G.1X, or
     *            G.2X.
     *            </p>
     *            <ul>
     *            <li>
     *            <p>
     *            For the <code>Standard</code> worker type, each worker
     *            provides 4 vCPU, 16 GB of memory and a 50GB disk, and 2
     *            executors per worker.
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            For the <code>G.1X</code> worker type, each worker provides 4
     *            vCPU, 16 GB of memory and a 64GB disk, and 1 executor per
     *            worker.
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            For the <code>G.2X</code> worker type, each worker provides 8
     *            vCPU, 32 GB of memory and a 128GB disk, and 1 executor per
     *            worker.
     *            </p>
     *            </li>
     *            </ul>
     *            <p>
     *            <code>MaxCapacity</code> is a mutually exclusive option with
     *            <code>NumberOfWorkers</code> and <code>WorkerType</code>.
     *            </p>
     *            <ul>
     *            <li>
     *            <p>
     *            If either <code>NumberOfWorkers</code> or
     *            <code>WorkerType</code> is set, then <code>MaxCapacity</code>
     *            cannot be set.
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            If <code>MaxCapacity</code> is set then neither
     *            <code>NumberOfWorkers</code> or <code>WorkerType</code> can be
     *            set.
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            If <code>WorkerType</code> is set, then
     *            <code>NumberOfWorkers</code> is required (and vice versa).
     *            </p>
     *            </li>
     *            <li>
     *            <p>
     *            <code>MaxCapacity</code> and <code>NumberOfWorkers</code> must
     *            both be at least 1.
     *            </p>
     *            </li>
     *            </ul>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     * @see WorkerType
     */
    public MLTransform withWorkerType(WorkerType workerType) {
        this.workerType = workerType.toString();
        return this;
    }

    /**
     * <p>
     * The number of workers of a defined <code>workerType</code> that are
     * allocated when a task of the transform runs.
     * </p>
     * <p>
     * If <code>WorkerType</code> is set, then <code>NumberOfWorkers</code> is
     * required (and vice versa).
     * </p>
     *
     * @return <p>
     *         The number of workers of a defined <code>workerType</code> that
     *         are allocated when a task of the transform runs.
     *         </p>
     *         <p>
     *         If <code>WorkerType</code> is set, then
     *         <code>NumberOfWorkers</code> is required (and vice versa).
     *         </p>
     */
    public Integer getNumberOfWorkers() {
        return numberOfWorkers;
    }

    /**
     * <p>
     * The number of workers of a defined <code>workerType</code> that are
     * allocated when a task of the transform runs.
     * </p>
     * <p>
     * If <code>WorkerType</code> is set, then <code>NumberOfWorkers</code> is
     * required (and vice versa).
     * </p>
     *
     * @param numberOfWorkers <p>
     *            The number of workers of a defined <code>workerType</code>
     *            that are allocated when a task of the transform runs.
     *            </p>
     *            <p>
     *            If <code>WorkerType</code> is set, then
     *            <code>NumberOfWorkers</code> is required (and vice versa).
     *            </p>
     */
    public void setNumberOfWorkers(Integer numberOfWorkers) {
        this.numberOfWorkers = numberOfWorkers;
    }

    /**
     * <p>
     * The number of workers of a defined <code>workerType</code> that are
     * allocated when a task of the transform runs.
     * </p>
     * <p>
     * If <code>WorkerType</code> is set, then <code>NumberOfWorkers</code> is
     * required (and vice versa).
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param numberOfWorkers <p>
     *            The number of workers of a defined <code>workerType</code>
     *            that are allocated when a task of the transform runs.
     *            </p>
     *            <p>
     *            If <code>WorkerType</code> is set, then
     *            <code>NumberOfWorkers</code> is required (and vice versa).
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public MLTransform withNumberOfWorkers(Integer numberOfWorkers) {
        this.numberOfWorkers = numberOfWorkers;
        return this;
    }

    /**
     * <p>
     * The timeout in minutes of the machine learning transform.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Range: </b>1 - <br/>
     *
     * @return <p>
     *         The timeout in minutes of the machine learning transform.
     *         </p>
     */
    public Integer getTimeout() {
        return timeout;
    }

    /**
     * <p>
     * The timeout in minutes of the machine learning transform.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Range: </b>1 - <br/>
     *
     * @param timeout <p>
     *            The timeout in minutes of the machine learning transform.
     *            </p>
     */
    public void setTimeout(Integer timeout) {
        this.timeout = timeout;
    }

    /**
     * <p>
     * The timeout in minutes of the machine learning transform.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Range: </b>1 - <br/>
     *
     * @param timeout <p>
     *            The timeout in minutes of the machine learning transform.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public MLTransform withTimeout(Integer timeout) {
        this.timeout = timeout;
        return this;
    }

    /**
     * <p>
     * The maximum number of times to retry after an <code>MLTaskRun</code> of
     * the machine learning transform fails.
     * </p>
     *
     * @return <p>
     *         The maximum number of times to retry after an
     *         <code>MLTaskRun</code> of the machine learning transform fails.
     *         </p>
     */
    public Integer getMaxRetries() {
        return maxRetries;
    }

    /**
     * <p>
     * The maximum number of times to retry after an <code>MLTaskRun</code> of
     * the machine learning transform fails.
     * </p>
     *
     * @param maxRetries <p>
     *            The maximum number of times to retry after an
     *            <code>MLTaskRun</code> of the machine learning transform
     *            fails.
     *            </p>
     */
    public void setMaxRetries(Integer maxRetries) {
        this.maxRetries = maxRetries;
    }

    /**
     * <p>
     * The maximum number of times to retry after an <code>MLTaskRun</code> of
     * the machine learning transform fails.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param maxRetries <p>
     *            The maximum number of times to retry after an
     *            <code>MLTaskRun</code> of the machine learning transform
     *            fails.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public MLTransform withMaxRetries(Integer maxRetries) {
        this.maxRetries = maxRetries;
        return this;
    }

    /**
     * Returns a string representation of this object; useful for testing and
     * debugging.
     *
     * @return A string representation of this object.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("{");
        if (getTransformId() != null)
            sb.append("TransformId: " + getTransformId() + ",");
        if (getName() != null)
            sb.append("Name: " + getName() + ",");
        if (getDescription() != null)
            sb.append("Description: " + getDescription() + ",");
        if (getStatus() != null)
            sb.append("Status: " + getStatus() + ",");
        if (getCreatedOn() != null)
            sb.append("CreatedOn: " + getCreatedOn() + ",");
        if (getLastModifiedOn() != null)
            sb.append("LastModifiedOn: " + getLastModifiedOn() + ",");
        if (getInputRecordTables() != null)
            sb.append("InputRecordTables: " + getInputRecordTables() + ",");
        if (getParameters() != null)
            sb.append("Parameters: " + getParameters() + ",");
        if (getEvaluationMetrics() != null)
            sb.append("EvaluationMetrics: " + getEvaluationMetrics() + ",");
        if (getLabelCount() != null)
            sb.append("LabelCount: " + getLabelCount() + ",");
        if (getSchema() != null)
            sb.append("Schema: " + getSchema() + ",");
        if (getRole() != null)
            sb.append("Role: " + getRole() + ",");
        if (getGlueVersion() != null)
            sb.append("GlueVersion: " + getGlueVersion() + ",");
        if (getMaxCapacity() != null)
            sb.append("MaxCapacity: " + getMaxCapacity() + ",");
        if (getWorkerType() != null)
            sb.append("WorkerType: " + getWorkerType() + ",");
        if (getNumberOfWorkers() != null)
            sb.append("NumberOfWorkers: " + getNumberOfWorkers() + ",");
        if (getTimeout() != null)
            sb.append("Timeout: " + getTimeout() + ",");
        if (getMaxRetries() != null)
            sb.append("MaxRetries: " + getMaxRetries());
        sb.append("}");
        return sb.toString();
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int hashCode = 1;

        hashCode = prime * hashCode
                + ((getTransformId() == null) ? 0 : getTransformId().hashCode());
        hashCode = prime * hashCode + ((getName() == null) ? 0 : getName().hashCode());
        hashCode = prime * hashCode
                + ((getDescription() == null) ? 0 : getDescription().hashCode());
        hashCode = prime * hashCode + ((getStatus() == null) ? 0 : getStatus().hashCode());
        hashCode = prime * hashCode + ((getCreatedOn() == null) ? 0 : getCreatedOn().hashCode());
        hashCode = prime * hashCode
                + ((getLastModifiedOn() == null) ? 0 : getLastModifiedOn().hashCode());
        hashCode = prime * hashCode
                + ((getInputRecordTables() == null) ? 0 : getInputRecordTables().hashCode());
        hashCode = prime * hashCode + ((getParameters() == null) ? 0 : getParameters().hashCode());
        hashCode = prime * hashCode
                + ((getEvaluationMetrics() == null) ? 0 : getEvaluationMetrics().hashCode());
        hashCode = prime * hashCode + ((getLabelCount() == null) ? 0 : getLabelCount().hashCode());
        hashCode = prime * hashCode + ((getSchema() == null) ? 0 : getSchema().hashCode());
        hashCode = prime * hashCode + ((getRole() == null) ? 0 : getRole().hashCode());
        hashCode = prime * hashCode
                + ((getGlueVersion() == null) ? 0 : getGlueVersion().hashCode());
        hashCode = prime * hashCode
                + ((getMaxCapacity() == null) ? 0 : getMaxCapacity().hashCode());
        hashCode = prime * hashCode + ((getWorkerType() == null) ? 0 : getWorkerType().hashCode());
        hashCode = prime * hashCode
                + ((getNumberOfWorkers() == null) ? 0 : getNumberOfWorkers().hashCode());
        hashCode = prime * hashCode + ((getTimeout() == null) ? 0 : getTimeout().hashCode());
        hashCode = prime * hashCode + ((getMaxRetries() == null) ? 0 : getMaxRetries().hashCode());
        return hashCode;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;

        if (obj instanceof MLTransform == false)
            return false;
        MLTransform other = (MLTransform) obj;

        if (other.getTransformId() == null ^ this.getTransformId() == null)
            return false;
        if (other.getTransformId() != null
                && other.getTransformId().equals(this.getTransformId()) == false)
            return false;
        if (other.getName() == null ^ this.getName() == null)
            return false;
        if (other.getName() != null && other.getName().equals(this.getName()) == false)
            return false;
        if (other.getDescription() == null ^ this.getDescription() == null)
            return false;
        if (other.getDescription() != null
                && other.getDescription().equals(this.getDescription()) == false)
            return false;
        if (other.getStatus() == null ^ this.getStatus() == null)
            return false;
        if (other.getStatus() != null && other.getStatus().equals(this.getStatus()) == false)
            return false;
        if (other.getCreatedOn() == null ^ this.getCreatedOn() == null)
            return false;
        if (other.getCreatedOn() != null
                && other.getCreatedOn().equals(this.getCreatedOn()) == false)
            return false;
        if (other.getLastModifiedOn() == null ^ this.getLastModifiedOn() == null)
            return false;
        if (other.getLastModifiedOn() != null
                && other.getLastModifiedOn().equals(this.getLastModifiedOn()) == false)
            return false;
        if (other.getInputRecordTables() == null ^ this.getInputRecordTables() == null)
            return false;
        if (other.getInputRecordTables() != null
                && other.getInputRecordTables().equals(this.getInputRecordTables()) == false)
            return false;
        if (other.getParameters() == null ^ this.getParameters() == null)
            return false;
        if (other.getParameters() != null
                && other.getParameters().equals(this.getParameters()) == false)
            return false;
        if (other.getEvaluationMetrics() == null ^ this.getEvaluationMetrics() == null)
            return false;
        if (other.getEvaluationMetrics() != null
                && other.getEvaluationMetrics().equals(this.getEvaluationMetrics()) == false)
            return false;
        if (other.getLabelCount() == null ^ this.getLabelCount() == null)
            return false;
        if (other.getLabelCount() != null
                && other.getLabelCount().equals(this.getLabelCount()) == false)
            return false;
        if (other.getSchema() == null ^ this.getSchema() == null)
            return false;
        if (other.getSchema() != null && other.getSchema().equals(this.getSchema()) == false)
            return false;
        if (other.getRole() == null ^ this.getRole() == null)
            return false;
        if (other.getRole() != null && other.getRole().equals(this.getRole()) == false)
            return false;
        if (other.getGlueVersion() == null ^ this.getGlueVersion() == null)
            return false;
        if (other.getGlueVersion() != null
                && other.getGlueVersion().equals(this.getGlueVersion()) == false)
            return false;
        if (other.getMaxCapacity() == null ^ this.getMaxCapacity() == null)
            return false;
        if (other.getMaxCapacity() != null
                && other.getMaxCapacity().equals(this.getMaxCapacity()) == false)
            return false;
        if (other.getWorkerType() == null ^ this.getWorkerType() == null)
            return false;
        if (other.getWorkerType() != null
                && other.getWorkerType().equals(this.getWorkerType()) == false)
            return false;
        if (other.getNumberOfWorkers() == null ^ this.getNumberOfWorkers() == null)
            return false;
        if (other.getNumberOfWorkers() != null
                && other.getNumberOfWorkers().equals(this.getNumberOfWorkers()) == false)
            return false;
        if (other.getTimeout() == null ^ this.getTimeout() == null)
            return false;
        if (other.getTimeout() != null && other.getTimeout().equals(this.getTimeout()) == false)
            return false;
        if (other.getMaxRetries() == null ^ this.getMaxRetries() == null)
            return false;
        if (other.getMaxRetries() != null
                && other.getMaxRetries().equals(this.getMaxRetries()) == false)
            return false;
        return true;
    }
}
