/*
 * Copyright 2010-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package com.amazonaws.services.a4b.model;

import java.io.Serializable;

import com.amazonaws.AmazonWebServiceRequest;

/**
 * <p>
 * Registers an Alexa-enabled device built by an Original Equipment Manufacturer
 * (OEM) using Alexa Voice Service (AVS).
 * </p>
 */
public class RegisterAVSDeviceRequest extends AmazonWebServiceRequest implements Serializable {
    /**
     * <p>
     * The client ID of the OEM used for code-based linking authorization on an
     * AVS device.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>^\S+{1,256}$<br/>
     */
    private String clientId;

    /**
     * <p>
     * The code that is obtained after your AVS device has made a POST request
     * to LWA as a part of the Device Authorization Request component of the
     * OAuth code-based linking specification.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>1 - 128<br/>
     */
    private String userCode;

    /**
     * <p>
     * The product ID used to identify your AVS device during authorization.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>^[a-zA-Z0-9_]{1,256}$<br/>
     */
    private String productId;

    /**
     * <p>
     * The key generated by the OEM that uniquely identifies a specified
     * instance of your AVS device.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>^[a-zA-Z0-9]{1,50}$<br/>
     */
    private String deviceSerialNumber;

    /**
     * <p>
     * The device type ID for your AVS device generated by Amazon when the OEM
     * creates a new product on Amazon's Developer Console.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>[a-zA-Z0-9]{1,18}<br/>
     */
    private String amazonId;

    /**
     * <p>
     * The client ID of the OEM used for code-based linking authorization on an
     * AVS device.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>^\S+{1,256}$<br/>
     *
     * @return <p>
     *         The client ID of the OEM used for code-based linking
     *         authorization on an AVS device.
     *         </p>
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * <p>
     * The client ID of the OEM used for code-based linking authorization on an
     * AVS device.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>^\S+{1,256}$<br/>
     *
     * @param clientId <p>
     *            The client ID of the OEM used for code-based linking
     *            authorization on an AVS device.
     *            </p>
     */
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    /**
     * <p>
     * The client ID of the OEM used for code-based linking authorization on an
     * AVS device.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>^\S+{1,256}$<br/>
     *
     * @param clientId <p>
     *            The client ID of the OEM used for code-based linking
     *            authorization on an AVS device.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public RegisterAVSDeviceRequest withClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }

    /**
     * <p>
     * The code that is obtained after your AVS device has made a POST request
     * to LWA as a part of the Device Authorization Request component of the
     * OAuth code-based linking specification.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>1 - 128<br/>
     *
     * @return <p>
     *         The code that is obtained after your AVS device has made a POST
     *         request to LWA as a part of the Device Authorization Request
     *         component of the OAuth code-based linking specification.
     *         </p>
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * <p>
     * The code that is obtained after your AVS device has made a POST request
     * to LWA as a part of the Device Authorization Request component of the
     * OAuth code-based linking specification.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>1 - 128<br/>
     *
     * @param userCode <p>
     *            The code that is obtained after your AVS device has made a
     *            POST request to LWA as a part of the Device Authorization
     *            Request component of the OAuth code-based linking
     *            specification.
     *            </p>
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * <p>
     * The code that is obtained after your AVS device has made a POST request
     * to LWA as a part of the Device Authorization Request component of the
     * OAuth code-based linking specification.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>1 - 128<br/>
     *
     * @param userCode <p>
     *            The code that is obtained after your AVS device has made a
     *            POST request to LWA as a part of the Device Authorization
     *            Request component of the OAuth code-based linking
     *            specification.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public RegisterAVSDeviceRequest withUserCode(String userCode) {
        this.userCode = userCode;
        return this;
    }

    /**
     * <p>
     * The product ID used to identify your AVS device during authorization.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>^[a-zA-Z0-9_]{1,256}$<br/>
     *
     * @return <p>
     *         The product ID used to identify your AVS device during
     *         authorization.
     *         </p>
     */
    public String getProductId() {
        return productId;
    }

    /**
     * <p>
     * The product ID used to identify your AVS device during authorization.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>^[a-zA-Z0-9_]{1,256}$<br/>
     *
     * @param productId <p>
     *            The product ID used to identify your AVS device during
     *            authorization.
     *            </p>
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * <p>
     * The product ID used to identify your AVS device during authorization.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>^[a-zA-Z0-9_]{1,256}$<br/>
     *
     * @param productId <p>
     *            The product ID used to identify your AVS device during
     *            authorization.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public RegisterAVSDeviceRequest withProductId(String productId) {
        this.productId = productId;
        return this;
    }

    /**
     * <p>
     * The key generated by the OEM that uniquely identifies a specified
     * instance of your AVS device.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>^[a-zA-Z0-9]{1,50}$<br/>
     *
     * @return <p>
     *         The key generated by the OEM that uniquely identifies a specified
     *         instance of your AVS device.
     *         </p>
     */
    public String getDeviceSerialNumber() {
        return deviceSerialNumber;
    }

    /**
     * <p>
     * The key generated by the OEM that uniquely identifies a specified
     * instance of your AVS device.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>^[a-zA-Z0-9]{1,50}$<br/>
     *
     * @param deviceSerialNumber <p>
     *            The key generated by the OEM that uniquely identifies a
     *            specified instance of your AVS device.
     *            </p>
     */
    public void setDeviceSerialNumber(String deviceSerialNumber) {
        this.deviceSerialNumber = deviceSerialNumber;
    }

    /**
     * <p>
     * The key generated by the OEM that uniquely identifies a specified
     * instance of your AVS device.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>^[a-zA-Z0-9]{1,50}$<br/>
     *
     * @param deviceSerialNumber <p>
     *            The key generated by the OEM that uniquely identifies a
     *            specified instance of your AVS device.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public RegisterAVSDeviceRequest withDeviceSerialNumber(String deviceSerialNumber) {
        this.deviceSerialNumber = deviceSerialNumber;
        return this;
    }

    /**
     * <p>
     * The device type ID for your AVS device generated by Amazon when the OEM
     * creates a new product on Amazon's Developer Console.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>[a-zA-Z0-9]{1,18}<br/>
     *
     * @return <p>
     *         The device type ID for your AVS device generated by Amazon when
     *         the OEM creates a new product on Amazon's Developer Console.
     *         </p>
     */
    public String getAmazonId() {
        return amazonId;
    }

    /**
     * <p>
     * The device type ID for your AVS device generated by Amazon when the OEM
     * creates a new product on Amazon's Developer Console.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>[a-zA-Z0-9]{1,18}<br/>
     *
     * @param amazonId <p>
     *            The device type ID for your AVS device generated by Amazon
     *            when the OEM creates a new product on Amazon's Developer
     *            Console.
     *            </p>
     */
    public void setAmazonId(String amazonId) {
        this.amazonId = amazonId;
    }

    /**
     * <p>
     * The device type ID for your AVS device generated by Amazon when the OEM
     * creates a new product on Amazon's Developer Console.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Pattern: </b>[a-zA-Z0-9]{1,18}<br/>
     *
     * @param amazonId <p>
     *            The device type ID for your AVS device generated by Amazon
     *            when the OEM creates a new product on Amazon's Developer
     *            Console.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public RegisterAVSDeviceRequest withAmazonId(String amazonId) {
        this.amazonId = amazonId;
        return this;
    }

    /**
     * Returns a string representation of this object; useful for testing and
     * debugging.
     *
     * @return A string representation of this object.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("{");
        if (getClientId() != null)
            sb.append("ClientId: " + getClientId() + ",");
        if (getUserCode() != null)
            sb.append("UserCode: " + getUserCode() + ",");
        if (getProductId() != null)
            sb.append("ProductId: " + getProductId() + ",");
        if (getDeviceSerialNumber() != null)
            sb.append("DeviceSerialNumber: " + getDeviceSerialNumber() + ",");
        if (getAmazonId() != null)
            sb.append("AmazonId: " + getAmazonId());
        sb.append("}");
        return sb.toString();
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int hashCode = 1;

        hashCode = prime * hashCode + ((getClientId() == null) ? 0 : getClientId().hashCode());
        hashCode = prime * hashCode + ((getUserCode() == null) ? 0 : getUserCode().hashCode());
        hashCode = prime * hashCode + ((getProductId() == null) ? 0 : getProductId().hashCode());
        hashCode = prime * hashCode
                + ((getDeviceSerialNumber() == null) ? 0 : getDeviceSerialNumber().hashCode());
        hashCode = prime * hashCode + ((getAmazonId() == null) ? 0 : getAmazonId().hashCode());
        return hashCode;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;

        if (obj instanceof RegisterAVSDeviceRequest == false)
            return false;
        RegisterAVSDeviceRequest other = (RegisterAVSDeviceRequest) obj;

        if (other.getClientId() == null ^ this.getClientId() == null)
            return false;
        if (other.getClientId() != null && other.getClientId().equals(this.getClientId()) == false)
            return false;
        if (other.getUserCode() == null ^ this.getUserCode() == null)
            return false;
        if (other.getUserCode() != null && other.getUserCode().equals(this.getUserCode()) == false)
            return false;
        if (other.getProductId() == null ^ this.getProductId() == null)
            return false;
        if (other.getProductId() != null
                && other.getProductId().equals(this.getProductId()) == false)
            return false;
        if (other.getDeviceSerialNumber() == null ^ this.getDeviceSerialNumber() == null)
            return false;
        if (other.getDeviceSerialNumber() != null
                && other.getDeviceSerialNumber().equals(this.getDeviceSerialNumber()) == false)
            return false;
        if (other.getAmazonId() == null ^ this.getAmazonId() == null)
            return false;
        if (other.getAmazonId() != null && other.getAmazonId().equals(this.getAmazonId()) == false)
            return false;
        return true;
    }
}
