/*
 * Copyright 2010-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package com.amazonaws.services.logs.model;

import java.io.Serializable;

/**
 * <p>
 * Contains one field from one log event returned by a CloudWatch Logs Insights
 * query, along with the value of that field.
 * </p>
 * <p>
 * For more information about the fields that are generated by CloudWatch logs,
 * see <a href=
 * "https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_AnalyzeLogData-discoverable-fields.html"
 * >Supported Logs and Discovered Fields</a>.
 * </p>
 */
public class ResultField implements Serializable {
    /**
     * <p>
     * The log event field.
     * </p>
     */
    private String field;

    /**
     * <p>
     * The value of this field.
     * </p>
     */
    private String value;

    /**
     * <p>
     * The log event field.
     * </p>
     *
     * @return <p>
     *         The log event field.
     *         </p>
     */
    public String getField() {
        return field;
    }

    /**
     * <p>
     * The log event field.
     * </p>
     *
     * @param field <p>
     *            The log event field.
     *            </p>
     */
    public void setField(String field) {
        this.field = field;
    }

    /**
     * <p>
     * The log event field.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param field <p>
     *            The log event field.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public ResultField withField(String field) {
        this.field = field;
        return this;
    }

    /**
     * <p>
     * The value of this field.
     * </p>
     *
     * @return <p>
     *         The value of this field.
     *         </p>
     */
    public String getValue() {
        return value;
    }

    /**
     * <p>
     * The value of this field.
     * </p>
     *
     * @param value <p>
     *            The value of this field.
     *            </p>
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * <p>
     * The value of this field.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param value <p>
     *            The value of this field.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public ResultField withValue(String value) {
        this.value = value;
        return this;
    }

    /**
     * Returns a string representation of this object; useful for testing and
     * debugging.
     *
     * @return A string representation of this object.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("{");
        if (getField() != null)
            sb.append("field: " + getField() + ",");
        if (getValue() != null)
            sb.append("value: " + getValue());
        sb.append("}");
        return sb.toString();
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int hashCode = 1;

        hashCode = prime * hashCode + ((getField() == null) ? 0 : getField().hashCode());
        hashCode = prime * hashCode + ((getValue() == null) ? 0 : getValue().hashCode());
        return hashCode;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;

        if (obj instanceof ResultField == false)
            return false;
        ResultField other = (ResultField) obj;

        if (other.getField() == null ^ this.getField() == null)
            return false;
        if (other.getField() != null && other.getField().equals(this.getField()) == false)
            return false;
        if (other.getValue() == null ^ this.getValue() == null)
            return false;
        if (other.getValue() != null && other.getValue().equals(this.getValue()) == false)
            return false;
        return true;
    }
}
