/*
 * Copyright 2010-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package com.amazonaws.services.athena.model;

import java.io.Serializable;

public class GetQueryResultsResult implements Serializable {
    /**
     * <p>
     * The number of rows inserted with a CREATE TABLE AS SELECT statement.
     * </p>
     */
    private Long updateCount;

    /**
     * <p>
     * The results of the query execution.
     * </p>
     */
    private ResultSet resultSet;

    /**
     * <p>
     * A token generated by the Athena service that specifies where to continue
     * pagination if a previous request was truncated. To obtain the next set of
     * pages, pass in the <code>NextToken</code> from the response object of the
     * previous page call.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>1 - 1024<br/>
     */
    private String nextToken;

    /**
     * <p>
     * The number of rows inserted with a CREATE TABLE AS SELECT statement.
     * </p>
     *
     * @return <p>
     *         The number of rows inserted with a CREATE TABLE AS SELECT
     *         statement.
     *         </p>
     */
    public Long getUpdateCount() {
        return updateCount;
    }

    /**
     * <p>
     * The number of rows inserted with a CREATE TABLE AS SELECT statement.
     * </p>
     *
     * @param updateCount <p>
     *            The number of rows inserted with a CREATE TABLE AS SELECT
     *            statement.
     *            </p>
     */
    public void setUpdateCount(Long updateCount) {
        this.updateCount = updateCount;
    }

    /**
     * <p>
     * The number of rows inserted with a CREATE TABLE AS SELECT statement.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param updateCount <p>
     *            The number of rows inserted with a CREATE TABLE AS SELECT
     *            statement.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public GetQueryResultsResult withUpdateCount(Long updateCount) {
        this.updateCount = updateCount;
        return this;
    }

    /**
     * <p>
     * The results of the query execution.
     * </p>
     *
     * @return <p>
     *         The results of the query execution.
     *         </p>
     */
    public ResultSet getResultSet() {
        return resultSet;
    }

    /**
     * <p>
     * The results of the query execution.
     * </p>
     *
     * @param resultSet <p>
     *            The results of the query execution.
     *            </p>
     */
    public void setResultSet(ResultSet resultSet) {
        this.resultSet = resultSet;
    }

    /**
     * <p>
     * The results of the query execution.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param resultSet <p>
     *            The results of the query execution.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public GetQueryResultsResult withResultSet(ResultSet resultSet) {
        this.resultSet = resultSet;
        return this;
    }

    /**
     * <p>
     * A token generated by the Athena service that specifies where to continue
     * pagination if a previous request was truncated. To obtain the next set of
     * pages, pass in the <code>NextToken</code> from the response object of the
     * previous page call.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>1 - 1024<br/>
     *
     * @return <p>
     *         A token generated by the Athena service that specifies where to
     *         continue pagination if a previous request was truncated. To
     *         obtain the next set of pages, pass in the <code>NextToken</code>
     *         from the response object of the previous page call.
     *         </p>
     */
    public String getNextToken() {
        return nextToken;
    }

    /**
     * <p>
     * A token generated by the Athena service that specifies where to continue
     * pagination if a previous request was truncated. To obtain the next set of
     * pages, pass in the <code>NextToken</code> from the response object of the
     * previous page call.
     * </p>
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>1 - 1024<br/>
     *
     * @param nextToken <p>
     *            A token generated by the Athena service that specifies where
     *            to continue pagination if a previous request was truncated. To
     *            obtain the next set of pages, pass in the
     *            <code>NextToken</code> from the response object of the
     *            previous page call.
     *            </p>
     */
    public void setNextToken(String nextToken) {
        this.nextToken = nextToken;
    }

    /**
     * <p>
     * A token generated by the Athena service that specifies where to continue
     * pagination if a previous request was truncated. To obtain the next set of
     * pages, pass in the <code>NextToken</code> from the response object of the
     * previous page call.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     * <p>
     * <b>Constraints:</b><br/>
     * <b>Length: </b>1 - 1024<br/>
     *
     * @param nextToken <p>
     *            A token generated by the Athena service that specifies where
     *            to continue pagination if a previous request was truncated. To
     *            obtain the next set of pages, pass in the
     *            <code>NextToken</code> from the response object of the
     *            previous page call.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public GetQueryResultsResult withNextToken(String nextToken) {
        this.nextToken = nextToken;
        return this;
    }

    /**
     * Returns a string representation of this object; useful for testing and
     * debugging.
     *
     * @return A string representation of this object.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("{");
        if (getUpdateCount() != null)
            sb.append("UpdateCount: " + getUpdateCount() + ",");
        if (getResultSet() != null)
            sb.append("ResultSet: " + getResultSet() + ",");
        if (getNextToken() != null)
            sb.append("NextToken: " + getNextToken());
        sb.append("}");
        return sb.toString();
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int hashCode = 1;

        hashCode = prime * hashCode
                + ((getUpdateCount() == null) ? 0 : getUpdateCount().hashCode());
        hashCode = prime * hashCode + ((getResultSet() == null) ? 0 : getResultSet().hashCode());
        hashCode = prime * hashCode + ((getNextToken() == null) ? 0 : getNextToken().hashCode());
        return hashCode;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;

        if (obj instanceof GetQueryResultsResult == false)
            return false;
        GetQueryResultsResult other = (GetQueryResultsResult) obj;

        if (other.getUpdateCount() == null ^ this.getUpdateCount() == null)
            return false;
        if (other.getUpdateCount() != null
                && other.getUpdateCount().equals(this.getUpdateCount()) == false)
            return false;
        if (other.getResultSet() == null ^ this.getResultSet() == null)
            return false;
        if (other.getResultSet() != null
                && other.getResultSet().equals(this.getResultSet()) == false)
            return false;
        if (other.getNextToken() == null ^ this.getNextToken() == null)
            return false;
        if (other.getNextToken() != null
                && other.getNextToken().equals(this.getNextToken()) == false)
            return false;
        return true;
    }
}
