/*
 * Copyright 2010-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *  http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package com.amazonaws.services.amazonredshift.model;

import java.io.Serializable;

import com.amazonaws.AmazonWebServiceRequest;

/**
 * <p>
 * Modifies an existing Amazon Redshift event notification subscription.
 * </p>
 */
public class ModifyEventSubscriptionRequest extends AmazonWebServiceRequest implements Serializable {
    /**
     * <p>
     * The name of the modified Amazon Redshift event notification subscription.
     * </p>
     */
    private String subscriptionName;

    /**
     * <p>
     * The Amazon Resource Name (ARN) of the SNS topic to be used by the event
     * notification subscription.
     * </p>
     */
    private String snsTopicArn;

    /**
     * <p>
     * The type of source that will be generating the events. For example, if
     * you want to be notified of events generated by a cluster, you would set
     * this parameter to cluster. If this value is not specified, events are
     * returned for all Amazon Redshift objects in your AWS account. You must
     * specify a source type in order to specify source IDs.
     * </p>
     * <p>
     * Valid values: cluster, cluster-parameter-group, cluster-security-group,
     * cluster-snapshot, and scheduled-action.
     * </p>
     */
    private String sourceType;

    /**
     * <p>
     * A list of one or more identifiers of Amazon Redshift source objects. All
     * of the objects must be of the same type as was specified in the source
     * type parameter. The event subscription will return only events generated
     * by the specified objects. If not specified, then events are returned for
     * all objects within the source type specified.
     * </p>
     * <p>
     * Example: my-cluster-1, my-cluster-2
     * </p>
     * <p>
     * Example: my-snapshot-20131010
     * </p>
     */
    private java.util.List<String> sourceIds;

    /**
     * <p>
     * Specifies the Amazon Redshift event categories to be published by the
     * event notification subscription.
     * </p>
     * <p>
     * Values: configuration, management, monitoring, security
     * </p>
     */
    private java.util.List<String> eventCategories;

    /**
     * <p>
     * Specifies the Amazon Redshift event severity to be published by the event
     * notification subscription.
     * </p>
     * <p>
     * Values: ERROR, INFO
     * </p>
     */
    private String severity;

    /**
     * <p>
     * A Boolean value indicating if the subscription is enabled.
     * <code>true</code> indicates the subscription is enabled
     * </p>
     */
    private Boolean enabled;

    /**
     * <p>
     * The name of the modified Amazon Redshift event notification subscription.
     * </p>
     *
     * @return <p>
     *         The name of the modified Amazon Redshift event notification
     *         subscription.
     *         </p>
     */
    public String getSubscriptionName() {
        return subscriptionName;
    }

    /**
     * <p>
     * The name of the modified Amazon Redshift event notification subscription.
     * </p>
     *
     * @param subscriptionName <p>
     *            The name of the modified Amazon Redshift event notification
     *            subscription.
     *            </p>
     */
    public void setSubscriptionName(String subscriptionName) {
        this.subscriptionName = subscriptionName;
    }

    /**
     * <p>
     * The name of the modified Amazon Redshift event notification subscription.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param subscriptionName <p>
     *            The name of the modified Amazon Redshift event notification
     *            subscription.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public ModifyEventSubscriptionRequest withSubscriptionName(String subscriptionName) {
        this.subscriptionName = subscriptionName;
        return this;
    }

    /**
     * <p>
     * The Amazon Resource Name (ARN) of the SNS topic to be used by the event
     * notification subscription.
     * </p>
     *
     * @return <p>
     *         The Amazon Resource Name (ARN) of the SNS topic to be used by the
     *         event notification subscription.
     *         </p>
     */
    public String getSnsTopicArn() {
        return snsTopicArn;
    }

    /**
     * <p>
     * The Amazon Resource Name (ARN) of the SNS topic to be used by the event
     * notification subscription.
     * </p>
     *
     * @param snsTopicArn <p>
     *            The Amazon Resource Name (ARN) of the SNS topic to be used by
     *            the event notification subscription.
     *            </p>
     */
    public void setSnsTopicArn(String snsTopicArn) {
        this.snsTopicArn = snsTopicArn;
    }

    /**
     * <p>
     * The Amazon Resource Name (ARN) of the SNS topic to be used by the event
     * notification subscription.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param snsTopicArn <p>
     *            The Amazon Resource Name (ARN) of the SNS topic to be used by
     *            the event notification subscription.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public ModifyEventSubscriptionRequest withSnsTopicArn(String snsTopicArn) {
        this.snsTopicArn = snsTopicArn;
        return this;
    }

    /**
     * <p>
     * The type of source that will be generating the events. For example, if
     * you want to be notified of events generated by a cluster, you would set
     * this parameter to cluster. If this value is not specified, events are
     * returned for all Amazon Redshift objects in your AWS account. You must
     * specify a source type in order to specify source IDs.
     * </p>
     * <p>
     * Valid values: cluster, cluster-parameter-group, cluster-security-group,
     * cluster-snapshot, and scheduled-action.
     * </p>
     *
     * @return <p>
     *         The type of source that will be generating the events. For
     *         example, if you want to be notified of events generated by a
     *         cluster, you would set this parameter to cluster. If this value
     *         is not specified, events are returned for all Amazon Redshift
     *         objects in your AWS account. You must specify a source type in
     *         order to specify source IDs.
     *         </p>
     *         <p>
     *         Valid values: cluster, cluster-parameter-group,
     *         cluster-security-group, cluster-snapshot, and scheduled-action.
     *         </p>
     */
    public String getSourceType() {
        return sourceType;
    }

    /**
     * <p>
     * The type of source that will be generating the events. For example, if
     * you want to be notified of events generated by a cluster, you would set
     * this parameter to cluster. If this value is not specified, events are
     * returned for all Amazon Redshift objects in your AWS account. You must
     * specify a source type in order to specify source IDs.
     * </p>
     * <p>
     * Valid values: cluster, cluster-parameter-group, cluster-security-group,
     * cluster-snapshot, and scheduled-action.
     * </p>
     *
     * @param sourceType <p>
     *            The type of source that will be generating the events. For
     *            example, if you want to be notified of events generated by a
     *            cluster, you would set this parameter to cluster. If this
     *            value is not specified, events are returned for all Amazon
     *            Redshift objects in your AWS account. You must specify a
     *            source type in order to specify source IDs.
     *            </p>
     *            <p>
     *            Valid values: cluster, cluster-parameter-group,
     *            cluster-security-group, cluster-snapshot, and
     *            scheduled-action.
     *            </p>
     */
    public void setSourceType(String sourceType) {
        this.sourceType = sourceType;
    }

    /**
     * <p>
     * The type of source that will be generating the events. For example, if
     * you want to be notified of events generated by a cluster, you would set
     * this parameter to cluster. If this value is not specified, events are
     * returned for all Amazon Redshift objects in your AWS account. You must
     * specify a source type in order to specify source IDs.
     * </p>
     * <p>
     * Valid values: cluster, cluster-parameter-group, cluster-security-group,
     * cluster-snapshot, and scheduled-action.
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param sourceType <p>
     *            The type of source that will be generating the events. For
     *            example, if you want to be notified of events generated by a
     *            cluster, you would set this parameter to cluster. If this
     *            value is not specified, events are returned for all Amazon
     *            Redshift objects in your AWS account. You must specify a
     *            source type in order to specify source IDs.
     *            </p>
     *            <p>
     *            Valid values: cluster, cluster-parameter-group,
     *            cluster-security-group, cluster-snapshot, and
     *            scheduled-action.
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public ModifyEventSubscriptionRequest withSourceType(String sourceType) {
        this.sourceType = sourceType;
        return this;
    }

    /**
     * <p>
     * A list of one or more identifiers of Amazon Redshift source objects. All
     * of the objects must be of the same type as was specified in the source
     * type parameter. The event subscription will return only events generated
     * by the specified objects. If not specified, then events are returned for
     * all objects within the source type specified.
     * </p>
     * <p>
     * Example: my-cluster-1, my-cluster-2
     * </p>
     * <p>
     * Example: my-snapshot-20131010
     * </p>
     *
     * @return <p>
     *         A list of one or more identifiers of Amazon Redshift source
     *         objects. All of the objects must be of the same type as was
     *         specified in the source type parameter. The event subscription
     *         will return only events generated by the specified objects. If
     *         not specified, then events are returned for all objects within
     *         the source type specified.
     *         </p>
     *         <p>
     *         Example: my-cluster-1, my-cluster-2
     *         </p>
     *         <p>
     *         Example: my-snapshot-20131010
     *         </p>
     */
    public java.util.List<String> getSourceIds() {
        return sourceIds;
    }

    /**
     * <p>
     * A list of one or more identifiers of Amazon Redshift source objects. All
     * of the objects must be of the same type as was specified in the source
     * type parameter. The event subscription will return only events generated
     * by the specified objects. If not specified, then events are returned for
     * all objects within the source type specified.
     * </p>
     * <p>
     * Example: my-cluster-1, my-cluster-2
     * </p>
     * <p>
     * Example: my-snapshot-20131010
     * </p>
     *
     * @param sourceIds <p>
     *            A list of one or more identifiers of Amazon Redshift source
     *            objects. All of the objects must be of the same type as was
     *            specified in the source type parameter. The event subscription
     *            will return only events generated by the specified objects. If
     *            not specified, then events are returned for all objects within
     *            the source type specified.
     *            </p>
     *            <p>
     *            Example: my-cluster-1, my-cluster-2
     *            </p>
     *            <p>
     *            Example: my-snapshot-20131010
     *            </p>
     */
    public void setSourceIds(java.util.Collection<String> sourceIds) {
        if (sourceIds == null) {
            this.sourceIds = null;
            return;
        }

        this.sourceIds = new java.util.ArrayList<String>(sourceIds);
    }

    /**
     * <p>
     * A list of one or more identifiers of Amazon Redshift source objects. All
     * of the objects must be of the same type as was specified in the source
     * type parameter. The event subscription will return only events generated
     * by the specified objects. If not specified, then events are returned for
     * all objects within the source type specified.
     * </p>
     * <p>
     * Example: my-cluster-1, my-cluster-2
     * </p>
     * <p>
     * Example: my-snapshot-20131010
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param sourceIds <p>
     *            A list of one or more identifiers of Amazon Redshift source
     *            objects. All of the objects must be of the same type as was
     *            specified in the source type parameter. The event subscription
     *            will return only events generated by the specified objects. If
     *            not specified, then events are returned for all objects within
     *            the source type specified.
     *            </p>
     *            <p>
     *            Example: my-cluster-1, my-cluster-2
     *            </p>
     *            <p>
     *            Example: my-snapshot-20131010
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public ModifyEventSubscriptionRequest withSourceIds(String... sourceIds) {
        if (getSourceIds() == null) {
            this.sourceIds = new java.util.ArrayList<String>(sourceIds.length);
        }
        for (String value : sourceIds) {
            this.sourceIds.add(value);
        }
        return this;
    }

    /**
     * <p>
     * A list of one or more identifiers of Amazon Redshift source objects. All
     * of the objects must be of the same type as was specified in the source
     * type parameter. The event subscription will return only events generated
     * by the specified objects. If not specified, then events are returned for
     * all objects within the source type specified.
     * </p>
     * <p>
     * Example: my-cluster-1, my-cluster-2
     * </p>
     * <p>
     * Example: my-snapshot-20131010
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param sourceIds <p>
     *            A list of one or more identifiers of Amazon Redshift source
     *            objects. All of the objects must be of the same type as was
     *            specified in the source type parameter. The event subscription
     *            will return only events generated by the specified objects. If
     *            not specified, then events are returned for all objects within
     *            the source type specified.
     *            </p>
     *            <p>
     *            Example: my-cluster-1, my-cluster-2
     *            </p>
     *            <p>
     *            Example: my-snapshot-20131010
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public ModifyEventSubscriptionRequest withSourceIds(java.util.Collection<String> sourceIds) {
        setSourceIds(sourceIds);
        return this;
    }

    /**
     * <p>
     * Specifies the Amazon Redshift event categories to be published by the
     * event notification subscription.
     * </p>
     * <p>
     * Values: configuration, management, monitoring, security
     * </p>
     *
     * @return <p>
     *         Specifies the Amazon Redshift event categories to be published by
     *         the event notification subscription.
     *         </p>
     *         <p>
     *         Values: configuration, management, monitoring, security
     *         </p>
     */
    public java.util.List<String> getEventCategories() {
        return eventCategories;
    }

    /**
     * <p>
     * Specifies the Amazon Redshift event categories to be published by the
     * event notification subscription.
     * </p>
     * <p>
     * Values: configuration, management, monitoring, security
     * </p>
     *
     * @param eventCategories <p>
     *            Specifies the Amazon Redshift event categories to be published
     *            by the event notification subscription.
     *            </p>
     *            <p>
     *            Values: configuration, management, monitoring, security
     *            </p>
     */
    public void setEventCategories(java.util.Collection<String> eventCategories) {
        if (eventCategories == null) {
            this.eventCategories = null;
            return;
        }

        this.eventCategories = new java.util.ArrayList<String>(eventCategories);
    }

    /**
     * <p>
     * Specifies the Amazon Redshift event categories to be published by the
     * event notification subscription.
     * </p>
     * <p>
     * Values: configuration, management, monitoring, security
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param eventCategories <p>
     *            Specifies the Amazon Redshift event categories to be published
     *            by the event notification subscription.
     *            </p>
     *            <p>
     *            Values: configuration, management, monitoring, security
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public ModifyEventSubscriptionRequest withEventCategories(String... eventCategories) {
        if (getEventCategories() == null) {
            this.eventCategories = new java.util.ArrayList<String>(eventCategories.length);
        }
        for (String value : eventCategories) {
            this.eventCategories.add(value);
        }
        return this;
    }

    /**
     * <p>
     * Specifies the Amazon Redshift event categories to be published by the
     * event notification subscription.
     * </p>
     * <p>
     * Values: configuration, management, monitoring, security
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param eventCategories <p>
     *            Specifies the Amazon Redshift event categories to be published
     *            by the event notification subscription.
     *            </p>
     *            <p>
     *            Values: configuration, management, monitoring, security
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public ModifyEventSubscriptionRequest withEventCategories(
            java.util.Collection<String> eventCategories) {
        setEventCategories(eventCategories);
        return this;
    }

    /**
     * <p>
     * Specifies the Amazon Redshift event severity to be published by the event
     * notification subscription.
     * </p>
     * <p>
     * Values: ERROR, INFO
     * </p>
     *
     * @return <p>
     *         Specifies the Amazon Redshift event severity to be published by
     *         the event notification subscription.
     *         </p>
     *         <p>
     *         Values: ERROR, INFO
     *         </p>
     */
    public String getSeverity() {
        return severity;
    }

    /**
     * <p>
     * Specifies the Amazon Redshift event severity to be published by the event
     * notification subscription.
     * </p>
     * <p>
     * Values: ERROR, INFO
     * </p>
     *
     * @param severity <p>
     *            Specifies the Amazon Redshift event severity to be published
     *            by the event notification subscription.
     *            </p>
     *            <p>
     *            Values: ERROR, INFO
     *            </p>
     */
    public void setSeverity(String severity) {
        this.severity = severity;
    }

    /**
     * <p>
     * Specifies the Amazon Redshift event severity to be published by the event
     * notification subscription.
     * </p>
     * <p>
     * Values: ERROR, INFO
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param severity <p>
     *            Specifies the Amazon Redshift event severity to be published
     *            by the event notification subscription.
     *            </p>
     *            <p>
     *            Values: ERROR, INFO
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public ModifyEventSubscriptionRequest withSeverity(String severity) {
        this.severity = severity;
        return this;
    }

    /**
     * <p>
     * A Boolean value indicating if the subscription is enabled.
     * <code>true</code> indicates the subscription is enabled
     * </p>
     *
     * @return <p>
     *         A Boolean value indicating if the subscription is enabled.
     *         <code>true</code> indicates the subscription is enabled
     *         </p>
     */
    public Boolean isEnabled() {
        return enabled;
    }

    /**
     * <p>
     * A Boolean value indicating if the subscription is enabled.
     * <code>true</code> indicates the subscription is enabled
     * </p>
     *
     * @return <p>
     *         A Boolean value indicating if the subscription is enabled.
     *         <code>true</code> indicates the subscription is enabled
     *         </p>
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * <p>
     * A Boolean value indicating if the subscription is enabled.
     * <code>true</code> indicates the subscription is enabled
     * </p>
     *
     * @param enabled <p>
     *            A Boolean value indicating if the subscription is enabled.
     *            <code>true</code> indicates the subscription is enabled
     *            </p>
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * <p>
     * A Boolean value indicating if the subscription is enabled.
     * <code>true</code> indicates the subscription is enabled
     * </p>
     * <p>
     * Returns a reference to this object so that method calls can be chained
     * together.
     *
     * @param enabled <p>
     *            A Boolean value indicating if the subscription is enabled.
     *            <code>true</code> indicates the subscription is enabled
     *            </p>
     * @return A reference to this updated object so that method calls can be
     *         chained together.
     */
    public ModifyEventSubscriptionRequest withEnabled(Boolean enabled) {
        this.enabled = enabled;
        return this;
    }

    /**
     * Returns a string representation of this object; useful for testing and
     * debugging.
     *
     * @return A string representation of this object.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("{");
        if (getSubscriptionName() != null)
            sb.append("SubscriptionName: " + getSubscriptionName() + ",");
        if (getSnsTopicArn() != null)
            sb.append("SnsTopicArn: " + getSnsTopicArn() + ",");
        if (getSourceType() != null)
            sb.append("SourceType: " + getSourceType() + ",");
        if (getSourceIds() != null)
            sb.append("SourceIds: " + getSourceIds() + ",");
        if (getEventCategories() != null)
            sb.append("EventCategories: " + getEventCategories() + ",");
        if (getSeverity() != null)
            sb.append("Severity: " + getSeverity() + ",");
        if (getEnabled() != null)
            sb.append("Enabled: " + getEnabled());
        sb.append("}");
        return sb.toString();
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int hashCode = 1;

        hashCode = prime * hashCode
                + ((getSubscriptionName() == null) ? 0 : getSubscriptionName().hashCode());
        hashCode = prime * hashCode
                + ((getSnsTopicArn() == null) ? 0 : getSnsTopicArn().hashCode());
        hashCode = prime * hashCode + ((getSourceType() == null) ? 0 : getSourceType().hashCode());
        hashCode = prime * hashCode + ((getSourceIds() == null) ? 0 : getSourceIds().hashCode());
        hashCode = prime * hashCode
                + ((getEventCategories() == null) ? 0 : getEventCategories().hashCode());
        hashCode = prime * hashCode + ((getSeverity() == null) ? 0 : getSeverity().hashCode());
        hashCode = prime * hashCode + ((getEnabled() == null) ? 0 : getEnabled().hashCode());
        return hashCode;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;

        if (obj instanceof ModifyEventSubscriptionRequest == false)
            return false;
        ModifyEventSubscriptionRequest other = (ModifyEventSubscriptionRequest) obj;

        if (other.getSubscriptionName() == null ^ this.getSubscriptionName() == null)
            return false;
        if (other.getSubscriptionName() != null
                && other.getSubscriptionName().equals(this.getSubscriptionName()) == false)
            return false;
        if (other.getSnsTopicArn() == null ^ this.getSnsTopicArn() == null)
            return false;
        if (other.getSnsTopicArn() != null
                && other.getSnsTopicArn().equals(this.getSnsTopicArn()) == false)
            return false;
        if (other.getSourceType() == null ^ this.getSourceType() == null)
            return false;
        if (other.getSourceType() != null
                && other.getSourceType().equals(this.getSourceType()) == false)
            return false;
        if (other.getSourceIds() == null ^ this.getSourceIds() == null)
            return false;
        if (other.getSourceIds() != null
                && other.getSourceIds().equals(this.getSourceIds()) == false)
            return false;
        if (other.getEventCategories() == null ^ this.getEventCategories() == null)
            return false;
        if (other.getEventCategories() != null
                && other.getEventCategories().equals(this.getEventCategories()) == false)
            return false;
        if (other.getSeverity() == null ^ this.getSeverity() == null)
            return false;
        if (other.getSeverity() != null && other.getSeverity().equals(this.getSeverity()) == false)
            return false;
        if (other.getEnabled() == null ^ this.getEnabled() == null)
            return false;
        if (other.getEnabled() != null && other.getEnabled().equals(this.getEnabled()) == false)
            return false;
        return true;
    }
}
